### ISSUE TITLE
window上中文路径出现失败的问题

### ISSUE THREAD

**Issue by yingnierxiao** [sisong/HDiffPatch#104]

**Comment by sisong** [comment]
请问你的操作系统和编译环境设置？      
   
我在windowsXP 32bit系统下测试过中文文件名，没有遇到问题；

**Comment by yingnierxiao** [comment]
window 10和window7 vs2015编译出来的64位的

**Comment by sisong** [comment]
我手边没有win10,你用我编译出来的exe试试呢？  下载： https://github.com/sisong/HDiffPatch/releases

**Comment by sisong** [comment]
如果是区域问题可以试试在文件打开函数前添加：
setlocale( LC_ALL, "" );

**Comment by sisong** [comment]
最近修复过2个bug；是否是特定文件触发了bug，而不是中文造成的问题？   @yingnierxiao
