### ISSUE TITLE
还有个问题请教一下，采用压缩选项后，在android上进行合成时，发现解压过程非常耗费内存，这个有没有办法优化呢？

### ISSUE THREAD

**Issue by sisong** [sisong/HDiffPatch#105]
之前问题解决了哈。还有个问题请教一下，采用压缩选项后，在android上进行合成时，发现解压过程非常耗费内存，这个有没有办法优化呢？

_Originally posted by @Ryan-Shz in https://github.com/sisong/HDiffPatch/issues/99#issuecomment-449398650_

**Comment by Ryan-Shz** [comment]
经过测试发现，zstd的压缩比是最小的，所以我采用了zstd压缩，然后使用hdiffz中的patch函数进行合成，80M左右的差分包，进行解压的时候内存占用大概是大几十M。

**Comment by sisong** [comment]
zstd不太适合这个场景，压缩率高的时候，解压特别占用内存，还是建议用lzma。    
Android上使用hpatchz建议编译时只打开需要的解压缩插件，并使用-s-memsize 作为运行参数

**Comment by Ryan-Shz** [comment]
原来如此！为了让查分包尽量小，我采用了zstd-22压缩级别!  : )  内存增长速度把我吓到了！非常感谢，我明天测试一下lzma的运行情况

**Comment by sisong** [comment]
你在对apk进行增量升级？ 有调查过我的 https://github.com/sisong/ApkDiffPatch 这个针对性的库吗？

**Comment by sisong** [comment]
#107 有助于优化这个问题
