### ISSUE TITLE
运行时，控制台输出当前的执行参数配置 #rejected

### ISSUE THREAD

**Issue by sisong** [sisong/HDiffPatch#114]

**Comment by housisong** [comment]
## integrated.MagicBuild
该仓库存储了需要集成到[integrated](https://dev.flybot.sg/client/integrated)项目中的一些dll库文件；   
这些dll库文件来源于integrated项目中的Clojure代码，使用Magic编译后得到；    
以后如果Magic和其[集成方式](https://github.com/nasser/Magic.Unity)支持更好的集成方式时可能修改。
