### ISSUE TITLE
 如果内容经过加密算法，有没办法在解密的情况下打补丁

### ISSUE THREAD

**Issue by yingnierxiao** [sisong/HDiffPatch#116]

**Comment by yingnierxiao** [comment]
问题是这样的  sqlite db 有加密的版本，加密的情况内容只要改动就没法patch，看来只能用脚本更新才行

**Comment by sisong** [comment]
加密状态的数据，和压缩状态的数据类似，都对diff patch不友好

**Comment by sisong** [comment]
"靠db自己的更新脚本"   它自己能更新，就是不知道有没有开放一些api接口或者开放自定义插件来完成更新； 这样的话还是有一点机会的
