### ISSUE TITLE
将代码放入独立的静态库项目中  #cancel

### ISSUE THREAD

**Issue by sisong** [sisong/HDiffPatch#154]
先实验xcode；可能有利于减少编译后文件大小；      
因为 代码作为静态库被链接时可执行程序不会链接包含没有用到的功能；    

只是编译设置的不同造成？

**Comment by sisong** [comment]
xcode编译出来的hdiffz和hpatchz可执行程序都变小了！  diff小了200k，patch小了10k；

**Comment by sisong** [comment]
Deployment Postprocessing  开启后优化不少

**Comment by mynameisenthusiasm** [comment]
请问要怎么编译到静态库啊

**Comment by sisong** [comment]
不同的编译器和操作系统可能都不同，你可以自己网上搜索一下怎么创建其静态库
