### ISSUE TITLE
执行path时旧目录里某个DLL文件被程序自身占用导致无法更新

### ISSUE THREAD

**Issue by Alic123** [sisong/HDiffPatch#172]
执行 hpatchz -f  oldPath pathName oldPath  时，提示can't remove old file xxx& can't move new file to oldDirectory xxxxxxx；
   debug发现该dll文件被程序hpatchz.exe自身占用了，调用GetLastError返回错误代码32（进程无法访问文件，因为另一个程序正在使用此文件）  该dll文件很确定没有被其他程序占用

**Comment by Alic123** [comment]
如果用hdiffz单独制作该dll的补丁，再执行 hpatchz -f dll路径 补丁名 dll路径，程序就不会报错

**Comment by sisong** [comment]
"该dll文件被程序hpatchz.exe自身占用了"      
1. 原hpatchz并没有调用除系统外的其他dll，自身就是一个完整的程序；   
1. 是否是某种权限问题，如 app还没有完全退出，hpatchz要修改自己，或者病毒检测之类的？ 
1. 我们的PC程序也在使用这个库（目录与目录之间的diff和patch），也有大量用户，并没有人报告这个问题；

**Comment by sisong** [comment]
我看了一下这个错误的位置，实际是调用_wrename 或 rename 函数来移动文件时失败，[参见说明](https://docs.microsoft.com/zh-cn/cpp/c-runtime-library/reference/rename-wrename?view=vs-2019)；   
而你试验单独的patch dll时，实际上是先生成一个new file,然后删除old file，然后把新文件rename成旧名称；      
这两者之间的差别较小，大的差别是前一个rename跨越了不同的目录，看解释这个API是支持的；

**Comment by sisong** [comment]
我会检查一下看是否过早执行了remove

**Comment by sisong** [comment]
已经确认该bug，确实remove时不正确；（苹果系统下能够正确执行，而在windows下会出现类似bug； 而我们的windows下的产品的使用策略却正好避开了这个bug）
