### ISSUE TITLE
make: cannot find zlib.h

### ISSUE THREAD

**Issue by sangnar** [sisong/HDiffPatch#176]
![error0](https://user-images.githubusercontent.com/31640220/64400908-422ff380-d0a9-11e9-82d5-4e16c119adc7.PNG)
![error1](https://user-images.githubusercontent.com/31640220/64400914-45c37a80-d0a9-11e9-9ab9-4c55179a5fa5.PNG)

Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
Linux P1209-1 4.4.0-17763-Microsoft #1-Microsoft Fri Sep 14 14:34:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sisong** [comment]
zlib.h  default  depends on your build environment； “cannot find” means it doesn't work;        
You can also add zlib code by yourself as LZMA;

**Comment by sangnar** [comment]
I thought I should use zlib you provide.
thank you.
