### ISSUE TITLE
check v==(size_t)v error

### ISSUE THREAD

**Issue by sangnar** [sisong/HDiffPatch#177]
windows x86 build

when check `unpackToSize(&savedOldRefSize,heapClip)` in dir_patch.c:203

```
#define unpackToSize(psize,sclip) { \
    TUInt v; check(_TStreamCacheClip_unpackUIntWithTag(sclip,&v,0)); \
    if (sizeof(TUInt)!=sizeof(size_t)) check(v==(size_t)v); \
    *(psize)=(size_t)v; }
```

my `v` size is 7199627868
so `(size_t)v` is 2904660572
occur check v==(size_t)v error in console

how can i fix it?

can i handle this v size when i diff?

**Comment by sisong** [comment]
try unpackUIntTo    
maybe a bug，I will check it

**Comment by sangnar** [comment]
Yeah, It seems that have exceeded the integer range.
i will try unpackUIntTo.
Thanks.
