### ISSUE TITLE
no dll export/import flag?

### ISSUE THREAD

**Issue by RPG3D** [sisong/HDiffPatch#183]
like lz4's LZ4LIB_API flag, can help me to build an dll&lib for c++

**Comment by sisong** [comment]
> like lz4's LZ4LIB_API flag

You can create a new code file to export your required APIs, and depends on your defined interface;    
     
hdiffpatch supports APIs with different  time or memory algorithm complexity, supports diff&patch between single object or multiple objects, supports multiple compresser and hash plugins; this determines that not needed all these features in practical applications;        
I recommendation is to strip code to the features only needed by application;
