### ISSUE TITLE
比较目标是路径时，能不能增加排除文件列表？

### ISSUE THREAD

**Issue by 0rt** [sisong/HDiffPatch#184]
有些文件我知道是没用的，仍然会比较，既浪费时间又增大了差分文件体积，能不能引入类似压缩软件的排除文件列表？
类似7zd  -x!data.log -x!foo.tmp 和 -x!@filelist.txt

**Comment by sisong** [comment]
> “排除文件列表”    

参见-g参数：
```
-g#ignorePath[#ignorePath#...]
      set iGnore path list when Directory Diff; ignore path list such as:
        #.DS_Store#desktop.ini#*thumbs*.db#.git*#.svn/#cache_*/00*11/*.tmp
      # means separator between names; (if char # in name, need write #: )
      * means can match any chars in name; (if char * in name, need write *: );
      / at the end of name means must match directory;
  -g-old#ignorePath[#ignorePath#...]
      set iGnore path list in oldPath when Directory Diff;
      if oldFile can be changed, need add it in old ignore list;
  -g-new#ignorePath[#ignorePath#...]
      set iGnore path list in newPath when Directory Diff;
      in general, new ignore list should is empty;
````
   
另外推荐先用-g和-M生成参与diff的文件列表文件：`hdiffz [-g#...] [-C-checksumType] inputPath -M#outManifestTxtFile`
再用列表来diff：`hdiffz [options] -M-old#oldManifestFile -M-new#newManifestFile oldPath newPath outDiffFile`

**Comment by 0rt** [comment]
谢谢。看来是我读帮助没仔细。其实我不对命令行不能说很熟悉，想问一下hpatchz的sfx生成的用法我不太懂。比如我先用hdiffz生成了一个叫bb的diff文件，然后想生成一个自执行文件z.exe，用的命令：
hpatchz bb -X#z.exe
提示和错误为：
selfExecute: "hpatchz"
diffFile   : "bb"
out sfxFile: "z.exe"

createSfx() open selfExecuteFile read ERROR!

请问怎么修正

**Comment by sisong** [comment]
> selfExecute: "hpatchz"   
应该是没有找到"hpatchz"这个文件，用 这个命令`hpatchz -X-exe#selfExecuteFile diffFile -X#outSelfExtractArchive` 指定吧； （这个命令可以制作跨平台的sfx包）

**Comment by 0rt** [comment]
哦，明白，会用了，感谢。

**Comment by sergeevabc** [comment]
Sorry, but I do not understand how to create `*.exe` from `*.hdiff`. Too complicated.

**Comment by sisong** [comment]
run SFX: `$ selfExtractArchive [[options] oldPath -X outNewPath]`      
if run with: `$ selfExtractArchive`  ,  it same as `$ selfExtractArchive -f "" -X  "./"`     
the oldPath&outNewPath info it is not saved in the file selfExtractArchive, you can edit source code to support it;
