### ISSUE TITLE
目录diff模式是否不支持目录嵌套

### ISSUE THREAD

**Issue by li5414** [sisong/HDiffPatch#186]
目录1
目录1->目录2
目录1->目录2->文件3

hdiffz -C-no 1 -M#1.minifest
output: test manifestFile found an error: not found path count in manifest error! ERROR!

hdiffz 1 -M#1.minifest
test manifestFile found an error: check checksumEnd!=posEnd error! ERROR!

**Comment by sisong** [comment]
* 支持目录嵌套；   
* `hdiffz -C-no 1 -M#1.minifest`  当使用-C-no来创建清单文件时出错，是一个bug；会在以后的版本中修复；另外不建议用-C-no关闭来关闭清单文件的检验功能：校验的存在可以避免历史文件版本的损坏；    
* `hdiffz 1 -M#1.minifest`  我这里无法重新；能否把你的测试文件夹打zip包发给我sisong@gmail.com

**Comment by li5414** [comment]
已发
文件是unity的assetbundle,chunk-based lz4压缩格式,可能是因为这个原因

**Comment by li5414** [comment]
清单文件其实已经创建出来了

**Comment by sisong** [comment]
找到原因了，windows下的目录路径符号`\`兼容造成的问题，会很快修复；  (macos和linux下没有这个问题)

**Comment by sisong** [comment]
已经更新，并且在windows下进行了minifest diff的测试
