### ISSUE TITLE
Is the output completely sequential?

### ISSUE THREAD

**Issue by BrianPugh** [sisong/HDiffPatch#188]
Hi Sisong,

In my application, I have compressed data that I would like to patch. The binary diff on compressed data would be large, so I want to create (and apply) the diff on the uncompressed data (and then compress the diff). **When patching data, is the output purely sequential?** If so, I can compress the stream as I write to disk and save resources.

Thanks!

**Comment by sisong** [comment]
> When patching data, is the output purely sequential?   

yes   sequential   
>  I can compress the stream as I write to disk and save resources.    

you can;  (My lib [ApkDiffPatch](https://github.com/sisong/ApkDiffPatch) output is also as zip file )

**Comment by BrianPugh** [comment]
Thanks for the swift response!
