### ISSUE TITLE
Android版本Patch实现找不头文件 bzlib.h

### ISSUE THREAD

**Issue by h923745834** [sisong/HDiffPatch#190]
你好，在你的这个项目源码上，我想编译出.so文件。但在这个实现的过程中，遇到下面这个问题。
xxxx/app/src/main/cpp/decompress_plugin_demo.h:203:13: fatal error: 'bzlib.h' file not found
#   include "bzlib.h"
不知有现成的bzlib.h这个头文件和对应的xxx.so库文件吗？还是说需要自己自己去编译bzlib这个项目的源码？

**Comment by sisong** [comment]
你可以参考我的Android编译设置（带我推荐的压缩插件）： https://github.com/sisong/HDiffPatch/tree/master/builds/android_ndk_jni_mk    
你也可以下载到我release的.so文件： https://github.com/sisong/HDiffPatch/releases   
   
bzib插件可以用_CompressPlugin_bz2宏开关来控制，你可以关闭这个定义，只打开你需要的压缩插件；    
否则你需要下载对应的库： http://www.bzip.org/  或  https://github.com/sisong/bzip2
