### ISSUE TITLE
关于patch的src path /dest path 目录的问题

### ISSUE THREAD

**Issue by jiayanbo** [sisong/HDiffPatch#191]
你好作者！通过使用你的源码，发现有个地方没有用好，所以还请指点一下
命令：./hpatchz.exe "E:\patchtest\test_restore_break\PubRefineTest191205" "E:\patchtest\test_restore_break\test.patch" "E:\patchtest\test_restore_break\PubRefineTest191205" -f
环境：
操作系统windows
初始版本1.0 ， 新版2.0 ，patch文件从1.0——》2.0 都已准备好
新版旧版差异: 新版改了版本号文件1.0为2.0

这个时候源路径和目标路径 是一样的时候，源目录下会提示版本号文件，删除失败：如下
WARNING: can't remove old file "E:\patchtest\test_restore_break\PubRefineTest191205-\sonkwo_game_version.txt"
因为移除不掉导致了_wrename(oldPath_w, newPath_w) ==-1，
oldPath_w: 
   E:\patchtest\test_restore_break\PubRefineTest191205001.tmp\sonkwo_game_version.txt
newPath_w:
   E:\patchtest\test_restore_break\PubRefineTest191205\sonkwo_game_version.txt

错误信息是 newPath_w 的文件已经存在

我这里想到的办法是创建一个临时目录和1.0版本自己的patch ，然后先把1.0版还原到临时目录下，然后再以临时目录作为源 路径，再往最开始的1.0版路径下打patch,这样就不会报警告和错误了

因为看到了源码文件（hpatch_dir_listener.h）中标注了
   //delete file in oldPathList; //WARNING
   //delete dir in oldPathList; //not check
所以想咨询一下，这个属于bug吗？也就说明了源路径和目标路径相同的时候，修改文件就不能正常使用了，只能增加。有其他的方法直接在源目录里边更新吗，再此多谢啦

**Comment by sisong** [comment]
直接覆盖的用法是正确的，不能patch成功算bug；   你的exe是用的我发布的[最新版本](https://github.com/sisong/HDiffPatch/releases/download/v3.0.8/hdiffpatch_v3.0.8_ApkDiffPatch_v1.3.1_bin_beta.zip)吗？

**Comment by jiayanbo** [comment]
多谢，我用的是主分支版本编写的
版本3.8
Patch的覆盖原目录是可以了，但是做patch 文件出现了问题
现象：增加文件，删除文件，都可以，但删除目录会出现问题
测试：都在同一源文件基础上
第一次删除saves目录，做patch ok
     第二次删除sheltered_Data 目录，出现问题
4.0版编译不过去，所以没试，劳烦作者了！祝小年快乐！
命令：
./hdiffz.exe "E:\patchtest\test_restore_break\PubRefineTest191205" "E:\patchtest\test_restore_break\PubRefineTest191205-4.0" "E:\patchtest\test_restore_break\test_3.8_deldir.patch" –f
文件差异：
目录结构文件只删除一个目录./shelltered_Data
 
![6WZAZ(09TJM LTL({RO{P(P](https://user-images.githubusercontent.com/24917159/72610244-d5cfd580-3961-11ea-904b-f58b117b8cfa.png)


 
结果：
![LL5Q}P1PB)1SQQ~S$4X9JZF](https://user-images.githubusercontent.com/24917159/72610306-f861ee80-3961-11ea-985a-4c9b627af588.png)

**Comment by sisong** [comment]
要安装app，还要注册登陆 :(      
发到我的邮箱 sisong@gmail.com 或者  你建立一个公开临时项目，将文件包提交到项目里？

**Comment by sisong** [comment]
看你的错误提示，是 diff时报内存分配错误； 而默认的diff内存参数是-m，这将占用（10*总文件大小）的内存；怀疑是你的电脑内存不足？  你可以添加 -s-64参数试试

**Comment by jiayanbo** [comment]
针对内存分配错误的情况做了个测试：
       此目录下File_Size =   589MB,如果按照10倍来算是，所需内存是5个GB,此时电脑Available Memory = 5.8GB,可见内存是足够的啊。
       针对上述情况，发现如果没有-s-64 这个参数，那么isLoadAll=true，函数执行到图中位置就return了，如图
![~W)A{W(0RAXG83W)J (~KX3](https://user-images.githubusercontent.com/24917159/72695141-7eed1a80-3b72-11ea-8a8c-dd37d3bd4a13.png)
       然后跟踪到为什么是空的，找到了它调用了这个地方，发现m_SA_Large 确实没有分配空间，如图
![T@L2G{D0T2@UZ)2I($RQ)FR](https://user-images.githubusercontent.com/24917159/72697125-bb704480-3b79-11ea-94c0-163dafab9af0.png)
       
       如果加了参数，那么isLoadAll=false ,此时是可以做出patch 文件

现在能做出patch 文件了，所以就不发游戏源文件了，再次感谢作者的解惑

**Comment by sisong** [comment]
> "... 此时电脑Available Memory = 5.8GB,可见内存是足够的啊。"      

你的case，报内存分配错误，怀疑是你用了32bit diff程序；你应该使用64bit程序就不会遇到这个问题了；   

> 现在能做出patch 文件了，...       

内存够用的情况下还是建议用 -m参数而不是-s参数，-m大部分情况下产生的补丁文件比-s更小一些；
