### ISSUE TITLE
Bad LZMA2 decompression speed

### ISSUE THREAD

**Issue by Zeblote** [sisong/HDiffPatch#196]
Hi, I am using HDiffPatch for an automatic software updater, and it is working great! However, there is a problem with the performance of builtin LZMA2 decompression, it is almost 10 times slower than external LZMA2 decompression on large archives and fast systems (NVMe SSD, etc).

To reproduce, you can try these steps:

#### 1) Prepare patches.
1) Find some large folder for testing. My example has a total size of 1.2GB.
2) Create an empty folder to make a patch from, to quickly create a very large patch for testing.
3) Create compressed patch: `hdiffz.exe -m-0 -c-lzma2-9 EmptyFolder BigFolder Compressed.hdiff`.
4) Create normal patch: `hdiffz.exe -m-0 EmptyFolder BigFolder Normal.hdiff`.

With my test folder, these patches have sizes of 440MB and 1.2GB.

#### 2) Externally compress the normal patch with LZMA2.
1) Run `7z.exe a -mx9 Normal.7z Normal.hdiff`. This creates Normal.7z file with size of 420MB.
2) Delete Normal.hdiff.

#### 3) Time the externally compressed patch.
1) Run `7z.exe e Normal.7z` to decompress the Normal.hdiff file, this takes 2 seconds.
2) Run `hpatchz.exe -c-512m EmptyFolder Normal.hdiff TestNormal` to test applying the externally compressed patch, this takes 1-2 seconds.

This test takes around 3 seconds in total.

#### 4) Time the builtin compressed patch.
1) Run `hpatchz.exe -c-512m EmptyFolder Compressed.hdiff TestCompressed` to test applying the builtin compressed patch, this takes 21 seconds.

This test takes 9 times longer than externally decompressing.

I don't know exactly what is causing this issue (maybe not using the multi-threaded decompression API, maybe too small decompress buffer size?), but it would be very nice for it to be fixed, so LZMA2 compressed patches become viable to use!

**Comment by Zeblote** [comment]
It is worth noting that zstd compressed patches do not have this problem, here applying a builtin compressed patch is about the same speed as manually decompressing and applying uncompressed patch. But I would like to use LZMA2 compression as it gets better ratio with much faster encoding.

**Comment by sisong** [comment]
1. "7z.exe a -mx9 Normal.7z Normal.hdiff" out size 420MB    
   "hdiffz.exe -m-0 -c-lzma2-9 EmptyFolder BigFolder Compressed.hdiff" out size 440MB   
   you can try -c-lzma2-9-32m to improve compression rate
1. "maybe not using the multi-threaded decompression API,"     
   Yes, patch is run with single-thread;  1.2GB/(21s-3s) =~ 68MB/s is decompress speed;

**Comment by Zeblote** [comment]
`you can try -c-lzma2-9-32m to improve compression rate`
Thanks, this did make it a little smaller!

`now, patch & decompress is run with single-thread`
Do you have any plans to use the multithreaded version in the future?

`you can used "-s-128" replace "-m-0" create .hdiff file for updater test`
What does this do? When creating a patch from empty, this results in exactly the same size, but when creating a patch between two versions, -s-128 results in a patch up to 3 times larger than -m-0.

**Comment by sisong** [comment]
`Do you have any plans to use the multithreaded version in the future?`    
 run patch with multi-threaded，it should be a good idea  for large game!     
 But no plan now, Our team's app size is <200MB, and  patch speed is ok;      
   
`What does this do?`     
A  team told me that using "-s-48" is much faster than "-m-6", and the out size is not much different; their steam game are large（xGB）, and “-m“ memory and speed are difficult to accept.       
(Another team for large app, in order to always use "-m", configured a 512GB PC for run diff)

**Comment by Zeblote** [comment]
`A team told me that using "-s-48" is much faster than "-m-6", and the out size is not much different;`
Hmm this is very interesting, while there is a big difference in the uncompressed patch size, the patch created with -s-48 compresses better afterwards, so they actually end up with a very similar final size.

`Do you have example code of using the multi-threaded lzma2 dec API?`
I have never used it myself, but I was looking around yesterday and found this API:
https://github.com/sisong/lzma/blob/pthread/C/Lzma2DecMt.h#L46
And this single usage in the 7-zip program:
https://github.com/sisong/lzma/blob/pthread/CPP/7zip/Compress/Lzma2Decoder.cpp#L152

**Comment by Zeblote** [comment]
Slightly off topic: it might also be interesting to look at Fast LZMA2 library (https://github.com/conor42/fast-lzma2) for creating compressed patch, it provides hugely faster compression to LZMA2 format, while achieving almost the same ratio (< 1% difference in my tests)

**Comment by sisong** [comment]
like zstd, lzma;  lzham(https://github.com/richgel999/lzham_codec) is also suitable for patch scene.

**Comment by sergeevabc** [comment]
@Zeblote, do you experience slow decompress speed if a patch is created with `hdiffz -c-lzma-9 original changed patch.hdiff` ?

**Comment by Zeblote** [comment]
Never tried. We switched to zstd compression for the patch and haven't looked back. It both encodes and decodes way faster and the compression ratio is close enough.

**Comment by Zeblote** [comment]
If you go that route, it is useful to modify hdiffz so it doesn't go above level 18 and passes the threads=0 config param to zstd so it will use parallel encoding.

**Comment by sergeevabc** [comment]
@Zeblote, gosh, thanks! Zstd’s `--patch-from` slipped my mind a week later after news and `--help` has no mention of it (cc: @Cyan4973). I especially appreciate `zstd` comes as a single file with more natural syntax and it verifies oldFile before applying a patch (whereas `hpatchz` seems to do size check only, which is NOT ENOUGH  — perhaps, I should create a separate issue for developers to fix that, because even old good Xdelta3 verifies oldFile). By the way, is it correct that `hpatchz` has no zstd support? So far I see zlib, bzip and lzma1/2.

**Comment by Zeblote** [comment]
Oh, I was talking about using hdiffz to generate the patch and then zstd to compress it. There is a zstd integration, but not enabled by default, so it requires some slight tweaking. To verify file integrity before the patch (in case the user messed up) and after the patch (in case hdiffz/hpatchz messed up) we use BLAKE3 hash outside the library.

**Comment by Zeblote** [comment]
The `-s-48` tip above is also very valuable. All combined, this results in a fairly impressive patch system. We use it for a UE4 game with 1.5 GB ucas container file, growing over time. It only takes a minute to generate 2-4% patches between versions and they apply in two seconds on modern systems.

**Comment by Zeblote** [comment]
zstd `--patch-from` is not usable for our case as we need the directory patch feature. I'm not sure why people keep demonstrating patch tools between tarballs, that's useless, no one does that in reality... the original will exist as loose files on the user's computer in 99% of cases.

**Comment by sisong** [comment]
@sergeevabc     
. you can `#define _CompressPlugin_zstd` (or edit makefile with -D_CompressPlugin_zstd) for open support zstd，    
and used by `hdiffz -c-zstd[-{0..22}[-dictBits]] ...`       
. you can used `hdiffz -D -C-crc32 ...` when diff between two files;  and  `hpatchz -C-all ...` for checksum all data;   
 if `#define _ChecksumPlugin_md5` (or make with MD5=1),   then can used `hdiffz -D -C-md5 ...`

**Comment by sisong** [comment]
@Zeblote    
can create manifestTxtFile for every vesion  by `hdiffz [-g#...] -C-checksumType inputDir -M#outManifestTxtFile`      
then can read&edit manifestTxtFile,  diff between two dir with their manifestTxtFile always, it's will checkum all files before diff.

**Comment by sergeevabc** [comment]
@sisong, I am an ordinary user, not a developer with tools to build a new binary after changing #define or editing makefile. If this method of compression is gaining traction, then make it official and upload a new binary. As for `-D -C-crc32`, it looks more like a dirty workaround right now, because '-D` is meant for directories according to the manual. Nevertheless, I tried it and was not happy, because modified file is created regardless of the checksum error as follows. Compare it with the output of Xdelta, Zstd, and Courgette.

``` console
$ rhash -p "%f %s %c\n" * | column -t
changed.exe   11205128  7a4bc307
fake.exe      11206664  5dc8e965
original.exe  11206664  dfd4a9a7

$ hdiffz -c-lzma2-9 -D -C-crc32 original.exe changed.exe latest.hdiff
oldFile: "original.exe"
newFile: "changed1.exe"
outDiff: "latest.hdiff"
hdiffz run dir diff with compress plugin: "lzma2"
hdiffz run dir diff with checksum plugin: "crc32"

DirDiff old path count: 1
        new path count: 1 (fileCount:1)
       same file count: 0 (dataSize: 0)
    ref old file count: 1
   diff new file count: 1

run hdiffz:
  oldRefSize  : 11206664
  newRefSize  : 11205128 (all newSize: 11205128)
  (used one lzma2 dictSize: 4096  (input data: 8))
  (used one lzma2 dictSize: 4096  (input data: 2695))
  (used one lzma2 dictSize: 4096  (input data: 3622))
  (used one lzma2 dictSize: 4096  (input data: 4059))
  (used one lzma2 dictSize: 4096  (input data: 44))
  diffDataSize: 5943
  diff    time: 1.294 s

diffDataSize  : 6012
dir  diff time: 1.357 s
  out dirDiffFile ok!

load dirDiffFile for test by patch check:
diffDataSize  : 6012
dir patch time: 0.078 s
  patch check diff data ok!

all   time: 1.450 s

$ hpatchz fake.exe latest.hdiff .exe changed2.exe
old file: "fake.exe"
diffFile: "latest.hdiff"
out file: "changed2.exe"
hpatchz run with decompress plugin: "lzma2" (need decompress 3)
hpatchz run with checksum plugin: "crc32" (need checksum 2)
DirPatch new path count: 1 (fileCount:1)
    copy from old count: 0 (dataSize: 0)
     ref old file count: 1
     ref new file count: 1
oldRefSize  : 11206664
diffDataSize: 6012
newRefSize  : 11205128 (all newSize: 11205128)
check !self->isNewRefDataChecksumError error!
check self->_listener->writedFinish(self->_listener) error!
check _file_entry_end(self) error!
check _file_append_ready(self) error!
check patch_decompress_with_cache(out_newData,oldData,&hdiffData.base, self->_decompressPlugin,temp_cache,temp_cache_end) error!
newFile checksum ERROR!

hpatchz dir patch time: 0.109 s

$ rhash -p "%f %s %c\n" * | column -t
changed1.exe  11205128  7a4bc307
changed2.exe  11205128  7376ce60
fake.exe      11206664  5dc8e965
latest.hdiff  6012      92c611af
original.exe  11206664  dfd4a9a7     

$ xdelta -d -s fake.exe c:\temp\latest.xdelta changed3.exe 
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT          
xdelta3: normally this indicates that the source file is incorrect   
xdelta3: please verify the source file with sha1sum or equivalent    

$ zstd -d --patch-from=fake.exe c:\temp\latest.zdiff -o changed3.exe                               
latest.zdiff         : 0 MB...     latest.zdiff : Decoding error (36) : Restored data doesn't match checksum

$ courgette.exe -apply fake.exe c:\temp\latest.courgette changed3.exe
-apply failed.                                                                                                                        
```

**Comment by sisong** [comment]
now ,I unknow how to call lzma2 decompress by muti-thread;

**Comment by sisong** [comment]
in v5.0.0, I add a new format winDiff (diff with -WD), optimized patch speed;
on my PC, patch can run speed 1GB/S with lzma2 decompressor(no parallel decompress), and 2.5GB/s with zstd.
