### ISSUE TITLE
wildcard filenames / minimum size

### ISSUE THREAD

**Issue by seansiongco** [sisong/HDiffPatch#198]
your code works great, im tinkering on the code, and find it difficult to somehow to make it work only on filenames with wildcard patterns like *.vpk or *.exe, etc.  miminum size inclusion would also be very useful if we only want to patch big file sizes as files with smaller sizes can be discarded ignored as they can be easily copied.

**Comment by sisong** [comment]
1. The semantics supported by the lib are excluded(-g#ignorePath), not support "include";      
1. You can  modify "isNeedIgnore()" func to  meet your needs;
