### ISSUE TITLE
尝试用libdivsufsort替换sais优化速度

### ISSUE THREAD

**Issue by sisong** [sisong/HDiffPatch#20]
libdivsufsort可能需要修改来支持int64

**Comment by JayXon** [comment]
编译的时候加上-DBUILD_DIVSUFSORT64应该就可以了

**Comment by sisong** [comment]
排序的时候我的代码中（根据序号范围）同时用到int32和int64的序号，所以用预编译或者修改类型都不可行，需要实际生成2份函数的方式；

**Comment by JayXon** [comment]
这样是为了速度么？还是内存？如果全用64位会对速度有很大影响么？

**Comment by sisong** [comment]
主要考虑内存占用，当old数据小于2G的时候序号类型用int32，速度也略快一点；    
当前的dev版本完成了替换：“	测试用libdivsufsort替换sais了，大一点的数据快约30%，很小的数据的话sais快；”
