### ISSUE TITLE
Hdiffz.exe bad allocation ERROR

### ISSUE THREAD

**Issue by emrecpp** [sisong/HDiffPatch#200]
Hello,
When i try to compare 2 binary files with this command: hdiffz.exe "path_in" "path_out" "diff_out"
i get error i think because of file's bigger size (4.2gb). I have 16 GB ram. Any parameter to fix this issue? Thanks

Output:

hdiffz run with compress plugin: ""
oldDataSize : 4302049575
newDataSize : 4299809943
diff run an error: bad allocation ERROR!

all   time: 18.453 s

**Comment by sisong** [comment]
try add parameter:  -s-48

**Comment by emrecpp** [comment]
Thank you!
