### ISSUE TITLE
add support for set password for diff file

### ISSUE THREAD

**Issue by saeid0034** [sisong/HDiffPatch#202]
i think it will be great if you add support for set password to diff file
its make it more secure to use
thanks for your work

**Comment by sisong** [comment]
I don’t know if this requirement is widespread;   
HDiffPatch is more positioned as a library of the app;   
It is recommended that you do some custom processing in the data layer to meet your needs.

**Comment by saeid0034** [comment]
I used to think it would be an attractive feature ...
but i think you right
