### ISSUE TITLE
add support to build with mingw64

### ISSUE THREAD

**Issue by saeid0034** [sisong/HDiffPatch#203]
hi can you please add support to build HDIFF with mingw64?
i want to use your lib on QT and i use mingw64 on it

**Comment by sisong** [comment]
I have not used mingw64,   you  can try build it with:     
```
$ cd HDiffPatch
$ make 
```     
You can include  the source code files only your project required;

**Comment by saeid0034** [comment]
> I have not used mingw64, you can try build it with:
> 
> ```
> $ cd HDiffPatch
> $ make 
> ```
> 
> You can include the source code files only your project required;

i test it whit `mingw32-make` but its doesn't work
i know i can just include source file, but i want to build your source
thanks for reply

**Comment by saeid0034** [comment]
i dont get any answer, so i close it

**Comment by sisong** [comment]
I downloaded & installed mingw64 on windows, test make cmdline with LZMA=0   
out error log:  
```
...<out some .o files ok>... 
... ...
-c -o libHDiffPatch/HDiff/private_diff/libdivsufsort/divsufsort64.o libHDiffPatc
h/HDiff/private_diff/libdivsufsort/divsufsort64.c, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [<builtin>: libHDiffPatch/HDiff/private_diff/libdivsufsort/divsufsort6
4.o] Error 2
```
I don't know why not found it :(
