### ISSUE TITLE
Patch文件加上校验码？

### ISSUE THREAD

**Issue by RPG3D** [sisong/HDiffPatch#204]
一个Patch通常是针对一个特定的源文件和一个特定目标文件，可否在Ptach文件内部包含新旧文件的大小和XXHash值？执行Patch的时候计算旧文件XXHash是否符合。如果上层逻辑计算过了XXhas，就把值传给Patch函数，内部跳过旧文件校验。

**Comment by sisong** [comment]
1. 文件大小是一定会被检查（校验）的   
1. 如果用的命令行工具，可以在执行hdiffz时添加 “-D” “-C-crc32” 参数，就会添加多种数据的CRC32校验值在补丁包中；hpatchz进行补丁的时候，可以用 “-C-？”参数控制校验哪些数据，而默认会校验输出的new数据； （-C-支持的参数见相应命令行的帮助说明）   
1. 如果是自己使用了库内部的数据层diff&patch函数；有两个方案，一个是在生成的补丁数据外面，自己再“包裹”一层自己定义的数据来储存校验值； 或者也可以在版本升级配置信息中存储相关校验值（我们团队就是这样用的，这就能支持提前校验和边下载边校验）；
