### ISSUE TITLE
Diff size estimation

### ISSUE THREAD

**Issue by ifree** [sisong/HDiffPatch#205]
Hi , thanks for your amazing work.
I have a question about the patch size, is there a way to estimate the final diff size(without compression)?
I can imagine the worst case might be `old + new + diff_info`? correct me if I'm wrong.
Do you have some idea about it with regard to the with/without compression case?

thanks.

**Comment by sisong** [comment]
> I can imagine the worst case might be old + new + diff_info?    
 
worst case  O(new_size+tiny_diff_info)

> is there a way to estimate the final diff size(without compression)?    
 
It is expected that there must have deviations, and different cases may have different situations!   
For example, you can use similar code:
1. Call getCovers_by_stream or get_diff to get the covers;   
1. Estimate the patch size based on these covers info.

**Comment by ifree** [comment]
Thanks so much for the clarification, I'll have a try then. ::thumbs up::
