### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by ezhikus** [sisong/HDiffPatch#206]
Hi!
Could you please add some instructions about how to build HDiffPatch? For example, I tried to build it using Visual Studio and faced the problem with missing files. I suppose I should manually add some extra libraries (zlib? lzma? anything else?) to make it work? Is there any list of all dependencies and recomended versions to use?

Thank you

**Comment by sisong** [comment]
if on linux or macos, try : `$ make LZMA=0`     
or: `$ git clone https://github.com/sisong/lzma.git ../lzma`  and with :  `$ make`
