### ISSUE TITLE
What happened to patch-single-stream?

### ISSUE THREAD

**Issue by Zeblote** [sisong/HDiffPatch#207]
Hey, just noticed that this branch disappeared without being merged, along with all the refactored code you submitted to it. Is there a specific reason for this (did it not work out?)

**Comment by sisong** [comment]
The submitted code of patch-single-stream will be retained!    
There is still a lot of follow-up work, development time resources are insufficient, and the plan is not yet sure(as new library api, or as the main format for v3.0?),  so it was temporarily withdrawn.

**Comment by Zeblote** [comment]
I see! I was a bit concerned to see it disappear as we had already adopted that format due to it being a bit faster to apply the patch.

**Comment by sisong** [comment]
`already adopted`  !!!   
With the observer, the state of infinite possibilities collapsed.
