### ISSUE TITLE
it doesn't work in bin files it changes the blocks correctly but not put the content of the bits

### ISSUE THREAD

**Issue by reproteq** [sisong/HDiffPatch#210]
it doesn't work in binaries, it changes the blocks correctly but alters the content of the bits. Maybe it's a configuration problem?
When I apply the delta diff patch to the original binary it does it well but when I try to apply the delta diff patch to another similar binary and the same size it corrupts the content of the changes but changes the corresponding bit.
Could you help me figure this out.

<img width="1870" alt="issue-binari-diff-patch" src="https://user-images.githubusercontent.com/16064306/103234820-e7c34200-4940-11eb-8419-8209ed56cfa7.png">

**Comment by reproteq** [comment]
I solved this issue , only need change config parameters.

thanks

**Comment by housisong** [comment]
> "but when I try to apply the delta diff patch to another similar binary ..."       

delta:=diff(old,new);    new' := patch(old',delta) ;   need old'==old ,then new'==new;     

> "wat cmd i need send for good results in binary file?"     

try: hdiffz -m-1 -c-lzm2-9-64m ...

**Comment by reproteq** [comment]
can the patch be applied to a binary that is not the same but similar?
I tried many command combinations and it seems to change the correct offsets but the values in this bits is wrong.

hdiff.exe   old new patch
hpatch.exe other_old_similar  patch other_new_patched

  
<img width="1418" alt="issue-1" src="https://user-images.githubusercontent.com/16064306/103392148-c454ee80-4b1c-11eb-98fc-0c0608797106.png">

**Comment by sisong** [comment]
> "maybe your project is not appropriate for what I need to do?"    

not too appropriate；old data can't changed when used "hdiffz -m-* ..."   Now you can used  "hdiff -s-* -c-* ..." to created your needed delta.   
if you want used "-m-*"  for smaller delta, you need edit sourecode close the Extend Feature:    
* tryLinkExtend()  immediate return false; 
* extend_cover() immediate  return; 
* maybe others ...
