### ISSUE TITLE
latest release提供的so使用的空间复杂度

### ISSUE THREAD

**Issue by Picasso1990** [sisong/HDiffPatch#212]
你好，请问最新版本中so库在使用patch过程的空间复杂度是多少呢？不知道是对应如下文档中哪个api

patch() runs in O(oldSize+newSize) time , and requires (oldSize+newSize+diffSize)+O(1) bytes of memory;
patch_stream() requires O(1) bytes of memory;
patch_decompress() requires (4*decompress stream size)+O(1) bytes of memory.

**Comment by sisong** [comment]
内存复杂度是最后面的那个；    
 如果你的环境非常在意patch时的内存占用，可以自己使用create_single_compressed_diff()和patch_single_compressed_diff()；
patch时的内存复杂度更加可控：(stepMemSize memory) + (I/O cache memory) + (decompress memory*1)

**Comment by Picasso1990** [comment]
好的，请问
public static native int patch(String oldFileName, String diffFileName,
                                   String outNewFileName, long cacheMemory);

**Comment by Picasso1990** [comment]
好的，请问
```
public static native int patch(String oldFileName, String diffFileName,
                                   String outNewFileName, long cacheMemory);
```
中cacheMemory代表的是什么意思呢？设置这个值的大小会和patch速率，内存使用大小有哪些关联呢？

**Comment by sisong** [comment]
cacheMemory代表patch时申请使用的缓冲区内存（字节数），主要用于文件读写缓存，临时数据保存之类的；   
主要影响的是运行速度：小的话可以给个512*1024；内存较多的话给个4*1024*1024； 最大可以给到比oldFile大一些，这样最快；

**Comment by Picasso1990** [comment]
好的，请问如下命令错误：
```
hdiffz.exe test-3.apk test-4.apk hdiff-3-4.zip
old : "test-3.apk"
new : "test-4.apk"
out : "hdiff-3-4.zip"
hdiffz run with compress plugin: ""
oldDataSize : 2056726724
newDataSize : 1930554403
diff run an error: bad allocation ERROR!

all   time: 39.172 s
```
其中test-3.apk为1.98g， test-4.apk：1.76g，电脑配置16g（剩余可用没那么多，不过win应该有虚拟内存）
请问出现上面命令差分错误是什么原因呢？（内存不够分配？）

**Comment by sisong** [comment]
分配内存的时候没有成功。    
可能的解决方案：      
    用了32bit的可执行程序？ 那换64bit的程序；      
    内存真的不够用？  那添加 -s-16 参数来创建补丁，这也会快得多，但补丁文件可能略大一点点。
     
另外可以选择一个压缩插件来压缩输出的补丁数据，比如 -c-lzma2

**Comment by Picasso1990** [comment]
感谢您，请问
```
-s[-cacheSize] 
      DEFAULT -s-64m; oldPath loaded as Stream;
      requires (cacheSize+ 4*decompress stream size)+O(1) bytes of memory;
      cacheSize can like 262144 or 256k or 512m or 2g etc....
```
其中decompress stream size的大小是由lzma算法决定的吗？如果是的话有最大最小值吗？受哪些因素影响呢？
若不是的话是由哪些因素决定的呢

**Comment by sisong** [comment]
完全由diff时的lzma算法压缩使用的字典大小决定的，你可以在diff参数里设定；   
```
        -c-lzma[-{0..9}[-dictSize]]     DEFAULT level 7
            dictSize can like 4096 or 4k or 4m or 128m etc..., DEFAULT 8m
        -c-lzma2[-{0..9}[-dictSize]]    DEFAULT level 7
            dictSize can like 4096 or 4k or 4m or 128m etc..., DEFAULT 8m
```

**Comment by Picasso1990** [comment]
感谢您，请问
```
-p-parallelThreadNumber
-c-compressType[-compressLevel] 
```
如上两条命令，
1、-p不指定情况下是默认单线程执行吗？
2、-c不指定情况下默认的压缩类型是什么呢？
3、在默认执行hdiffz时没有看到decompress stream size的相关输出，假如2问中不指定情况下默认使用的是-c-lzma-7-8m，那么可以认为在patch时最大的使用内存空间为(cacheSize+ 4*8)+O(1)吗？
4、其中 -c-zlib、-c-pzlib、-c-bzip2、pbzip2、lzma、lzma2等多种compressType有最佳使用场景吗？例如在意patch是内存使用大小、patch时间长短等情况下最佳实践。

**Comment by sisong** [comment]
* “1、-p不指定情况下是默认单线程执行吗？”     
默认是4，它现在只适用于支持并行的压缩算法；可以自己阅读diff的参数说明       
* “2、-c不指定情况下默认的压缩类型是什么呢？”    
默认不压缩补丁包    
* "3、..."   
如果使用了-c-lzma-7-8m，那patch时最大的使用内存空间确实为(cacheSize+ 4*8m)+O(1)； 实际中字典可能不会用完4*8m；    
* “4、...”
简单谈一点个人看法：zlib压缩的数据patch内存占用小，压缩率较低，解压快；bzip2内存占用中等，对文本压缩比较有效，解压缩慢； lzma2压缩率高，内存占用可以配置，解压缩略慢；      
具体如何选择，需要考虑自己的应用场景， 像在pc和智能手机上，使用本库在patch时内存占用应该都ok吧；  如果很在意patch内存占用和patch速度，需要你自己测试，本库还支持brotli、lzham、zstd压缩插件

**Comment by Picasso1990** [comment]
在不使用-c的情况下，直接使用原始命令
```
hdiffz old new diff
```
这时候如上述2问中的回答默认不压缩吗？那么这时候可否确定patch时的空间复杂度呢？由于这种情况下在diff过程中没有used one lzma dictSize输出，没有办法通过公式(cacheSize + 4*decompress stream size)+O(1)，不能确定其中的decompress stream size的大小

**Comment by sisong** [comment]
不压缩，当然patch时就不会有4\*decompress stream size这一块的占用

**Comment by Picasso1990** [comment]
1、那这样意思是在不使用-c压缩算法的情况下使用内存的情况是cacheSize+O(1)吗？
这空间复杂度太棒了

2、那不使用压缩算法情况下，是会相对diff会大一些是吗？

**Comment by sisong** [comment]
不压缩当然会大一些；   
看你在用apk文件做实验，应该不在意解压字典的内存占用才对啊；       
我帮人定制过一个patch版本，因为他的系统 (IoT设备)只有4KB内存，这样的环境，也用上了一个1KB左右的解压缩字典；

**Comment by Picasso1990** [comment]
是的，不是很在意解压字典的内存，只是想确认解压字典的内存是否能够控制或者是否在可接受范围内，一般在50M的内存花费范围内都是可接受的
