### ISSUE TITLE
这个patch可以移植到单片机上吗（diff在电脑上生成）？

### ISSUE THREAD

**Issue by tomyqg** [sisong/HDiffPatch#213]
内存32KB，没有文件系统，只提供flash读写接口，源文件（最大128KB）可以边读边打patch吗？

**Comment by sisong** [comment]
肯定可以做到，有朋友的IoT设备8位cpu+4kb内存+64kb都跑起来的（当然给他定制了一个压缩算法）

**Comment by tomyqg** [comment]
那在不压缩的前提下，可以调用那些接口实现我边读边patch的功能啊，大佬

**Comment by sisong** [comment]
“边读边patch”   
这个的意义不太清晰。    
你可以看看patch_single_compressed_diff的接口和说明

**Comment by tomyqg** [comment]
我的意思是说patch时不需要将整个源文件读出来后，再进行吧(因为ram空间有限)？
好的，我先看下这个接口，感谢大佬

**Comment by tomyqg** [comment]
大佬，请教下 patch_single_compressed_diff函数中这几个参数如何确定
diffData_pos       coverCount        stepMemSize

如下是我实现的接口

hpatch_BOOL hdiffz_patch_image(void)
{
		int ret = 0;
		
		hpatch_TStreamOutput out_stream = { 0 };
    hpatch_TStreamInput  old_stream = { 0 };
    hpatch_TStreamInput  diff_stream;

    old_stream.streamImport = NULL;
    old_stream.streamSize = iap_cfg.app_size;
    old_stream.read = hdiffz_read_old;

    out_stream.streamImport = NULL;
    out_stream.streamSize = iap_cfg.app_size;
    out_stream.write = hdiffz_write_new;

    diff_stream.streamImport = NULL;
    diff_stream.streamSize = iap_cfg.diff_size;
    diff_stream.read = hdiffz_read_diff;
		
		if(patch_single_stream_diff(&out_stream, &old_stream, &diff_stream, 0, 0, 4096, diiff_cache, diiff_cache+16*1024))
		{
				return hpatch_TRUE;
		}
		
		return hpatch_FALSE;
}

**Comment by sisong** [comment]
不熟悉的话，你需要使用的是patch_single_compressed_diff；它内部调用了compressed_stream_as_uncompressed() + patch_single_stream_diff() ；

**Comment by tomyqg** [comment]
好的，感谢大佬，年后再搞了，祝新年快乐 ！

**Comment by tomyqg** [comment]
大佬这个getSingleCompressedDiffInfo函数需要压缩的diff文件（kVersionType="HDIFFSF20"）吧，我的没有压缩（kVersionType="HDIFF13"），不能直接调用啊？

**Comment by sisong** [comment]
没有压缩也可以

**Comment by sisong** [comment]
没有压缩也可以

**Comment by sisong** [comment]
HDIFF13是以前的格式，需要使用patch_decompress_with_cache，不能使用patch_single_stream_diff；    
HDIFFSF20才是新定义的单数据流格式

**Comment by tomyqg** [comment]
那如何才能生成HDIFFSF20格式的diff文件啊，我目前是这样用的
hdiffz.exe c1.bin c2.bin c3.bin

**Comment by sisong** [comment]
hdiffz.exe c1.bin c2.bin c3.bin -SD-4k       (如果不支持-SD，那就自己用vc重新编译一个新的hdiffz.exe)

**Comment by sisong** [comment]
针对单片机场景，增加了一个demo： [HPatchLite](https://github.com/sisong/HPatchLite)，和[tinyuz](https://github.com/sisong/tinyuz)压缩算法一起 在4KB内存，8位CPU的设备上跑过。可以支持内存小于1KB的设备。
