### ISSUE TITLE
可以移植到iOS上吗？

### ISSUE THREAD

**Issue by HuangXiaowen1989** [sisong/HDiffPatch#214]
准备用在移动端的热更新上，看到有Android jni的版本，但是没有iOS的版本。

**Comment by sisong** [comment]
iOS上直接引用源代码就好了，如果用的其他语言，那需要你自己包装一下api；      

这个库不负责”热“更新，它只是提供了一个diff&patch算法，具体怎么利用是你的工作。

**Comment by jiezuowhu** [comment]
同求IOS版本

**Comment by sisong** [comment]
我有点搞不清楚状况，请你们定义一什么是iOS版？    
iOS是可以直接使用C/C++代码的，那么在手机上使用patch端代码完全没有问题。 本源码库只是算法库，没有热更新的概念。

**Comment by jiezuowhu** [comment]
具体哪些c++文件需要包含进去呢，如果能提供一个想安卓版这样，可以直接调用版本就最好了（ps：用的其实是Unity）

**Comment by sisong** [comment]
核心只需要`HDiffPatch\libHDiffPatch\HPatch\patch.c`中的patch_decompress_with_cache函数；（当然还有其引用到的头文件patch_types.h、patch_private.h、patch_types.h）      
patch_decompress_with_cache处理的参数是流，如果嫌调用麻烦，可以调用`HDiffPatch\builds\android_ndk_jni_mk\hpatch.c`文件中的hpatchz函数，这个函数处理的参数是文件，就和android中调用的是同一个函数了。

**Comment by yingnierxiao** [comment]
没问题的  unity里面我也用过了

**Comment by jiezuowhu** [comment]
> 核心只需要`HDiffPatch\libHDiffPatch\HPatch\patch.c`中的patch_decompress_with_cache函数；（当然还有其引用到的头文件patch_types.h、patch_private.h、patch_types.h）
> patch_decompress_with_cache处理的参数是流，如果嫌调用麻烦，可以调用`HDiffPatch\builds\android_ndk_jni_mk\hpatch.c`文件中的hpatchz函数，这个函数处理的参数是文件，就和android中调用的是同一个函数了。

如果还需要用到lzma压缩呢，看lzma的压缩效果还是挺明显的

**Comment by jiezuowhu** [comment]
> 没问题的 unity里面我也用过了 正常编辑就行 相关引用加上

有木有例子可以参考下~

**Comment by jiezuowhu** [comment]
> 核心只需要`HDiffPatch\libHDiffPatch\HPatch\patch.c`中的patch_decompress_with_cache函数；（当然还有其引用到的头文件patch_types.h、patch_private.h、patch_types.h）
> patch_decompress_with_cache处理的参数是流，如果嫌调用麻烦，可以调用`HDiffPatch\builds\android_ndk_jni_mk\hpatch.c`文件中的hpatchz函数，这个函数处理的参数是文件，就和android中调用的是同一个函数了。

或者可以提供一个IOS对应的.a文件么，自己看了一波，还是挺多文件的，怕有问题

**Comment by sisong** [comment]
`挺多文件的，怕有问题`  手边没有macos，对于C\C++代码，编译链接没有报错就没有问题了
