### ISSUE TITLE
关于IOS的.a库

### ISSUE THREAD

**Issue by jiezuowhu** [sisong/HDiffPatch#220]
这边自己根据提供的build里面的XCode，模仿生成了一套IOS用的.a库，但是测试后发现没法patch使用了lzma压过生成的diff文件，请问是需要打开什么宏定义么？

**Comment by sisong** [comment]
默认是带了zlib，bzip2，lzma和lzma2的解码器的。  你调用的是哪个patch函数？

**Comment by jiezuowhu** [comment]
> 默认是带了zlib，bzip2，lzma和lzma2的解码器的。 你调用的是哪个patch函数？

直接用的安卓android_ndk_jni_mk里面的hpatch.c跟hpatch.h文件，哦是这个里面要开启宏么？

**Comment by jiezuowhu** [comment]
> hpatch.c的代码里关闭了默认的插件，然后在Android.mk里定义了_CompressPlugin_zlib、_CompressPlugin_lzma、_CompressPlugin_lzma2 这3个宏；
> 所以你可以在xcode的.a项目属性中添加这几个宏定义

我把hpatch.c里面改成了#define _IS_NEED_DEFAULT_CompressPlugin 1，然后又报错HPATCH_PATCH_ERROR了

**Comment by jiezuowhu** [comment]
> hpatch.c的代码里关闭了默认的插件，然后在Android.mk里定义了_CompressPlugin_zlib、_CompressPlugin_lzma、_CompressPlugin_lzma2 这3个宏；
> 所以你可以在xcode的.a项目属性中添加这几个宏定义

测试过非压缩的情况下是好的，用压缩的情况，就不可以了（同样情况下PC跟安卓都是可以的）

**Comment by sisong** [comment]
HPATCH_PATCH_ERROR 这种错误很难知道具体原因，只能怀疑数据有误。 另外可以用Xcode跟踪一下报错的位置，利用_hpatch_false宏来打开调试

**Comment by jiezuowhu** [comment]
> HPATCH_PATCH_ERROR 这种错误很难知道具体原因，只能怀疑数据有误。 另外可以用Xcode跟踪一下报错的位置，利用_hpatch_FALSE宏来打开调试

本来想用XCode来调试试下来着，又发现了一个很奇怪的现象，如果是直接用生成号的.a文件，会报HPATCH_PATCH_ERROR ，但是如果直接引用生成.a库的工程，就没问题，有大佬知道原因么

**Comment by sisong** [comment]
是有点奇怪了，没有遇到过。 猜测是链接出了问题？

**Comment by jiezuowhu** [comment]
> 是有点奇怪了，没有遇到过。 猜测是链接出了问题？

最后还是源码了，就可以了

**Comment by jiezuowhu** [comment]
后面又研究了一下，大概找到原因了，是因为跟Unity本身的lzma代码冲突了
