### ISSUE TITLE
Specific error code for patch failing due to insufficient disk space

### ISSUE THREAD

**Issue by Zeblote** [sisong/HDiffPatch#221]
Hi, we're getting surprisingly many support requests from people seeing their patch fail because they somehow have less than 1GB free disk space. Unfortunately the library returns a generic DIRPATCH_PATCH_ERROR rather than something more specific that would allow displaying a message to the user why it failed and how they can easily fix it themselves.

So I'm proposing adding something like DIRPATCH_DISK_FULL for this case.

**Comment by Zeblote** [comment]
```
[0x6d5c|00:00:04.072] Patch progress: 12 %
[0x6d5c|00:00:04.079] Patch progress: 13 %
[0x6d5c|00:00:04.085] [hpatch] check _file_append_part(self,writeToPos,data,data+writeLen) error!
[0x6d5c|00:00:04.087] [hpatch] check patch_decompress_with_cache(out_newData,oldData,&hdiffData.base, self->_decompressPlugin,temp_cache,temp_cache_end) error!
[0x6d5c|00:00:04.087] [hpatch] dir patch run ERROR!
[0x6d5c|00:00:04.087] [hpatch] check !self->_curNewFile->fileError error!
[0x6d5c|00:00:04.087] [hpatch] newPath close ERROR!
[0x6d5c|00:00:04.174] [hpatch] 
[0x6d5c|00:00:04.174] [hpatch] hpatchz dir patch time: 1.078 s
[0x6d5c|00:00:04.174] Patch failed to apply.
[0x6d5c|00:00:04.174] Reason: DIRPATCH_PATCH_ERROR
```

Snippet from one of the user logs. You can see hpatchz output. Maybe that reveals a good place where detection for this case can be added.

**Comment by sisong** [comment]
call _file_append_part()  return a false  --> call self->_curNewFile->write() return a false     
Here, we know that fwrite() return a false, but code unknow this: not sure about _curNewFile is a file stream.      
Here, we know 'fwrite() return a false' is very high **probability** because the disk is full, but it may also be caused by other errors in the file system.

**Comment by Zeblote** [comment]
Is there some way to query the OS _why_ it failed?

**Comment by sisong** [comment]
call ferror() ?    I did not find the meaning of the return value.      
change file API to OS file API, such as: windows API  CreateFile\WriteFile\... then call GetLastError()  get why it failed (error code 39 is mean disk full)

**Comment by sisong** [comment]
v4.2.3 test dir patch, when disk full print log:
```
hpatch_TFileStream ERROR! errno: 28, errmsg: No space left on device.
dir_patch check self->_listener->closeNewFile(self->_listener,self->_curNewFile) error!
check _file_append_end(self) error!
dir_patch TDirPatcher_patch() patch_decompress_with_cache error!
dir patch run ERROR!
```

**Comment by Zeblote** [comment]
Nice! Would it be possible to pass that error all the way up so the programming calling dir patch receives i.e. DIRPATCH_DISK_FULL? That way we can show the correct message to the user and prompt him to make some space without having to dig through the logs.

**Comment by sisong** [comment]
`> pass that error all the way up`     
now, not pass.     
next, I want to convert some frequently occurring errno to return value(define some new Patch Error Code).
