### ISSUE TITLE
想请教一下大佬，在单元测试的时候为什么要把部分olddata copy入new data呀

### ISSUE THREAD

**Issue by mynameisenthusiasm** [sisong/HDiffPatch#235]
在看unit test的时候不是很懂这部分代码
![image](https://user-images.githubusercontent.com/54618402/127805301-76bb6d60-2fde-436c-ac7e-62e843aed988.png)
🙏

**Comment by sisong** [comment]
这是在生成测试数据，拷贝的目的是，让new和old数据有一些相同的数据。

**Comment by mynameisenthusiasm** [comment]
是的是的，谢谢大牛回复！后来逐渐理解了～主要还是因为这个覆盖线算法是基于有一些相同的假设操作的😃
