### ISSUE TITLE
请问single compressed和非single有什么区别呢

### ISSUE THREAD

**Issue by mynameisenthusiasm** [sisong/HDiffPatch#237]
我阅读了您的一些merge历史，发现single compressed diff似乎是compressed diff的优化？不知道这种理解对吗 可以请您提供详细一些的信息吗

**Comment by sisong** [comment]
readme和函数注释上有解释，推荐新的single compressed diff是为了支持patch时的边下载边patch特性并且减少patch时的解压缩流数量，生成的补丁包可能比compressed diff生成的略大。

**Comment by mynameisenthusiasm** [comment]
原来如此，那看来如果有边下载边patch的需求用single compressed diff比较合适了，但是如果进入应用之前更新不用会比较合适🤔这样理解对吗

**Comment by sisong** [comment]
是的
