### ISSUE TITLE
./hpatchz 如何使用呢？

### ISSUE THREAD

**Issue by zhu-clam** [sisong/HDiffPatch#238]
例如我想要在块设备分区，使用HDIFF/HPATCH 工具进行差分升级。
步骤1. 使用./hdiffz old_system.img new_system.img inc_system.img 
生成增量的system镜像文件
步骤2. 将inc_system 镜像文件刷写到块设备中;按照用例。
patch usage: hpatchz [options] oldPath diffFile outNewPath；执行如下命令
./hpatchz /dev/mmcblk0p30 ./inc_system.img  /dev/mmcblk0p29
其中 /dev/mmcblk0p30 是我old_system.img 对应的块设备；
/dev/mmcblk0p29 是我想要去刷写的块设备。
但提示
get outNewPath type ERROR!

**Comment by zhu-clam** [comment]
补充一下：
使用bspatch 工具，可以直接使用 bsdiff 生成的差分包进行块设备升级。如下
$patch_tool ${device_node_origin} ${device_node} ${file}
bspatch  /dev/mmcblk0p30  /dev/mmcblk0p29  inc_system.img
上面，/dev/mmcblk0p30 是对应old_system.img 的块设备，inc_system.img 是由bsdiff 生成的增量文件。
/dev/mmcblk0p29 是输出到的块设备

**Comment by sisong** [comment]
看起来是调用C文件api函数stat("/dev/mmcblk0p29",&s)时返回了错误的状态码。        
调用这个函数的目的是避免覆盖已有文件，可以试试添加-f参数试试跳过该检查。

**Comment by sisong** [comment]
另外： ./hdiffz  支持压缩的补丁包，比如选项-c-lzma2

**Comment by zhu-clam** [comment]
@sisong 加上-f 参数可行。
感谢楼主百忙中的回复

**Comment by zhu-clam** [comment]
又遇到新的一个issue。
root@j5dvb-hynix1G:~# ./hpatchz /dev/mmcblk0p24 ./inc_vbmeta.img /dev/mmcblk0p23 -f
old : "/dev/mmcblk0p24"
diff: "./inc_vbmeta.img"
out : "/dev/mmcblk0p23"
oldFile dataSize 131072 != diffFile saved oldDataSize 1920 ERROR!

hpatchz time: 0.000 s
./hpatchz 程序不能像bspatch 一样，能够识别出需要patch 的文件大小。或者有什么参数，指定只比较 比如这里 ，只比较前 1920 bytes？

**Comment by sisong** [comment]
这个检查默认情况下肯定需要保留的；     
你把`if (poldData->streamSize!=diffInfo.oldDataSize)`这里的检查逻辑去掉，然后`$make`出一个新的hpatchz

**Comment by zhu-clam** [comment]
好的，多谢楼主！

**Comment by zhu-clam** [comment]
下午好~
   我在使用 hdiffz 给镜像文件大小 为1GB 的做差分时，偶尔正常，会提示：
zxf@zxf-virtual-machine:~/samba/share/j5-upload/build/ota_tools$ diff_tools/hdiffz /tmp/tmp.pUVXP2zLTv/system/system.img /tmp/tmp.iK5nZjNfDk/system/system.img ./inc_system.img
old : "/tmp/tmp.pUVXP2zLTv/system/system.img"
new : "/tmp/tmp.iK5nZjNfDk/system/system.img"
out : "./inc_system.img"
hdiffz run with compress plugin: ""
oldDataSize : 1073741824
newDataSize : 1073741824
diff run an error: std::bad_alloc ERROR!

all   time: 7.401 s
然后我有浏览 issue 集，使用了参数 -s-1k 之后，slove this problem。但是产生的差分文件，是 -s-64[default] 的 10倍以上。
请问是 -s-  参数会影响 生成的差分包的size 吗？ 另外我的英文比较差，参数说明很多不理解意思。有中文的吗？

**Comment by sisong** [comment]
这是机器内存不够。    
用谷歌翻译吧。   
diff时默认是-m模式，该参数内存需求较大，速度慢，但补丁包较小；而-s模式内存占用小速度快，但可能补丁包略大（1k的参数太大，可以改小来得到更小的补丁）。  要对比补丁包的大小，需要添加压缩参数 否则没有意义。

**Comment by zhu-clam** [comment]
再次感谢 @sisong

**Comment by zhu-clam** [comment]
> 又遇到新的一个issue。
> root@j5dvb-hynix1G:~# ./hpatchz /dev/mmcblk0p24 ./inc_vbmeta.img /dev/mmcblk0p23 -f
> old : "/dev/mmcblk0p24"
> diff: "./inc_vbmeta.img"
> out : "/dev/mmcblk0p23"
> oldFile dataSize 131072 != diffFile saved oldDataSize 1920 ERROR!
> 
> hpatchz time: 0.000 s
> ./hpatchz 程序不能像bspatch 一样，能够识别出需要patch 的文件大小。或者有什么参数，指定只比较 比如这里 ，只比较前 1920 bytes？

此问题修改一处代码slove。
         if (poldData->streamSize!=diffInfo.oldDataSize){
             fprintf(stderr,"oldFile dataSize %" PRIu64 " != diffFile saved oldDataSize %" PRIu64 " ERROR!\n",
                     poldData->streamSize,diffInfo.oldDataSize);
-            check_on_error(HPATCH_FILEDATA_ERROR);
+                       poldData->streamSize=diffInfo.oldDataSize;
+            //check_on_error(HPATCH_FILEDATA_ERROR);
         }
希望有帮助到后面的人。
