### ISSUE TITLE
请问为什么非dir不支持checksum检查呀

### ISSUE THREAD

**Issue by mynameisenthusiasm** [sisong/HDiffPatch#239]
很奇怪，不是应该先支持非dir然后再支持dir吗，因为dir是由非dir组成的（？）或者说请问您觉得没有必要吗

**Comment by sisong** [comment]
2个文件之间diff时，可以添加“-D”参数来开启检验。         
 由来： 刚开始时库只支持2个文件之间的diff，这时校验需求交给了外部自己解决，（如果实在需要校验数据在补丁文件中，也可以自己添加在补丁文件前面或后面）。  而自己处理也更自由，比如下载补丁前就检查old数据，然后边下载补丁，边校验下载到的数据，这样的策略实现更好。（刚开始库实现了校验逻辑，后来在实现完整方案后，完全删除了这些逻辑，保持库的简单）         
后来：需要支持2个目录之间的diff，而这时文件数量可能很大（我们自己的上万以上），这时交给外部管理数据校验就比较困难了（外部实现即复杂又不高效不安全），所以库就提供了默认的内部校验实现。

**Comment by mynameisenthusiasm** [comment]
原来如此，感谢大佬的细致回复，但是如果添加-D的话，会不会慢很多啊，因为可能有些专属目录的操作？

**Comment by sisong** [comment]
速度差不多吧，你自己试试     
默认会进行一些校验，可以选择校验哪些。

**Comment by mynameisenthusiasm** [comment]
嗯嗯 应该overhead不太大，我测试一下然后选择吧，谢谢

**Comment by sisong** [comment]
需要注意：我编译的安卓上的.so库没有包含dir的支持（也就没有包含校验的支持），如果需要此支持，需要调整少量代码和宏
