### ISSUE TITLE
在头文件中实现的原因

### ISSUE THREAD

**Issue by mynameisenthusiasm** [sisong/HDiffPatch#240]
![image](https://user-images.githubusercontent.com/54618402/128798257-801b8ad4-6d49-48ab-8284-11862299c2d2.png)
是这样，我本来想手动添加checksum（因为单file不支持），发现大佬在头文件中也实现了？一般cpp应该遵循“在头文件定义，cpp文件实现”，请问这里为什么不符合呢？🤔

**Comment by sisong** [comment]
1. 这类代码可以看做是核心库以外的功能，不是必须的，而且其实现可以看作参考的“demo”实现
2. 这些代码实际上是一些“胶水”代码，并没有真正的“实现”，而是一般转调用了其他的第三方库的代码实现

**Comment by mynameisenthusiasm** [comment]
原来如此，谢谢大佬，学到很多～

**Comment by mynameisenthusiasm** [comment]
【自己要养成close的习惯
