### ISSUE TITLE
使用self-reference structure的原因

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#241]
有两个地方我发现您使用了self-reference structure（可能这个名词使用的不准确，不过这里主要是想表达一个structure里面用到了自己）
第一处是在inputstream
因为不从文件输入，因此我需要让我的char*符合您的stream，但是不是很懂为什么我看您在定义file stream的时候，
![image](https://user-images.githubusercontent.com/54618402/128799236-125bc26c-8cd7-494b-bf02-dac359ea07dd.png)
里面的第一个元素指向了自己，base是hpatch_TStreamInput类型，which拥有一个void pointer（streamImport），绕了一圈这个import最后通过一个void pointer指向自己了🤣，我理解这个应该是指向一片空间适合的内存空间，比如像mem里面做的
![image](https://user-images.githubusercontent.com/54618402/128799610-95b966cc-73ca-4e7e-bcd5-96e383e419af.png)
但是hpatch_TFileStreamInput显然不是一片内存空间，最后指向自己更是让我不能理解，请问为什么要设计这种结构呢

第二个使用self reference structure的地方是在hpatch checksum，是在checksum_plugin.h里面，这个结构体的某个函数要求传入一个自己类型的指针，但是我到了demo里面发现，这个自己类型的指针似乎并没有什么用。。。
![image](https://user-images.githubusercontent.com/54618402/128799901-e7b38fb8-b6ee-43ca-8d0d-333a0b016d71.png)
![image](https://user-images.githubusercontent.com/54618402/128800171-c23e7bd7-6f97-4d4d-be4a-d8e04f964fb7.png)
我能理解的是，因为这里用了函数指针，其实是想实现多态，那么open和close到底“how”其实在赋值的时候已经确定了，为什么还要传入自身呢 so confused

**Comment by sisong** [comment]
嗯，有几个结构有类似的成员字段。     
比如streamImport，它的目的是交给接口的实现者存储自己想要储存的数据，比如句柄、序号、内存、资源等等（要存储什么才能实现该接口，是接口的实现者决定的）     
“hpatch checksum，... 这个自己类型的指针似乎并没有什么用”      
我的实现是不需要，但我无法排除别人的实现用不上，比如：某个hash算法很特殊，或者就是需要共享一些公共的资源，统一的内存管理等等，那这个参数就能用的上了

**Comment by mynameisenthusiasm** [comment]
原来如此，谢谢大佬，我再思考一下怎么使用
