### ISSUE TITLE
请问create_single_compressed_diff_stream这个stream是指的创建时候的stream size还是patch时候的stream size

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#243]
![image](https://user-images.githubusercontent.com/54618402/129036685-0eb2ceaa-e4da-4378-8a9f-3d3f799da88b.png)

换句话说 如果我们用create_compressed_diff去生成diff 是否可以在patch的时候设置stream size？
（或者，diff时的stream size是否与patch相对应）

**Comment by sisong** [comment]
这个diff函数的意思：使用流的方式来创建一个单压缩数据流   （old和new文件都不用要求全部加载到内存了）     
流模式的diff可用于节省diff时的内存和加快补丁创建速度（代价是补丁可能会大一些）

**Comment by sisong** [comment]
这个diff函数的意思：使用流的方式来创建一个单压缩数据流   （old和new文件都不用要求全部加载到内存了）     
流模式的diff可用于节省diff时的内存和加快补丁创建速度

**Comment by sisong** [comment]
没有相关性

**Comment by sfsfsf183** [comment]
get
