### ISSUE TITLE
关于checksum

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#244]
请问现在支持的checksum是做完diff的checksum吗？这样和check_diff的功能是不是一样的啊？

**Comment by mynameisenthusiasm** [comment]
![image](https://user-images.githubusercontent.com/54618402/129063080-3e9f705c-1f6e-48e9-912d-ff8e49db20d2.png)
shuo cuo l
说错了，应该是这个函数，有对应的checksum吗？

**Comment by sisong** [comment]
check_diff和check_diff_stream功能一样， 只是用于在diff后检查生成的补丁包是否正确。

**Comment by sfsfsf183** [comment]
请问patch会有默认校验支持吗

**Comment by sisong** [comment]
hpatchz支持-D模式（目录间补丁）的补丁的校验功能，而且默认会开启部分检查（用-C-no关闭），请阅读命令行说明

**Comment by sfsfsf183** [comment]
嗯嗯好的，其实命令行说明看了，但是就是有印象好像之前说没有
然后刚刚又找了一下，发现是因为这个
“我编译的安卓上的.so库没有包含dir的支持（也就没有包含校验的支持），如果需要此支持，需要调整少量代码和宏”
那我去调整一下看看～谢谢
