### ISSUE TITLE
请问为什么create_single_compressed_diff_stream的参数反而少呢

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#245]
![image](https://user-images.githubusercontent.com/54618402/129131900-9e3fd4ad-45b9-4cfe-b033-0aafe671d9ff.png)
按照我的理解，create_single_compressed_diff_stream应该是create_single_compressed_diff的父集（增加了kmatchblocksize）这一选项，请问create_single_compressed_diff其他的参数要怎么理解呢，是为了优化吗？如果想用这一层的接口（直接传char*），需要怎么修改和操作呢

**Comment by mynameisenthusiasm** [comment]
我发现create_single_compressed_diff）stream控制 matchBlockSize
create_single_compressed_diff 控制matchScore

**Comment by sisong** [comment]
这两个diff函数生成的补丁一样，但两个是**完全不同的算法思路**，所以参数也有不同。    
create_single_compressed_diff占用较多内存，速度慢，但生成的补丁包可能小一些；而create_single_compressed_diff_stream尽量减少内存占用，速度快。

**Comment by mynameisenthusiasm** [comment]
这个“占用较多内存”，指的是diff的内存还是patch的内存？为什么测试stream的时候非stream速度更快呢，晕

**Comment by mynameisenthusiasm** [comment]
或者说diff和patch有哪些一定要对应的参数呢，按照我的理解，single是一定要对应的，然后压缩解压缩方法一定要对应，其他还有什么吗？

**Comment by sisong** [comment]
“这个“占用较多内存”，指的是diff的内存还是patch的内存？”  指diff， 请注意每个函数前面的注释说明     
“为什么测试stream的时候非stream速度更快呢，晕”  diff的时候stream模式快，patch的时候stream模式慢   
“single是一定要对应的，然后压缩解压缩方法一定要对应”  是的；可以看看patch函数对补丁包的要求

**Comment by mynameisenthusiasm** [comment]
”patch的时候stream模式慢“请问这一句，stream模式指的是patch时用stream模式吗？我看patch好像接口全是stream的
![image](https://user-images.githubusercontent.com/54618402/129181006-70402479-8973-480e-aa72-ed555d512424.png)
为啥既可以mem也可以stream🤣diff里不是mem和stream是冲突的吗（diff里有hdiffmem和hdiffstream）

**Comment by mynameisenthusiasm** [comment]
感谢回复！
”patch的时候stream模式慢“请问这一句，stream模式指的是patch时用stream模式吗？请问要对应哪个参数呢（或者说对应哪个v4接口呢🤔

**Comment by mynameisenthusiasm** [comment]
感谢回复！
”patch的时候stream模式慢“请问这一句，stream模式指的是patch时用stream模式吗？
如果要在patch中实现相似的功能，请问要对应哪个参数呢（或者说对应哪个v4接口呢🤔

**Comment by mynameisenthusiasm** [comment]
原来如此，请问大佬可以简单介绍一下v4接口中patch_single_stream_diff()和patch_single_stream()的区别吗，这个diff后缀有点疑惑不知道有什么用

**Comment by mynameisenthusiasm** [comment]
还有一个问题，

> patch_single_stream

diff应该是with diff info 但是with 不 with 有啥区别呢

**Comment by sisong** [comment]
注意看函数前面的注释，一般都有说明，比如说明里有：    
```
singleCompressedDiff()==getSingleCompressedDiffInfo() + listener->onDiffInfo() + patch_single_compressed_diff()
patch_single_compressed_diff()==compressed_stream_as_uncompressed() + patch_single_stream_diff()

```

**Comment by sfsfsf183** [comment]
> 注意看函数前面的注释，一般都有说明，比如说明里有：
> 
> ```
> singleCompressedDiff()==getSingleCompressedDiffInfo() + listener->onDiffInfo() + patch_single_compressed_diff()
> patch_single_compressed_diff()==compressed_stream_as_uncompressed() + patch_single_stream_diff()
> ```

嗯嗯，注释其实也都看了，就是想问下对比，有两个patch_single_stream一个有diff后缀一个没有
sorry昨天编辑的时候好像失误少发了🙈 ）其实问题是想问patch_single_stream_diff中的diff后缀的含义

然后自己推测的是diff应该是with diff info 但是with 不 with 有啥区别呢

所以其实还是不太清楚这个diff后缀？🤔

**Comment by sisong** [comment]
命名只能尽量了:(   
patch_single_stream可以看作是一个封装好的最外层的单一函数，用这个函数来满足绝大部分情况的需求；
patch_single_stream_diff是最内层的一个核心函数实现(没有patch_single_stream前的最早的功能实现)；可能patch_single_stream_kernel更贴切？

**Comment by sfsfsf183** [comment]
好的，命名确实不是容易的事情
