### ISSUE TITLE
关于设计合适的stream

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#246]
![image](https://user-images.githubusercontent.com/54618402/129150683-d94e24d3-144b-41ae-a04e-1c24c7581f92.png)
我发现这些是继承于stream，但是filestreaminput却是拥有stream请问为什么要这样设计？🤔（因为感觉filestraminput 确实is a stream，和下面这些没有什么区别吧 
如果我想使用您的createsinglecompressedstream是直接传入char*比较好还是包装一下传入比较好

**Comment by mynameisenthusiasm** [comment]
（又多懂得了一点，似乎是open和read的区别

**Comment by sisong** [comment]
“filestreaminput却是拥有stream请问为什么要这样设计？”    因为C语言不支持继承的语法；    
“createsinglecompressedstream是直接传入char*比较好还是包装一下传入比较好”   create_single_compressed_diff_stream是为了支持超大文件或者资源有限的设备上创建补丁； 如果old和new用文件流加载后当作参数传入该函数，那这样内存占用就会很小，用到哪里的数据，才会相应的加载少量文件数据到内存。

**Comment by sfsfsf183** [comment]
“用文件流加载后当作参数传入该函数” 这个用文件流加载后可以理解为用TFileStreamInputs包装吗？请问具体有函数可以实现吗

**Comment by sisong** [comment]
TFileStreamInput的作用就是将已经存在的文件，包装成一个满足要求的输入流。     
同理一个目录也可以用一定的方式包装成流数据，所以库就能支持目录之间的diff&patch了；      
同样也可以将apk（zip）文件用一定的方式抽象成未压缩的数据流 ...

**Comment by sfsfsf183** [comment]
”同样也可以将apk（zip）文件用一定的方式抽象成未压缩的数据流 ...“
这个抽象成未压缩的和解压缩有什么区别呀

**Comment by sfsfsf183** [comment]
请问
”同样也可以将apk（zip）文件用一定的方式抽象成未压缩的数据流 ...“
您描述中的”抽象成未压缩“的和“解压缩”有什么区别呀

**Comment by sisong** [comment]
”抽象成未压缩“==“解压缩”+"压缩还原需要的元数据"

**Comment by sfsfsf183** [comment]
谢谢🙏

**Comment by sfsfsf183** [comment]
> ”抽象成未压缩“==“解压缩”+"压缩还原所需要的元数据"

对了 请问那个compressed_stream_as_uncompressed 也中的as也是这个含义吗？

**Comment by sisong** [comment]
翻译成 当作

**Comment by sfsfsf183** [comment]
请问这个命名中的T是什么意思呀？一般不实例化？（感觉像是template但是也没啥道理

**Comment by sfsfsf183** [comment]
比如
![image](https://user-images.githubusercontent.com/54618402/130192284-1a9e3030-c6f3-40f1-9a5a-e916054a5fdd.png)
🤔

**Comment by sfsfsf183** [comment]
而且有些地方加了hpatch的前缀，有些又没有，难道hpatch前缀只是给hpatch用的吗，diff里也用了好多呀
![image](https://user-images.githubusercontent.com/54618402/130192396-1e63eb62-369f-49f0-8357-959023018259.png)

**Comment by sisong** [comment]
“T” 指类型type    
“hpatch前缀”  为了容易移植，patch部分的代码都由C语言编写的，而 C的名称容易造成编译冲突或链接失败； 加上前缀后，重名的几率将大大降低；         
diff部分默认需要依赖和使用patch部分的代码（反过来就不太好了）

**Comment by sfsfsf183** [comment]
如果想支持一种新的数据流，要如何修改代码呢？

**Comment by sfsfsf183** [comment]
> “T” 指类型type的缩写，个人习惯
> “hpatch前缀” 为了容易移植，patch部分的代码都由C语言编写的，而 C的名称容易造成编译冲突或链接失败； 加上前缀后，重名的几率将大大降低；
> diff部分用的C++实现，默认需要依赖和使用patch部分的代码作为基础（反过来就不太好了），所以就直接用了

谢谢～

**Comment by sfsfsf183** [comment]
这个CFileStreamInput似乎都是在cppfile里用呀🙈为什么要交CFile呢

**Comment by sisong** [comment]
“如果想支持一种新的数据流，要如何修改代码呢？”   如果是“实现”一种新的数据流，那借鉴已有的那些实现就好（比如hpatch_TFileStreamInput、CFileStreamInput、mem_as_hStreamInput）；如果是“支持”一种新的数据流，那我也不知道你的具体需求。      
CFileStreamInput中的C，是Class的缩写，它是对C语言实现的hpatch_TFileStreamInput包装一下给CPP代码用，帮助自动管理资源。

**Comment by sfsfsf183** [comment]
> “如果想支持一种新的数据流，要如何修改代码呢？” 如果是“实现”一种新的数据流，那借鉴已有的那些实现就好（比如hpatch_TFileStreamInput、CFileStreamInput、mem_as_hStreamInput）；如果是“支持”一种新的数据流，那我也不知道你的具体需求。
> CFileStreamInput中的C，是Class的缩写，它是对C语言实现的hpatch_TFileStreamInput包装一下给CPP代码用，帮助自动管理资源。

谢谢回复，可不可以顺便问一下您定义的f_pos, f_offset （in out都有但是out没用）以及out_length要怎么理解呢
目前理解f_offse似乎就是全局offset（每次读写都会生效）
 f_pos设置不设置好像没什么影响？ out_length要手动赋值为streamsize🤔

**Comment by sisong** [comment]
m_fpos是当前读写位置；     
m_offset是给这个流一个相对偏移位置，用来处理一些特殊情况，比如这个流只是一个文件的其中一部分的情况；     
out_length是写入数据的最后位置（m_fpos和streamSize都无法代表这个语义），“out_length要手动赋值为streamsize”是将流的大小设置为实际拥有的数据大小；

**Comment by sfsfsf183** [comment]
> > “如果想支持一种新的数据流，要如何修改代码呢？” 如果是“实现”一种新的数据流，那借鉴已有的那些实现就好（比如hpatch_TFileStreamInput、CFileStreamInput、mem_as_hStreamInput）；如果是“支持”一种新的数据流，那我也不知道你的具体需求。
> > CFileStreamInput中的C，是Class的缩写，它是对C语言实现的hpatch_TFileStreamInput包装一下给CPP代码用，帮助自动管理资源。
> 
> 谢谢回复，可不可以顺便问一下您定义的f_pos, f_offset （in out都有但是out没用）以及out_length要怎么理解呢
> 目前理解f_offse似乎就是全局offset（每次读写都会生效）
> f_pos设置不设置好像没什么影响？ out_length要手动赋值为streamsize🤔

这个outputstream中的offset和input的含义有差别吗，为什么一个生效一个不生效呀🙉🙈

**Comment by sfsfsf183** [comment]
呜呜谢谢大佬回复，其实名字上也确实写的能猜出来，但是还是有点疑问，关于这几个成员的设计

”m_fpos是当前读写位置；“

我发现有一个函数_TFileStreamInput_read_file需要输入read的position，而且似乎没有提供不需要输入position的重载，既然这样那这个位置记录会不会有点多余？
（每次只要根据输入的position seek过去就可以了，不是很明白记录当前读写位置的意义，我唯一发现的用处就是如果read/write和当前position相同就可以减少一次seek操作？


by the way
~(hpatch_StreamPos_t)0
这是一种什么操作呀。。。🤔经常发现这种写法

**Comment by sisong** [comment]
“这个outputstream中的offset和input的含义有差别吗，为什么一个生效一个不生效呀”    语义一样，但我的应用中还没有遇到有需要用到它的地方，就没有去实际实现这个功能（也不对外）。        
“当前position相同就可以减少一次seek操作？”   确实是这个目的；      
“~(hpatch_StreamPos_t)0”     置成全1而已，即该无类型整数的最大值

**Comment by sfsfsf183** [comment]
> “这个outputstream中的offset和input的含义有差别吗，为什么一个生效一个不生效呀” 语义一样，但我的应用中还没有遇到有需要用到它的地方，就没有去实际实现这个功能（也不对外）。
> “当前position相同就可以减少一次seek操作？” 确实是这个目的；
> “~(hpatch_StreamPos_t)0” 置成全1而已，即该无类型整数的最大值

🙏谢谢
