### ISSUE TITLE
关于listener的使用

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#247]
想用您的v4API，发现patch里面都是用listener携带参数的，自己理解了一下，不知可否请您看下是否有误

我现在已经理解的是：listner里面有一个空指针import，两个函数指针onDiffInfo, onPatchFinish，并看了一些使用case，这个listener在check和patch的时候使用，
可不可以理解import是plugin（包括checksum和decompress/compress两部分），用啥加啥
之后两个都是固定的
ondiffinfo是_check_single_onDiffInfo
onpatchfinish是_check_single_onPatchFinish

**Comment by sisong** [comment]
ondiffinfo是打开补丁数据后，知道了一些补丁信息，告知listener，并从listener得到一些设置数据继续执行；     
onpatchfinish用于通知listener，patch结束，可用于释放资源。     
这里没有checksum的逻辑；  check_single_compressed_diff的实现是为了检查创建的补丁包是否正确，避免发布错误的补丁包。

**Comment by sfsfsf183** [comment]
谢谢回复～

**Comment by sfsfsf183** [comment]
对了，请问这是运用了某种设计模式吗？

**Comment by sisong** [comment]
接口回调     
没什么特殊吧
