### ISSUE TITLE
hdiffz's name

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#248]
hdiffz
有时候理解名字会帮我们更好的理解算法
h是什么意思
z是什么意思
谢谢！

**Comment by sisong** [comment]
h是比较随意的字母，和diff拼在一起，已和其他diff算法名称区分；    
加z是因为v1API的时候编译出的命令行文件名称用了hdiff、hpatch； 而实现v2API后彻底重写了命令行功能，为了避免同名而生成的补丁格式不同造成兼容错误，所以另外起了新的名称，用z来代表有压缩功能。

**Comment by sfsfsf183** [comment]
好的～get谢谢～
