### ISSUE TITLE
对于single compressed stream的理解

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#249]
我记得很早之前看到某个帖子说，single compressed stream就是一路compressed stream ，不然是四路，请问这个路要怎么理解（找了很久也没找到原来那句话😭 就提了个问题

**Comment by sisong** [comment]
以前的补丁数据存储时，为了压缩率好一点，相类似的数据放在一起单独压缩，从而最多有4路压缩流；     
而新的格式使用了新的数据存储方式，patch时同时用到的多种数据一起存储，整体数据按使用的时间先后依次存储，所以只有单路压缩数据流；

**Comment by sfsfsf183** [comment]
好嘞 get～
