### ISSUE TITLE
代码格式

### ISSUE THREAD

**Issue by JayXon** [sisong/HDiffPatch#25]
我注意到代码格式比较混乱，比如很多地方行尾有多余空格、有的逗号后面没有空格等等。
可以考虑使用clang-format来自动格式化代码，选项非常丰富，可以[配置成各种代码风格](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options)，还可以把你的配置存到.clang-format文件中，这样其他人也可以使用同样的代码风格。
各大IDE也都有相应的clang-format插件来自动格式化代码。

**Comment by sisong** [comment]
现在格式化代码造成大量代码差异可能不太值得；    
我主要使用xcode写代码,同时交叉使用windows下的vc和linux下的Code::Blocks来编译测试，也造成了一些不统一；

**Comment by JayXon** [comment]
其实可以选择不格式化所有代码，而是每次commit只格式化改动的那几行代码（用git-clang-format），这样的话不会影响git历史，然后慢慢的所有代码就都符合格式了。
