### ISSUE TITLE
关于v4接口的归类

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#250]
compressed_stream_as_uncompressed() + patch_single_stream_diff()
那可以理解这个patch_single_stream_diff()其实是as uncompressed之后用的（其实是用给不compress的data）
![image](https://user-images.githubusercontent.com/54618402/129227795-f6aea134-b47c-498b-9f5a-93afc88e2933.png)
放在这个single compressed标题下面是不是不太合适

**Comment by sisong** [comment]
这里没有那么严谨，仅仅是大概告知有这些相关的重要函数

**Comment by sfsfsf183** [comment]
好的～
