### ISSUE TITLE
是不是可以不解压缩直接patch

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#251]
有没有接口实现这样的功能（今天好像看到一个，但是没及时记录，有点遗忘

**Comment by mynameisenthusiasm** [comment]
因为好多接口带有decompress字眼，patch_decompress用给 非single compressed
patch_single_dicompressed_diff用给single compressed （compressed as uncompressed）那这个as到底是真的解压缩了吗🙈 （安卓上要不要安装相应的解压缩库啊）

**Comment by mynameisenthusiasm** [comment]
因为好多接口带有decompress字眼，patch_decompress用给 非single compressed
patch_single_dicompressed_diff用给single compressed （compressed as uncompressed）那这个as到底是真的解压缩了吗🙈 （安卓上要不要安装相应的解压缩库呢）

**Comment by sisong** [comment]
创建补丁的时候，带有压缩插件的参数，这个是可以null的，从而补丁数据不会被压缩；    
如果设置了压缩插件，那当然在安卓上也得有对应的解压缩插件才能正确的patch， 可以看看`builds\android_ndk_jni_mk\Android.mk`，默认带了那些解压缩插件。
