### ISSUE TITLE
v4接口命名

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#252]
接口命名如何与命令行参数相对应？

**Comment by mynameisenthusiasm** [comment]
（感觉这个问题有点大，明天我自己来补充一下🙈
今天看您的代码提了很多问题，主要是在issue mark一下，明天如果大佬有空帮我看下很感谢，不过之后自己如果有了新的感悟也会及时补充～ 【为了问题的整洁性最后我会删掉这楼

**Comment by sisong** [comment]
建议先看看命令行参数的说明，并实际执行一下，然后再看源代码就比较容易了

**Comment by sfsfsf183** [comment]
嗯嗯好的，谢谢建议

**Comment by sfsfsf183** [comment]
发现备注确实写的比较全，所以理解之后确实也没什么补充了
