### ISSUE TITLE
hdiff的assumption与bsdiff是否相同

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#253]
即
![image](https://user-images.githubusercontent.com/54618402/129298617-ea89f61c-6af4-4c0c-8746-792772082c14.png)

**Comment by sisong** [comment]
可以看我的2006年的一篇blog： https://blog.csdn.net/housisong/article/details/658863    这是这个库的基础。

**Comment by sfsfsf183** [comment]
好文！谢谢
