### ISSUE TITLE
关于内存复杂度

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#256]
![image](https://user-images.githubusercontent.com/54618402/130312889-2fd1f98c-c9a9-47a2-a633-c5346c52ed72.png)
命令行上写的是cachesize+4*decompress buffer size 但是头文件注释是
![image](https://user-images.githubusercontent.com/54618402/130312926-92285802-14ac-4e1a-b8b0-409a9e9d659b.png)
请问cacheSize = hpatch_kStreamCacheSize*6 stack memory 吗？

**Comment by sfsfsf183** [comment]
好像是不一样的
在这里hpatch_kStreamCacheSize*6 stack memory这个东西被归入了O(1)?

**Comment by sisong** [comment]
命令行那里，让使用者可以自己选择被当作缓存的内存大小；    
而后面的注释，表明这个函数已经做了个固定的选择，即设置了cacheSize `= hpatch_kStreamCacheSize*6`

**Comment by sfsfsf183** [comment]
原来如此（不好意思命名的时候智商不太在线
