### ISSUE TITLE
此算法为何比Bsdiff优秀

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#257]
可不可以略述改进在哪里🤔
数据存储格式吗
我看Bsdiff也是基于“覆盖线”的算法

可不可以理解这种算法放大了assumption，bsdiff是根据程序的格式进行优化，这种算法因为没有基于谁优化，所以针对zip文件这种大杂烩普遍效果比较好？

**Comment by sisong** [comment]
“此算法为何比Bsdiff优秀”  “可不可以略述改进在哪里”   
应该说是相当吧。    
不是太熟悉bsdiff，瞄了下，知道是基于“覆盖线”的算法（我自己的分类方法）； 而xdelta，看了一下，也没太明白其算法的抽象基础，猜测是类似字典压缩算法之类的； jojodiff我猜测可能是基于编辑距离一类的算法；      
bsdiff针对应用程序较多，而我需要处理的主要数据一直是整个游戏的更新，所以一些设计选择可能不同（优化方向不同）。    
hdiffpatch的-m模式可以参考我[2006年的一篇blog](https://blog.csdn.net/housisong/article/details/658863)，这是内部版本的实现思路，文章内容较少，但看完文章自己实现一个版本应该问题不大；其中还有一些优化思路并没有在开源版本中实现。   
hdiffpatch的-s模式，类似于同步算法，大概思路：将old数据按固定大小分块，计算出每个块的hash值，然后对new数据执行roll-hash来匹配这些hash从而快速寻找到old中的相等匹配区域；

**Comment by sfsfsf183** [comment]
感谢大佬耐心解惑，已经大致阅读您的blog了～

1. “将old数据按固定大小分块，计算出每个块的hash值“ 似乎逐步明白这个帖子了：https://github.com/sisong/HDiffPatch/issues/255
不过现在又有点疑惑这个当时说的“格式”指的是什么？数据压缩格式？（🤔让我想起single或者非single那种数据格式是不同的）

2. 🤔这个分块参数要怎么调整呢，减小参数，我按照接近mem推测，diff内存占用增大，时间变长，patch时间变短，patch内存怎么变呢（？）


3.不过这又令我产生了另外一个疑问，那为什么这种-s会带来包大小的增加呢，
可不可以粗略理解一下是
将old数据按固定大小分块，计算出每个块的hash值，然后对new数据执行roll-hash来匹配这些hash从而快速寻找到old中的相等匹配区域；
这样操作之后，我们需要搬运的数据更多（没之前那么精确了）
🤔

4. by the way小小的脑袋再次冒出小小的疑问 大佬自己设计之前不会先借鉴一下别人的diff算法吗（？）这个算法就是灵光一现出现的吗（？）🤔或者说这个算法有其他算法作为基础吗

**Comment by sisong** [comment]
1. “当时说的“格式”指的是什么？数据压缩格式？（🤔让我想起single或者非single那种数据格式是不同的）”   
是的，single\非single 是不同的编码格式。   -m和-s是两种不同的算法，但可以输出相同的文件格式。    
2. “减小参数 ... diff内存占用增大，时间变长，patch时间变短，patch内存怎么变呢（？）”      
blockSize减小，“diff内存占用增大，时间变长”，是的； 但对patch的影响不太明显。     
3. “-s会带来包大小的增加呢” “需要搬运的数据更多（没之前那么精确了）”      
blockSize增大，一般情况下补丁包会变大（但如果blockSize太小太小，在很多数据集上，补丁包反而会变大), 因为一些较小的匹配就会漏掉。      
4. “不会先借鉴一下别人的diff算法吗（？）这个算法就是灵光一现出现的吗（？）🤔或者说这个算法有其他算法作为基础吗”    
刚开始当然用的别人的算法（见blog里提到的[vpatch](http://www.tibed.net/vpatch)），但实在太慢了,那时候没有找到其他更好的算法，没有办法就只能自己动手写了一个。     
我的算法是2006年初上的线（见blog），并且支持目录之间的diff&patch，支持多种内部优化来生成足够小的补丁包。  
而知道bsdiff是非常后面的事情了，前些年偶然看到安卓系统的源代码中带了一个diff算法才知道的。     
“这个算法就是灵光一现出现的吗” 应该算是吧，你可以从blog中看到，整个想法实际上并不复杂； 当然各种优化策略反而更花时间（比如为了优化 那时用游戏引擎写了一个old-new二维bit数组地图浏览器来理解数据到底是怎样的）。     
“或者说这个算法有其他算法作为基础吗”  算法不可能凭空产生，那时的我遇到了需要解决的现实问题，而我在网上看到过用后缀数组解决回文问题，那他也能用可以接受的时间帮我找到我的二维bit数组假设中的所有线段（我那时针对问题抽象出的“理想”环境下的最佳补丁），从而整条算法路经才能走通。

**Comment by sfsfsf183** [comment]
wow再次感谢大佬的耐心回复～！
上面的问题基本都了解了，就还剩下最后一个小小的不太明确的地方
请问这个”文件格式“对使用会有什么样的影响呢？文件格式相同就能使用同一个patch接口，文件格式不同就不行？🤔

**Comment by sfsfsf183** [comment]
(还是reopen一下吧 又出现一个问题，那就是-s是没有用后缀数组那些的是吧🤔 这个roll-hash ！=后缀数组，是两套完全不同的思路（？）

**Comment by sisong** [comment]
“文件格式相同就能使用同一个patch接口，文件格式不同就不行？”         
那当然，diff&patch对补丁的储存方式必须有一致的约定。    
    
“这个roll-hash ！=后缀数组，是两套完全不同的思路（？）”      
是的，-s模式是后来随着游戏的变大需要处理超大的游戏数据才添加的，有人用于处理过几十GB的3A游戏的更新；  这种新的需求，用-m模式，diff时间和内存都无法接受。    
那就需要一个新的思路来解决问题： diff时不能加载所有的数据到内存，那就用流；那要如何匹配，就用hash值来代替首次匹配，hash一样才测试数据是否真的匹配； 每次都只加载少量数据到内存，利用一些缓存来减低磁盘访问量； roll-hash一般用的adler32太慢并且hash冲突率很高（错误匹配的速度惩罚很严重），那就新写一个更快的并且冲突最小的roll-hash算法（fast_adler64）；hash表匹配太慢，那就再用一个bloom过滤来预先降低无效匹配； 单个hash匹配和处理太慢，将hash值按块顺序看成字符串进行字符串的查找和匹配； ....       
（-s模式的思路，这里还是有点简略，可能也需要一篇技术文章来说明思路）

**Comment by sfsfsf183** [comment]
好的 谢谢回复～

**Comment by sisong** [comment]
稍微细化了一下-s模式diff算法，见blog文章 [一个基于字节的流式diff算法](https://blog.csdn.net/housisong/article/details/126857706)

​

**Comment by wishes2018** [comment]
patch上比bsdiff快，是因为HDiffPatch使用了多线程并行，而bsdiff只是单线程么？还是还有其他优化？

**Comment by sisong** [comment]
@wishes2018 
hdiffpatch的hpatch本身并不会bspatch快很多，hpatch只是可以使用一个固定大小的内存缓冲区来执行patch而已。而你觉得快，可能是patch时的不同解压缩算法造成的。
