### ISSUE TITLE
-m与-s

### ISSUE THREAD

**Issue by sfsfsf183** [sisong/HDiffPatch#259]
![image](https://user-images.githubusercontent.com/54618402/130325300-643821f7-cfee-4932-b0be-c317d19dd397.png)
使用目前的mac binary 
通过提供不同的-s -m 参数
可以看出几乎没什么差别？
合成时间也没什么差别
除了-m合成了一分多钟 -s三秒解决问题
请问是我的打开方式有什么问题嘛

**Comment by sisong** [comment]
建议添加压缩参数后再对比补丁包大小。   
另外-s模式本来就是为了优化速度和减少内存占用才开发的

**Comment by sfsfsf183** [comment]
确实 我发现-s参数越小越patch快（包越小）？🤔可不可以理解-s参数越小越接近mem？我刚开始还以为是stream size越大越接近mem

**Comment by sfsfsf183** [comment]
好的～
