### ISSUE TITLE
patch the same /dev/mmcblk0p29 device will occure error,use hpatchz

### ISSUE THREAD

**Issue by zhu-clam** [sisong/HDiffPatch#261]
Hi sisong:

   Recently , I come across one block issue when use hpatchz, That is I want incremental upgrade block device which named /dev/mmcblk0p29 use hpatchz tool .The command and process log show at blow, please help me to checkout it.

root@j5dvb-hynix3G:/var/volatile/tmp# hpatchz /dev/mmcblk0p29 /inc_system.img /dev/mmcblk0p29 -f
NOTE: outNewPath temp file will be rename to oldPath name after patch!
old : "/dev/mmcblk0p29"
diff: "/inc_system.img"
out : "/dev/mmcblk0p29001.tmp"
oldDataSize : 1073741824
diffDataSize: 32307948
newDataSize : 1073741824
out newFile write ERROR!

hpatchz time: 6.786 s

but My Company‘s colleague tell me that the bspatch tool is ok. but I do not want use it. 
So can you help me to slove this issue ?
at the end , I see the log which is :out : "/dev/mmcblk0p29001.tmp", is there anything ? thx
回复中文即可。。。

**Comment by sisong** [comment]
"out newFile write ERROR!"  说明，fopen调用没有问题，很可能是fwrite时出现了错误。      
 如果"/dev/mmcblk0p29001.tmp"文件中有数据，那很可能是磁盘满了之类的？       
因为old和new文件名相同，而程序并不支持原地替换，所以需要先生成new的临时文件，然后完成后在替换掉old文件。

**Comment by zhu-clam** [comment]
OK, I will try to print some log to show about "/dev/mmcblk0p29001.tmp" this file's information.

**Comment by sisong** [comment]
问题解决了？
