### ISSUE TITLE
编译so库报错

### ISSUE THREAD

**Issue by rube520** [sisong/HDiffPatch#262]
E:\bspatch\HDiffPatch-4.0.6\builds\android_ndk_jni_mk>build_libs.bat

E:\bspatch\HDiffPatch-4.0.6\builds\android_ndk_jni_mk>ndk-build NDK_PROJECT_PATH=.  APP_BUILD_SCRIPT=Android.mk  NDK_APPLICATION_MK=Application.mk
[armeabi-v7a] Compile thumb  : hpatchz <= hpatch_jni.c
[armeabi-v7a] Compile thumb  : hpatchz <= hpatch.c
In file included from ././hpatch.c:12:
In file included from ./../../hpatchz.c:76:
./../../decompress_plugin_demo.h:341:13: fatal error: 'LzmaDec.h' file not found
#   include "LzmaDec.h" // "lzma/C/LzmaDec.h" https://github.com/sisong/lzma
            ^~~~~~~~~~~
1 error generated.
make: *** [C:/Users/ubtech/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-binary.mk:476: obj/local/armeabi-v7a/objs/hpatchz/./hpatch.o] Error 1

E:\bspatch\HDiffPatch-4.0.6\builds\android_ndk_jni_mk>

**Comment by sisong** [comment]
you need clone lzma lib;   
```
$ cd E:\bspatch\HDiffPatch-4.0.6
$ git clone https://github.com/sisong/lzma.git ..\lzma
```

**Comment by rube520** [comment]
^
././../../../lzma/Asm/arm64/LzmaDecOpt.S:267:276: warning: null character ignored [-Wnull-character]
  ...#݄<BC>&<CD>S<8C><8F>J<U+0005><DF>~<E6><F7><D6><CC><D7><U+0000><C0><BD>F<EA><U+0001>.<FF>J<A2><B8><D4>_<DE>i<E8>
                                                          ^
135 warnings generated.
././../../../lzma/Asm/arm64/LzmaDecOpt.S:1:2: error: invalid operand
b#eW ? E-SafeNet LOCK 昩jT?:?gWn抦 .4茲?? B 綣Vン戩0qv”槢gY探?ly韕HoXV蓃燥5絘=:?榀窷?q??裆砆?蠥kL略鐨>噙F雁鍿,xe坞?w逵漏gHo??X逵漏gHo??XX       肺袑?遐X 甽疋蓵衤Z?!ㄋRlSG妛殼殼
././../../../lzma/Asm/arm64/LzmaDecOpt.S:1:106: error: invalid operand
b#eW ? E-SafeNet LOCK 昩jT?:?gWn抦 .4茲?? B 綣Vン戩0qv”槢gY探?ly韕HoXV蓃燥5絘=:?榀窷?q??裆砆?蠥kL略鐨>噙F雁鍿,xe坞?w逵漏gHo??X逵漏gHo??XX       肺袑?遐X 甽疋蓵衤Z?!ㄋRlSG妛殼殼
././../../../lzma/Asm/arm64/LzmaDecOpt.S:2:1: error: invalid character in input
GC抬穢2E鯷訸kM瘐?抃狙znC 8ǎ跦 尽緰轊嚓A'??官&衈癔IH軺鲣屙諧匕W蠨穲沛?咹 5?偠甓睪t?yzt?yzz
././../../../lzma/Asm/arm64/LzmaDecOpt.S:2:1: error: unexpected token at start of statement
GC抬穢2E鯷訸kM瘐?抃狙znC 8ǎ跦 尽緰轊嚓A'??官&衈癔IH軺鲣屙諧匕W蠨穲沛?咹 5?偠甓睪t?yzt?yzz

乱码了。环境是windows 10

**Comment by sisong** [comment]
看起来是arm64的汇编代码编译失败；       
我用的也是windows10；      
可能的解决方案： 1. 重装NDK试试  2. 修改Android.mk关闭这些汇编代码，即移除ifeq ($(TARGET_ARCH_ABI),arm64-v8a)内容；  3. 下载我releases里提供的编译好的.so文件

**Comment by rube520** [comment]
大佬用的什么版本的NDK
你编译好的so没有diff只有patch，我想快速验证diff出来的包大小

**Comment by rube520** [comment]
感谢大佬，按照第二条编译成功了。不过有个问题，你提供的java文件只有patch，没有diff

**Comment by sisong** [comment]
diff需要你自己弄
