### ISSUE TITLE
内存占用控制

### ISSUE THREAD

**Issue by gneworld** [sisong/HDiffPatch#264]
你好，我现在的原包是930MB，可用内存限制在200MB，请问如何给hpatchz 设置参数，可以控制在patch过程中占用内存不超限呢，谢谢

**Comment by sisong** [comment]
你是在安卓手机上用的？   那`HPatch.patch()`函数的cacheMemory参数就是 内存缓存 字节数；  再加上一些解压内存（压缩的时候控制）就是执行时的内存占用了。

**Comment by gneworld** [comment]
多谢多谢~~

**Comment by gneworld** [comment]
你好， 试了下128K和128m的patch速度差不多，所以这个参数 -s-cacheSize 仅仅影响内存占用不影响patch时间的吗，谢谢

**Comment by gneworld** [comment]
你好，另外试了下，虽然patch过程中内存占用控制住了，但会生成一个930MB的临时文件，而我需要在同一块设备里patch，也就是参数里的 oldfile 和 newfile 都是 /dev/sda1，而我执行./hpatchz所在的分区大小只有 64MB，请问这种情况该如何处理呢，期待您的回复~

**Comment by sisong** [comment]
这个属于原地更新，一般这样的存储设备读写都非常快；    
 现在的库还没有支持这个特性。       
如果要支持，可能的方向：   
1. 现有的补丁上写一个新的patch算法，见讨论 #36  ；    
1. 全新实现一个diff&patch组合，以块为操作单位的算法，diff时规划好patch时搬运数据的最大次数的路径。

**Comment by gneworld** [comment]
> 另外能不能问一下，你们是什么类型的设备？

你好，是工业用Android平板

**Comment by sisong** [comment]
内存够大吗？ 大到能把old文件放到内存

**Comment by gneworld** [comment]
> 内存够大吗？ 大到能把old文件放到内存

内存只有200MB，old文件也就是/dev/sda1是930MB

**Comment by sisong** [comment]
原地更新的技术路线，有思考过做一个实现的尝试，但实际上因为需求不够多的原因，也不是我要用的需求，而且还有其他更想做的事情，而没机会尝试。     
你可以找找其他的实现？
