### ISSUE TITLE
目录patch时没有处理符号链接文件

### ISSUE THREAD

**Issue by shengjiangwuqq** [sisong/HDiffPatch#265]
hdiffz linux-5.14 linux-5.14.1 linux-5.14_linux-5.14.1_patch
hpatchz linux-5.14 linux-5.14_linux-5.14.1_patch linux-5.14.1_new
diff -r linux-5.14.1 linux-5.14.1_new
只在 linux-5.14.1/arch/arm/boot/dts 存在：sun8i-a23-ippo-q8h-v1.2.dts
只在 linux-5.14.1/arch/arm/boot/dts 存在：sun8i-a23-ippo-q8h-v5.dts
只在 linux-5.14.1/arch/arm/boot/dts 存在：sun8i-a33-et-q8-v1.6.dts
只在 linux-5.14.1/arch/arm/boot/dts 存在：sun8i-a33-ippo-q8h-v1.2.dts
只在 linux-5.14.1/arch/arm64/boot/dts/arm 存在：vexpress-v2m-rs1.dtsi
只在 linux-5.14.1/Documentation 存在：Changes
只在 linux-5.14.1/include/dt-bindings/clock 存在：qcom,dispcc-sm8150.h
只在 linux-5.14.1/include/dt-bindings/input 存在：linux-event-codes.h
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：arc
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：arm
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：arm64
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：dt-bindings
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：h8300
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：microblaze
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：mips
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：nios2
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：openrisc
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：powerpc
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：sh
只在 linux-5.14.1/scripts/dtc/include-prefixes 存在：xtensa
只在 linux-5.14.1/scripts/dummy-tools 存在：nm
只在 linux-5.14.1/scripts/dummy-tools 存在：objcopy
只在 linux-5.14.1/tools/testing/selftests/powerpc/copyloops 存在：copy_mc_64.S
只在 linux-5.14.1/tools/testing/selftests/powerpc/copyloops 存在：copyuser_64.S
只在 linux-5.14.1/tools/testing/selftests/powerpc/copyloops 存在：copyuser_power7.S
只在 linux-5.14.1/tools/testing/selftests/powerpc/copyloops 存在：memcpy_64.S
只在 linux-5.14.1/tools/testing/selftests/powerpc/copyloops 存在：memcpy_power7.S
只在 linux-5.14.1/tools/testing/selftests/powerpc/nx-gzip/include 存在：vas-api.h
只在 linux-5.14.1/tools/testing/selftests/powerpc/primitives/asm 存在：asm-compat.h
只在 linux-5.14.1/tools/testing/selftests/powerpc/primitives/asm 存在：asm-const.h
只在 linux-5.14.1/tools/testing/selftests/powerpc/primitives/asm 存在：feature-fixups.h
只在 linux-5.14.1/tools/testing/selftests/powerpc/primitives/asm 存在：ppc_asm.h
只在 linux-5.14.1/tools/testing/selftests/powerpc/primitives 存在：word-at-a-time.h
只在 linux-5.14.1/tools/testing/selftests/powerpc/stringloops 存在：memcmp_32.S
只在 linux-5.14.1/tools/testing/selftests/powerpc/stringloops 存在：memcmp_64.S
只在 linux-5.14.1/tools/testing/selftests/powerpc/stringloops 存在：strlen_32.S
只在 linux-5.14.1/tools/testing/selftests/powerpc/vphn/asm 存在：lppaca.h
只在 linux-5.14.1/tools/testing/selftests/powerpc/vphn 存在：vphn.c

**Comment by sisong** [comment]
故意跳过的，readme中就有说明      
原因： 不熟悉，不知道如何正确处理；链接文件有相对路径和绝对路径的概念？是否会造成安全性问题？ 链接文件和操作系统有耦合，跨操作系统下如何patch？
