### ISSUE TITLE
GNU-diff context report #rejected

### ISSUE THREAD

**Issue by gvanem** [sisong/HDiffPatch#271]
Is there any way to make `hdiffz` report in GNU-diff context diff format?
Like with `diff -u3 old-dir new-dir`:
```diff
--- old-dir\Makefile.b32 Thu Jan 20 12:22:45 2021
+++ new-dir\Makefile.b32  Thu Apr 07 13:58:57 2021
@@ -34,18 +34,18 @@
 PROGNAME = curl.exe

 # Setup environment
-PP_CMD   = cpp32 -q -P-
 CC_CMD   = bcc32 -q -c
 LD       = bcc32
 RM       = del 2>NUL
-MKDIR    = mkdir
-RMDIR    = rmdir /s /q 2>NUL
+MKDIR    = md
+RMDIR    = rd /q 2>nul
+COPY     = $(COMSPEC) /c copy /y
```

And what about recursive directory walking? No option `-r` AFAICS. I'm looking for something faster than GNU-diff, so this 
program / library seems promising.

**Comment by sisong** [comment]
The diff format should be possible, You can start from get_match_covers_by_sstring() or get_match_covers_by_block();
but hdiff is not designed for this purpose;

**Comment by gvanem** [comment]
> You can start from get_match_covers_by_sstring() or get_match_covers_by_block();

Thanks. But I fail to understand all those parameters. The 4 first could probably be from mem-mapped files, no?
But how do I setup the parameters for text I/O. Can you please give an example?

**Comment by sisong** [comment]
#rejected
