### ISSUE TITLE
HDiffPatch-4.1.0 windows版本 执行hpatchz 那个弹框如何能去掉，path多个文件时特别影响性能

### ISSUE THREAD

**Issue by liqt** [sisong/HDiffPatch#274]
我写了一个脚本多次调用hpatchz来patch很多单个文件，结果发现整体时间比bspatch慢很多， bspatch 花费5s左右， hpatchz花费55s

感觉可能是启动窗口耗时比较多，如何才能不启动窗口再后面静默执行呢。

示例python脚本：
```
    def hpatch_internal(patch_dir, origin_dir, out_dir):
        #print("hpatch_internal")
        for sdir in os.listdir(patch_dir):
            patchFile = os.path.join(patch_dir, sdir)
            orignFile = os.path.join(origin_dir, sdir)
            outFile = os.path.join(out_dir, sdir)
            #print("patchFile={}".format(patchFile))
            #print("orignFile={}".format(orignFile))
            if os.path.isdir(patchFile):
                self.hpatch_internal(patchFile, orignFile, outFile)
            elif os.path.isfile(patchFile):
                #print("out_dir={}".format(out_dir))
                if not os.path.exists(out_dir):
                    os.makedirs(out_dir)
                cmd_str="hpatchz {0} {1} {2}".format(orignFile, patchFile, outFile)
                #cmd_str="bspatch {0} {1} {2}".format(orignFile, outFile, patchFile)
                res_code = subprocess.call(cmd_str, shell=True)
                if res_code != 0:
                    raise Usage("{} failed".format(cmd_str))

```

**Comment by sisong** [comment]
先试试给hpatchz添加一个参数“-m”  看看速度怎么样？

**Comment by sisong** [comment]
另外，我查了一下，`subprocess.call`可以支持隐藏调用的命令行窗口，参考： https://stackoverflow.com/questions/7006238/how-do-i-hide-the-console-when-i-use-os-system-or-subprocess-call

**Comment by liqt** [comment]
非常感谢！ 我在hpatchz.c中加入这行，可以屏蔽掉控制台窗口。
#pragma comment(linker,"/subsystem:windows /ENTRY:wmainCRTStartup")

测试后发现patch为34秒， 比bspatch慢了不少， 请问patch有其他设置得地方吗？

我的diff脚本为：
#====================
   def hdiff_internal(self, newdir, origindir, deltaDir):
        print("newdir={}".format(newdir))
        for sdir in os.listdir(newdir):
            srcFile = os.path.join(newdir, sdir)
            orignFile = os.path.join(origindir, sdir)
            deltaFile = os.path.join(deltaDir, sdir)
            print("srcFile={}".format(srcFile))
            print("orignFile={}".format(orignFile))
            if os.path.isdir(srcFile):
                self.hdiff_internal(srcFile, orignFile, deltaFile)
            elif os.path.isfile(srcFile):
                if not os.path.exists(deltaDir):
                    os.makedirs(deltaDir)
                cmd_str="hdiffz -c-lzma2 {0} {1} {2}".format(orignFile, srcFile, deltaFile)
                #cmd_str="bsdiff {0} {1} {2}".format(orignFile, srcFile, deltaFile)
                res_code = subprocess.call(cmd_str, shell=True)
                if res_code != 0:
                    raise Usage("{} failed".format(cmd_str))

**Comment by liqt** [comment]
#!/usr/bin/python
# -*- coding: utf-8 -*

import sys
import getopt
import os, os.path
import re
import json
import time
import subprocess
import shutil
import hashlib
import zlib
import platform

            # if not os.path.exists(targetDir):
            #     os.makedirs(targetDir)
class Usage(Exception):
    def __init__(self, msg):
        self.msg = msg
        print("msg={}".format(msg))

class JJHdiffPatch(object):
    def __init__(self):
        self._origin_dir = ""
        self._new_dir = ""
        self._out_dir = ""
        self._mode = ""
        self._patch_dir = ""

    def hdiff_internal(self, newdir, origindir, deltaDir):
        print("newdir={}".format(newdir))
        for sdir in os.listdir(newdir):
            srcFile = os.path.join(newdir, sdir)
            orignFile = os.path.join(origindir, sdir)
            deltaFile = os.path.join(deltaDir, sdir)
            print("srcFile={}".format(srcFile))
            print("orignFile={}".format(orignFile))
            if os.path.isdir(srcFile):
                self.hdiff_internal(srcFile, orignFile, deltaFile)
            elif os.path.isfile(srcFile):
                if not os.path.exists(deltaDir):
                    os.makedirs(deltaDir)
                cmd_str="hdiffz -c-lzma2 {0} {1} {2}".format(orignFile, srcFile, deltaFile)
                #cmd_str="bsdiff {0} {1} {2}".format(orignFile, srcFile, deltaFile)
                res_code = subprocess.call(cmd_str, shell=True)
                if res_code != 0:
                    raise Usage("{} failed".format(cmd_str))




    def hdiff(self):
        print("hdiff()")
        print("self._origin_dir={}".format(self._origin_dir))
        print("self._new_dir={}".format(self._new_dir))
        print("self._out_dir={}".format(self._out_dir))

        if not os.path.exists(self._origin_dir):
            assert(False), "ERROR: not exist {}".format(self._origin_dir)
        if not os.path.exists(self._new_dir):
            assert(False), "ERROR: not exist {}".format(self._new_dir)

        if os.path.exists(self._out_dir):
            shutil.rmtree(self._out_dir)

        os.makedirs(self._out_dir)

        self.hdiff_internal(self._new_dir, self._origin_dir, self._out_dir)

    def hpatch(self):
        print("hpatch()")
        print("self._origin_dir={}".format(self._origin_dir))
        print("self._out_dir={}".format(self._out_dir))
        print("self._patch_dir={}".format(self._patch_dir))
        if not os.path.exists(self._origin_dir):
            assert(False), "ERROR: not exist {}".format(self._origin_dir)

        if os.path.exists(self._out_dir):
            shutil.rmtree(self._out_dir)

        os.makedirs(self._out_dir)

        self.hpatch_internal(self._patch_dir, self._origin_dir, self._out_dir)


    def hpatch_internal(self, patch_dir, origin_dir, out_dir):
        #print("hpatch_internal")
        for sdir in os.listdir(patch_dir):
            patchFile = os.path.join(patch_dir, sdir)
            orignFile = os.path.join(origin_dir, sdir)
            outFile = os.path.join(out_dir, sdir)
            #print("patchFile={}".format(patchFile))
            #print("orignFile={}".format(orignFile))
            if os.path.isdir(patchFile):
                self.hpatch_internal(patchFile, orignFile, outFile)
            elif os.path.isfile(patchFile):
                #print("out_dir={}".format(out_dir))
                if not os.path.exists(out_dir):
                    os.makedirs(out_dir)
                cmd_str="hpatchz {0} {1} {2}".format(orignFile, patchFile, outFile)
                #cmd_str="bspatch {0} {1} {2}".format(orignFile, outFile, patchFile)
                res_code = subprocess.call(cmd_str, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                if res_code != 0:
                    print("res_code={}".format(res_code))
                    raise Usage("{} failed".format(cmd_str))


    def process(self):
        print("process() mode={}".format(self._mode))
        if self._mode == "diff":
            self.hdiff()
        elif self._mode == "patch":
            self.hpatch()

def main(argv):
    hdiff = JJHdiffPatch()
    try:
        try:
            opts, args = getopt.getopt(argv, ["h"], ["origin-dir=", "new-dir=", "out-dir=", "diff", "patch", "patch-dir="])
        except getopt.error as msg:
            raise Usage(msg)
        for opt, arg in opts:
            if opt == "--origin-dir":
                print("--origin-dir {}".format(arg))
                hdiff._origin_dir = arg
            elif opt == "--new-dir":
                print("--new-dir {}".format(arg))
                hdiff._new_dir = arg
            elif opt == "--out-dir":
                print("--out-dir {}".format(arg))
                hdiff._out_dir = arg
            elif opt == "--diff":
                print("--diff")
                hdiff._mode = "diff"
            elif opt == "--patch":
                print("--patch")
                hdiff._mode = "patch"
            elif opt == "--patch-dir":
                print("--patch-dir {}".format(arg))
                hdiff._patch_dir = arg
            else:
                raise Usage("{} not support yet".format(opt))
    except Usage as err:
        print >> sys.stderr, err.msg
        print >> sys.stderr, "for help use --help"
        return 2
    starttime = time.time()
    hdiff.process()
    difference = time.time() - starttime
    print("diff total time={}".format(difference))

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))

**Comment by liqt** [comment]
我上传了我的测试脚本

**Comment by liqt** [comment]
> 

我加上-m 测试35s比不加略微慢了一点点

**Comment by sisong** [comment]
可以试试 `hdiffz -SD -c-zstd-21-25 ...` ，来看看是否有改善hpatchz速度；（diff时可尝试加-block和-cache来加快diff速度）
“bspatch 花费5s” “patch为34秒”      
这个差别很大了！ 应该不是简单的参数能够解决的； 一定有一个确定的原因        
可能的怀疑：    
1.  bsdiff、bspatch有过修改，比如补丁包实际没有压缩？   或者bspatch是多个进程在并行？   所以快。   
2.  目录中的文件大小平均很小很小？  造成程序启动时间占了过大比重   
3.  hpatchz支持兼容bsdiff的补丁，可以试试用bsdiff的补丁接hpatchz来打补丁试试看 
4.  hdiffz -BSD可以创建bsdiff兼容的补丁，可以接bspatch试试看

**Comment by liqt** [comment]
使用参数：hdiffz -d -SD-2m -c-zstd-21 -block-1m -cache  后生成diff的形成更慢了，耗时33.6370000839s

1. bsddiff, bspatch 来自https://github.com/cnSchwarzer/bsdiff-win   4.3版本
2. 目录中的文件确实很小，绝大部分都在1M以内
3. hpatchz使用bsdiff的补丁，测试时间区别不大都34s
4. 使用hdiffz -BSD创建的bsdiff兼容补丁使用bspatch打补丁耗时4.96s和bsdiff，bspatch相近

另外： 那些日志输出应该也有性能消耗。我尝试关闭试试

**Comment by liqt** [comment]
使用参数：hdiffz -d -SD-2m -c-zstd-21 -block-1m -cache 后生成diff的形成更慢了，耗时33.6370000839s
这个压缩level太高了，我设置为hdiffz -d -SD-2m -c-zstd-6 -block-1m -cache， 耗时9s

**Comment by sisong** [comment]
（-block-1m  数据1m,block也1m太大了，建议用默认值-block就好，也就是-block-1k，当然再小一些也行）      
    
补丁包大小有异常吗？     这个patch速度差别实在太奇怪了，hpatchz用了debug版？用的我编译好的试试呢？       
能否帮忙:找两个patch时间差异较大的一组2个文件发给我，我在本地试试看

**Comment by liqt** [comment]
1. 去掉日志输出
2. hdiffz -d -SD-2m -c-zstd-6 -block -cache

测试耗时6.9s， 性能提升明显， hdiffz已经比bsdiff快了， 但是hpatchz 感觉差距有点太大了， 我看一下patch后内容是否一致

**Comment by liqt** [comment]
我把样本脱敏一下看看发你吧。 housisong@hotmail.com 这个邮箱可以吗？

**Comment by sisong** [comment]
“hdiffz已经比bsdiff快了”   
如果在意diff速度：-s模式更快，比如： `hdiffz  -d -SD-2m -c-zstd-6  -s-48   {0} {1} {2}`   -s后面的参数决定了diff速度和补丁包大小的权衡

**Comment by sisong** [comment]
32bit的hpatchz弹窗和速度慢  这个问题我猜测应该是win10后带来的，对32bit exe做了些特别检查（兼容性助手？）    
另外发现用hdiffz --patch代替hpatchz后又正常，所以用diff的编译设置替换了patch的，问题解决。
