### ISSUE TITLE
incompatible architecture

### ISSUE THREAD

**Issue by wuxinvip** [sisong/HDiffPatch#277]
incompatible architecture (have 'arm64', need 'x86_64')

**Comment by sisong** [comment]
你这个是在mac m1上运行 [hdiffpatch_v4.1.2_bin_macos.zip](https://github.com/sisong/HDiffPatch/releases/download/v4.1.2/hdiffpatch_v4.1.2_bin_macos.zip) 时返回的错误？     
我在max x64上测试过，但没有m1的测试设备

**Comment by wuxinvip** [comment]
嗯嗯 是的 m1的笔记本



| |
连先生
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月24日 19:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [sisong/HDiffPatch] incompatible architecture (Issue #277) |

你这个是在mac m1上运行 hdiffpatch_v4.1.2_bin_macos.zip 时返回的错误？
我在max x64上测试过，但没有m1的测试设备

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sisong** [comment]
你可以自己编译试试：  
先下载相关仓库
``` 
git clone https://github.com/sisong/HDiffPatch.git  <codepatch>/HDiffPatch
cd  <codepatch>/HDiffPatch
git clone https://github.com/sisong/libmd5.git ../libmd5
git clone -b fix-make-build https://github.com/sisong/lzma.git ../lzma
git clone -b v1.5.0 https://github.com/facebook/zstd.git ../zstd
```
然后可以用xcode打开builds/xcode/HDiffPatch.xcworkspace编译和运行   
（也可以继续在命令行用：make来编译）

**Comment by wuxinvip** [comment]
找到问题了 是 gcc问题 改了之后自己编译就好了 

https://blog.csdn.net/L_boyka/article/details/112554554

**Comment by sisong** [comment]
没看出来和这个问题的关系，   
你是自己编译，然后发现gcc出了兼容性问题？

**Comment by wuxinvip** [comment]
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

用这个gcc编译出来的 会提示上边那个错误

**Comment by wuxinvip** [comment]
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

用这个gcc编译出来的 会提示上边那个错误

**Comment by wuxinvip** [comment]
是的
