### ISSUE TITLE
open Old file ERROR

### ISSUE THREAD

**Issue by gregoryderner** [sisong/HDiffPatch#288]
I have received some type errors. And it only happens in some cases. I tried to find a pattern, but it doesn't seem to have.
I use the latest version of both hdiff and hpatch. Here is the code i'm using:

hdiff

```
FileName = $"./hdiffz.exe",
UseShellExecute = false,
Arguments = $"-s-1k -C-no -c-lzma2-9-1m \"./{currentVersion}/Game Data\" \"{gamePath}\" \"./PATCH {currentVersion} TO {nextVersion}\"",
CreateNoWindow = false,
```

hpatch
`${process.env.hpatchzPath} -f -C-no ".\\Game Data" ".\\PATCH ${version} TO ${newVersion}" ".\\Game Data"`

the error
```
Error Command failed: .\hpatchz -f -C-no ".\Game Data" ".\PATCH 1_4_2 TO 1_4_3" ".\Game Data"
check oldPathType==kPathType_file error!
open oldFile ERROR!
can't delete newTempDir ".\Game Data001.tmp\"  ERROR!
dir patch finish ERROR!
 
    node:internal/process/task_queues:96:5 processTicksAndRejections
```

But this error only occurs in some users.

**Comment by sisong** [comment]
break at `check(oldPathType==kPathType_file);`   
Possible situation:
.  this old file not existed;
. this old file name is a dir; (almost impossible)
. C API `stat(path_utf8,&s);` not work; (you can test remove `check(oldPathType==kPathType_file);` & rebuild hpatchz)

**Comment by sisong** [comment]
> `-s-1k`   

can try `-s-48` to got smaller patch file; (`-m-4` could be better for this purpose, & require too large memory when diff)

> `-c-lzma2-9-1m`   

`1m` dictSize is for reduce memory usage when patching? can try add `-SD` when diff for this purpose.

**Comment by gregoryderner** [comment]
any way to test it? I use busgnag, I can try to pull this information from the user's pc.
>`. C API stat(path_utf8,&s); not work;`

this actually reduced the weight a bit.
>can try -s-48 

yes, it was a try.
>1m dictSize is for reduce memory usage when patching?

---


We don't want to put the patch to be done in memory, because we don't know how much memory our users have. This project is a game for windows.


another related error (maybe it will help us with something)
```
Error Command failed: .\hpatchz -f -C-no ".\Game Data" ".\PATCH 1_4_3 TO 1_4_4" ".\Game Data"
check self->_listener->openNewFile(self->_listener,self->_curNewFile, utf8fileName,fileSize) error!
check self->_listener->openNewFile(self->_listener,self->_curNewRefIndex,&self->_curNewFile) error!
check _file_append_ready(self) error!
check patch_decompress_with_cache(out_newData,oldData,&hdiffData.base, self->_decompressPlugin,temp_cache,temp_cache_end) error!
dir patch run ERROR!
can't delete newTempDir ".\Game Data001.tmp\"  ERROR!
dir patch finish ERROR!
 
    node:internal/process/task_queues:96:5 processTicksAndRejections
```

**Comment by sisong** [comment]
> `This project is a game for windows.`     
hpatchz call API `_wstat64(path_w,&s);` on windows;    
   
> `-C-no` `another related error(...`    
There is also a possibility that the downloaded patchFile's data is incorrect.
   
> `any way to test it?`   
Does collecting filenames help?   
befor `check(oldPathType==kPathType_file)` add code 'if (oldPathType!=kPathType_file) <upload:oldRefFileName>;'
