### ISSUE TITLE
用diffz无参数生成的差分包放入patch接口中报段错误

### ISSUE THREAD

**Issue by wangchz13** [sisong/HDiffPatch#292]
作者您好，可以帮我看看哪里出问题了吗？不知道是不是patch参数的问题。

环境：WSL Ubuntu 20.04.3 LTS 
编译：make LZMA=0 ZSTD=0 MD5=0
测试diffz：./hdiffz led1.hex led2.hex patch 成功
然后用以下代码将led1.hex patch文件放入patch接口中，期望生成led2.hex，结果失败，报段错误，经定位是patch中的_bytesRle_load函数返回失败，gdb调试，发现rle_code！=rle_code_end，out_data！=out_dataEnd导致返回失败
测试代码（部分）：
`
int main(int argc, char const* argv[])
{

    const char* oldname = argv[1];//led1.hex
    const char* patchname = argv[2];//patch
    const char* newname = argv[3];//myled2.hex

    TByte* oldData = 0;
    TByte* patchData = 0;
    TByte newData[5 * 1024];

    FILE* oldfile = fopen(oldname, "rb");
    FILE* patchfile = fopen(patchname, "rb");
    FILE* newfile = fopen(newname, "wb");

    size_t oldsize = getFileSize(oldfile);
    size_t patchsize = getFileSize(patchfile);

    oldData = (TByte*)malloc(oldsize);
    patchData = (TByte*)malloc(patchsize);

    fread(oldData, 1, oldsize, oldfile);
    fread(patchData, 1, patchsize, patchfile);

    patch(newData, newData + 5 * 1024, oldData, oldData + oldsize, patchData, patchData + patchsize);
    fwrite(newData, 1, 5 * 1024, newfile);
    fclose(oldfile);
    fclose(patchfile);
    fclose(newfile);
    return 0;
}
`

gdb调试信息：
`Starting program: /home/wcz/hdifftest/mypatch led1.hex patch myled2.hex

Breakpoint 1, patch (out_newData=0x7ffffffecd20 "0\376}\377\377\177", out_newData_end=0x7ffffffee120 " \342\376\377\377\177",
    oldData=0x8008870 ":1040000008080020B5540000734C000093540000D1\r\n:10401", '0' <repeats 35 times>, "A0\r\n:10402", '0' <repeats 27 times>, "9F5400009D\r\n:10403", '0' <repeats 19 times>, "D5540000D75400002C\r\n:10404000D9540000DB5"..., oldData_end=0x800c3ec "", serializedDiff=0x800c51e "", serializedDiff_end=0x800c424 "")
    at patch.c:84
84          hpatch_BOOL bytesRleload =  _bytesRle_load(out_newData, out_newData_end, serializedDiff, serializedDiff_end);
(gdb) n

Breakpoint 2, _bytesRle_load (out_data=0x7ffffffecd20 "0\376}\377\377\177", out_dataEnd=0x7ffffffee120 " \342\376\377\377\177", rle_code=0x800c51f "",
    rle_code_end=0x800c424 "") at patch.c:176
176         if (  (ctrlBuf==ctrlBuf_end)
(gdb) p ctrlBuf
$2 = (const TByte *) 0x800c51f ""
(gdb) p ctrlBuf_end
$3 = (const TByte *) 0x800c51f ""
(gdb) p rle_code
$4 = (const TByte *) 0x800c51f ""
(gdb) p rle_code_end
$5 = (const TByte *) 0x800c424 ""
(gdb) p out_data
$6 = (TByte *) 0x7ffffffecd20 "0\376}\377\377\177"
(gdb) p out_dataEnd
$7 = (TByte *) 0x7ffffffee120 " \342\376\377\377\177"
(gdb)`

**Comment by wangchz13** [comment]
好像是serializedDiff传的不对，这个要求是create_diff生成的

**Comment by sisong** [comment]
嗯 需要注意patch函数能够支持的补丁格式的说明。

**Comment by wangchz13** [comment]
> 

作者您好，当前hdiffz.exe生成的差分文件是kDiffZ类型的，请问有没有方法生成kDiffO型的文件呢？

**Comment by sisong** [comment]
hdiffz中已经不输出hdiffo格式的补丁，可以自己用代码调用create_diff()函数来创建； 
或者，下载以前的老版本代码库（v4.0之前的版本）编译，然后执行hdiffz命令行时添加 "-o"参数

**Comment by wangchz13** [comment]
问题已解决，非常感谢！ @sisong
