### ISSUE TITLE
Is it possible to run hdiffz on multiple cpu cores ?

### ISSUE THREAD

**Issue by shahar-fleischman** [sisong/HDiffPatch#298]
Hi,

Tried to run hdiffz with -p for multithreading, but it seems it only run on 1 core(consuming 100% of it).
Is it possible to run it on more than 1 core to save time ?

Thanks.

**Comment by sisong** [comment]
now  multi thread only support for compresser

**Comment by sisong** [comment]
no diff, only compressPlugin

**Comment by sisong** [comment]
now multi thread  support for diff
