### ISSUE TITLE
为什么patch函数需要指定输出内容的末尾地址"out_newData_end"？

### ISSUE THREAD

**Issue by vailinice** [sisong/HDiffPatch#303]
你好，我想把这个项目改变成不读取文件，而是只对内存中已有的数据进行diff&patch操作。
所以想要使用这样一组接口
`diff(const vector<BYTE> &oldData, const vector<BYTE> &newData, vector<BYTE> &diffData)`
`patch(const vector<BYTE> &oldData, const vector<BYTE> &diffData, vector<BYTE> &newData )`
在本项目中，对于diff函数可以很好地用create_diff来做转换。但是对于本项目中的patch函数，我观察到它需要指定`out_newData_end`，但这似乎需要先解析diffData才能获得到的。

**Comment by sisong** [comment]
patch的时候知道newSize的大小，是设计时约定的（而不是真的必须）：这是为了安全和更早的检查用户剩余空间。       
"这似乎需要先解析diffData才能获得到的"   是的，你可以在patch过程中，得知newSize的值的时候resize `vector<BYTE> &newData`;

**Comment by finch-yihe** [comment]
怎么解析diffData得到newData的大小？

**Comment by sisong** [comment]
看你用的什么补丁格式；类似 get？DiffInfo函数。
