### ISSUE TITLE
[hpatchz] Info about running hpatchz with gnu parallel 

### ISSUE THREAD

**Issue by wioo** [sisong/HDiffPatch#305]
Hi there.

This isn't an issue but question.

Does anyone know why bash for loop ex.
` for i in some filenames
do
hpatchz ...
done`

takes the same time (or even less) compared to 

`parallel -j0 hpatchz ... ::: (some filenames)`

Files are binaries, various sizes (up to few gigs),patch is lzma2 compressed

**Comment by sisong** [comment]
guess： disk I/O is the limit？

**Comment by wioo** [comment]
Good point.
So i guess there is no real benefit for using hpatchz with parallel. 

Thanks

**Comment by sisong** [comment]
if need patch faster，can try zstd compresser.
