### ISSUE TITLE
 hpatch: open diff File for read ERROR

### ISSUE THREAD

**Issue by smllys** [sisong/HDiffPatch#308]
android手机，利用so库完成patch。执行patch的时候报错 hpatch: open diff File for read ERROR。
patch文件在mac的命令行是可以完成合并

**Comment by sisong** [comment]
你是自己编译的so吗？ 还是我提供了？   
我猜测可能是补丁文件的访问权限问题    
如果你重新编译一个当前最新代码的so，错误信息里应该会log出为什么访问失败

**Comment by smllys** [comment]
你提供的so。patch文件放在了sdcard目录下面。我在设置里面已经把文件的读写权限打开了，在代码中也申请了读写权限

**Comment by sisong** [comment]
你重新编译一个so

**Comment by sisong** [comment]
我编译了新的so，见 [release](https://github.com/sisong/HDiffPatch/releases)
