### ISSUE TITLE
Streaming dir patch

### ISSUE THREAD

**Issue by Zeblote** [sisong/HDiffPatch#312]
Hi, is it possible to use the dir patch in streaming way? For example, when a large patch is being downloaded from the internet, and we could theoretically start applying the patch while the download is still in progress.

**Comment by sisong** [comment]
yes    
diff with -SD[-stepSize]   
note： patcher's version must >= 4.0.0

**Comment by Zeblote** [comment]
I see, do you have more details on how the patch could be passed to the library in chunks? It looks like the dir patch only has an api that accepts entire patch at once currently, but I might be missing something.

**Comment by sisong** [comment]
This is done using the interface abstraction of the dir patch parameter hpatch_TStreamInput* dirDiffData, for example:   
Assume that diffData is downloading in a thread and saved to the output file hpatch_TFileStreamOutput out_diff; one variable is always maintained during the download: the total amount of data currently written diff_writedBytes.     
Define a hpatch_TStreamInput in_diff to read data from out_diff(call out_diff.base.read_writed()); start the dir patch passing in the in_diff parameter, if in_diff.read() want reading data has not been downloaded yet, then blocking until it downloaded.    
Note: Thread safety is required when reading and writing out_diff file (e.g. using critical section).

**Comment by Zeblote** [comment]
I see, that sounds sensible to far. I'll report back if I have any troubles getting it to work!
