### ISSUE TITLE
How to create sfx ?

### ISSUE THREAD

**Issue by AliM1988** [sisong/HDiffPatch#320]
I don't know how to create SFX.
hpatchz [-X-exe#selfExecuteFile] diffFile -X#outSelfExtractArchive

What is selfExecuteFile ?

**Comment by sisong** [comment]
SFX  self extract archive: Combine the hpatchz executable file of the target platform and the diffFile into one executable file.   
"selfExecuteFile" is the  "hpatchz executable file of the target platform".

**Comment by AliM1988** [comment]
Thank you for your reply. 
As an example: 
```
set program="hpatchz.exe"
set patch="patch.hdiffz"
set selfpatch="patch.sfx.exe"

%program% -X-exe#%program% %patch% -X#%selfpatch%
```
I can't understand why we should repeat  %program% (hpatchz) while SFX creator and SFX executer is same?

**Comment by AliM1988** [comment]
In Windows `%program% %patch% -X#%selfpatch%` works fine!
Thank you.
