### ISSUE TITLE
关于Hdiff的一些疑问

### ISSUE THREAD

**Issue by LeviKing98** [sisong/HDiffPatch#323]
最近在学习差分算法，看了您的源码，由于个人水平不足，一些地方有困惑，想请教下前辈。

1. 请问getBestMatch()函数的内在逻辑是什么呢？请问是否是通过**newData**和**已排序的后缀字符串前缀**比较，基于二分法，找到到最佳位置，然后再进行相等字符的拓展匹配的？

2. 在您的博客（[https://blog.csdn.net/housisong/article/details/658863](url)）中，处理左斜线时，提到

> 如果a,b两个线段在一条直线上，并且间隔很小，则他们是可以优化的，优化方法是：把它们联接成一条直线段，中间的间隔部分对应的NewData数据同样需要放到PatchData中

- 若将差分包抽象成add、copy指令。请问此处Cover联结的收益体现在哪，是copy指令消耗吗？被联结Cover中间的不同字符串是否还需要用一条add指令表示？覆盖线优化策略对差分包大小的影响是否只在copy指令消耗（数量、地址、长度等），而对需要add的字符串无影响？基于我的理解，决定差分包大小的关键在于add字段的多少，那么关于copy指令的合并优化，最后对差分包大小的影响大吗？

3. 在处理左斜线时，您对左斜线集合L进行了排序，请问排序的第一（第二）关键词是什么？

4. 我对您的覆盖线查找及优化策略的理解是：查找、延长、合并，请问是否准确呢？查找最长的相同字符串前缀的起始位置，进行前后相等（相似？）拓展，再对Cover（左斜线集合L）进行排序，进行合并优化（解决独立、重叠、被包含、可联结的Cover）。

5. 我注意到您在_search_cover()函数中的getBestMatch()函数已经进行了向后的相等字符拓展，那么请问为什么需要在_dispose_cover()函数中extend_cover()里再次拓展，并且使用了kExtendMinSameRatio变量，这是否意味着后者的拓展允许存在不同字符？如果是，那要怎么处理拓展时出现的不同字符呢？

6. 在您的博客（[https://blog.csdn.net/housisong/article/details/126857706](url)）中，提到

> hash表的匹配也不够快，创建hash表的内存占用也不太可控；所以进行了替换：将old的块fadler64值(和其index)放在一个数组中，进行排序，然后用二分法查询；但这样fadler64值查找速度会从hash表的平均O(1)变成O(log(n))，所以在该查询之前再用一个bloom过滤器来预先降低大量的无效匹配。 这样处理后内存占用固定(即2个数组)，查询匹配速度也更快。

- 请问old的块fadler64值进行排序时，第一关键词是fadler64吗？为什么将其放在数组中内存占用即可固定？固定后的两个数组分别是什么？

7. 同时，在上条问题中的博客，您提到

> 可以将fadler64值按块顺序看成“字符串”进行字符串的查找和匹配。 对old的块fadler64值(和其index)的数组进行排序的时候，看作字符串进行排序，匹配的时候将new的多个连续块的fadler64值进行类字符串的搜索匹配。

- 请问是否是第一次时通过fadler64值查找，之后的字符串通过索引(index+1)进行查找？

8. 我注意到最后输出的数据有四块（cover_buf、ctrl_buf、code_buf、newDataDiff），请问各块的作用（内容）是什么？

9. 请问您是如何实现Patch过程，是按顺序进行add、copy操作吗？

10. 我注意到hpatch的合成速度非常快（相较其他算法），请问可能的原因是什么呢？

11. 相较其他算法，Hdiff的实验效果较突出，请问您认为该算法最具有特点的是哪方面呢？

问题有点多，希望不会给您带来困扰。
考虑到您的算法在差分算法领域具有的一定竞争力和优势，如果您能完善一些算法原理方面的文档，对诸如我等算法初学者将会是莫大的帮助。
感谢！

**Comment by sisong** [comment]
1. getBestMatch 是拿当前位置的new数据，在old后缀数组中查找最长的匹配，用的二分法查找，默认只需要检查2个位置，并返回匹配长度；   
其他复杂的代码大多和可选参数diffLimit的限制相关，用来保证查找到的匹配满足 diffLimit的要求。   

1. 覆盖线的合并优化收益：整体带来的差分包大小的影响不太大，如果是程序数据很多，那收益会稍好一些，如果其他数据较多，那收益很小。    
原因： 两条覆盖线合并成一条覆盖线后，需要输出的控制数据会减少一点，但更重要的是，存储差异数据时，程序数据中的大量地址值变动(sub减后)将变得更好压缩一些。   
覆盖线指令的额外处理： 还需要存储覆盖线描述的old数据和new数据的差值（sub数据），这会产生大量的0和少量的差值； 而不使用add指令，add指令这里仅用于存储覆盖线没有覆盖到的new数据。     

1. "左斜线集合L进行了排序"，  仅按照newPos排序。     
需要注意：blog中的方案(即公司内部版本)和开源的方案不同，blog中的方案是先寻找到所有可能的覆盖线，然后用算法选出一个可能的最好的覆盖线子集。   
而开源的方案为了内存占用和性能考虑，采用了贪婪算法：遍历new，仅在new的当前位置尽量找到一个可能是最好的覆盖线，然后跳过覆盖线长度的距离。    

1. "查找、延长、合并，请问是否准确呢？"  是的。 延长时允许少量比例的数据不同(-s模式当前没有使用延长)。    
"再对Cover（左斜线集合L）进行排序，进行合并优化（解决独立、重叠、被包含、可联结的Cover）" 这是blog中的算法； 开源版本没有这些处理。    

1. "getBestMatch()函数已经进行了向后的相等字符拓展"、"extend_cover()里再次拓展"     
 getBestMatch只是获得相等的长度，没有延长覆盖线；extend_cover中用kExtendMinSameRatio作为控制值来延长，允许少量比例的字符不同。   
这些不同的字符处理见上面提到的"覆盖线指令的额外处理"   

1. "第一关键词是fadler64吗"  是的, 查找都是用hash值为关键字来进行查找匹配。   
 "为什么将其放在数组中内存占用即可固定？固定后的两个数组分别是什么？"  old数据按blockSize大小分成小块，每一块保存一个fadler64值和其块序号index，这构成了一个(oldSize+blockSize-1)/blockSize大小的数组(假设叫OldBH)。new生成的fadler64值可以用二分法来查找该数组OldBH。    
 new生成的大量fadler64值都去查找，还是有点慢，所以对前面old的块fadler64值建立一个布隆过滤器(一个和fadler64个数成正比大小的数组)，只有布隆过滤器返回真时的fadler64值才继续在OldBH数组中二分查找。   
整体来看，将建立hash表(可能有多次内存申请)和查询hash表，替换成了2个数组来完成同样的功能，并且速度更快。   

1. "请问是否是第一次时通过fadler64值查找，之后的字符串通过索引(index+1)进行查找？"     
上面一条提到的数组OldBH，就是一个标准的后缀数组，它的排序和查询都是按照后缀字符串的算法来进行的。 一个"字符"是一个fadler64值,而不是常见的byte值；而它的下一个字符，是下一个块index+1的fadler64值。    

1. "数据有四块（cover_buf、ctrl_buf、code_buf、newDataDiff）"   
默认将补丁数据分成的4块来压缩，覆盖线本身一块； 覆盖线没有覆盖到的new数据一块；   
"覆盖线指令的额外处理"产生的sub数据，使用了rle算法来压缩，又将rle数据分成了ctrl数据和code数据分别储存。    
分成4路分别压缩，有利于优化压缩大小，但不能支持边下载边patch的特性；所以v4.0添加了新的单压缩流格式，重新组织4种数据的存储位置，按patch时用到的先后顺序交错放置到一起。   

1. "如何实现Patch过程，是按顺序进行add、copy操作吗？"    
patch过程其实比较简单的，按覆盖线拷贝old数据并加上sub数据，覆盖线没有覆盖到的new数据直接输出。   
如果数据都在内存中，那只需要很少量的代码就可以实现。 但这样内存占用不可控，需要流式实现。   
外部提供一块内存给patch(所有hpatch都不自己申请内存)，patch维护好各路数据流的状态来完成打补丁。 (hpatch_lite甚至可以支持在1KB内存设备中同时完成解压缩数据和打补丁)     

1. "hpatch的合成速度非常快（相较其他算法），请问可能的原因是什么呢？"    
好像也没有什么特别的算法:) 也没有使用什么特殊的CPU指令集，就是简单的一个实现，没有什么特别的技巧。   
hpatch的实现可以概括为在尽量节省内存的设计中实现了还不错的速度。

1. "Hdiff的实验效果较突出，请问您认为该算法最具有特点的是哪方面呢？"   
hdiff比较快，对很多可能慢下来的情况进行过优化，也能支持部分并行diff和并行压缩算法；-s模式能够处理特别巨大(比如50GB以上)的数据之间创建增量补丁。创建的补丁一般都比较小。

**Comment by LeviKing98** [comment]
感谢前辈的解答。我还有些问题想问前辈：

1. 我看到**difflimit**这个变量贯穿字符串匹配始终，但是默认值为0。在我测试的过程中，发现该变量好像一直没有改变，请问该变量的主要用处是什么，会对差分结果带来什么样的影响呢
2. 我看到**difflimit**类还包含了名为”listener“的函数变量，请问该函数的作用是什么呢
3. 在_search_cover函数中，先后进行了tryLinkExtend和tryCollinear函数。
`        if (tryLinkExtend(lastCover,matchCover,diff,diffLimit)){ // use link
          if (covers.size()==cover_begin)
              covers.push_back(lastCover);
          else
              covers.back()=lastCover;
      }else{ // use match
          if (covers.size()>cover_begin)//尝试共线;
              tryCollinear(covers.back(),matchCover,diff,diffLimit);
          covers.push_back(matchCover);
      }`
- 请问tryLinkExtend和tryCollinear函数的区别是什么呢？
`        inline bool isCanLink(const TOldCover& next)const{ // 覆盖线是否可以连接.
            return isCollinear(next)&&(linkSpaceLength(next)<=kMaxLinkSpaceLength);
        }
        inline bool isCollinear(const TOldCover& next)const{ // 覆盖线是否在同一条直线上.
            return cover_is_collinear(*this,next); // 两条指令新旧位置相对偏移一致
        }`
- 并且，请问isCanLink, isCollinear的区别是什么？
- 我看到isCollinear函数的作用是合并两条平行的sub指令，使sub指令能够包含该两条sub指令的中间add部分。因此我理解tryCollinear函数主要是去判断该情况并尝试合并指令
- 我看到tryLinkExtend函数的注释写的是_“尝试延长lastCover来完全代替matchCover”_，内部操作是对lastCover向后相同拓展，最终的结果是调整了lastCover.length，请问该操作是基于什么观察？既然每次生成Cover的时候已经进行了相同拓展，为什么要再次进行相同拓展，会有什么效果？对sub段或者对指令数量有什么影响？

4. _dispose_cover中的_select_cover中

- 注释里提到了单覆盖，请问是哪种情况？
- 我注意到在该函数中，主要进行link合并操作。此时所做的link合并操作与上面提到的tryLinkExtend是否相同？

5. 在getBestMatch函数中，通过
` TInt sai=sstring.lower_bound(newData,newData_end); `
函数已经获得的newData在src中的匹配位置，为什么不能直接拿来用，还要进行 matchDeep = 2 次数的循环，并设置 leftOk, rightOk, 两个变量，再进行两次相同匹配？请问leftOk, rightOk, 两个变量的功能是什么？

希望不会打扰到前辈

**Comment by sisong** [comment]
1. -m diff中difflimit参数的作用：寻找到覆盖线后，用difflimit可以选择不满意的线，要求重新寻找替代的覆盖线。   
该变量在 `create_*diff_block` 这些函数中有使用,用来优化对应的`create_*diff`函数的速度。 使用 difflimit来限制覆盖线不能跨越某些范围。   
2. "difflimit类还包含了名为"listener"的函数变量"  这是C代码中常用的策略，用来传递difflimit本身的值，相当于C++的this。   
3. 代码中我用 术语"collinear"共线，表示两条覆盖线段在同一条直线上； 术语"link"表示合并共线的两条覆盖线段成为一条覆盖线段。"try"的语义就是试试能不能共线或合并。   
4. 先尝试强制变线并link,发现不划算时，那保持共线也是不错的。    
5. "单覆盖" 的处理，当前算法选出了>=5长度的覆盖线数组，如果发现某覆盖线无法和其他覆盖线link，就需要单独保存，那很可能就需要比较长的线才会保存，否则就会删除太短的单独的覆盖线。   
6. "lower_bound  已经获得的newData在src中的匹配位置"  不是，C++的lower_bound语义是下边界，不是最长匹配； 但这个位置肯定在最长匹配旁边，所以"matchDeep = 2 次数的循环，并设置 leftOk, rightOk" 是为了在左右2边都找找。   difflimit!=0时，因为可能会否定一些不喜欢的匹配，所以需要加大matchDeep次数，但只要左右2边都各ok过一次，就算可以了。

**Comment by LeviKing98** [comment]
对于第3点，我的理解是在共线情况下，合并无疑是最优解，但是在不共线的情况下，可以尝试强行延长一条指令来涵盖下一条指令的大部分，并权衡损耗，如果强行延长能够减少损耗，则采取强行延长，否则不进行处理。
不知道是否准确

**Comment by sisong** [comment]
是的

**Comment by LeviKing98** [comment]
好的，谢谢前辈的解答！
