### ISSUE TITLE
ZSTD 搞了个 --patch-from 功能，也可以实现 diff+patch ，希望能加入到对比中。

### ISSUE THREAD

**Issue by byronhe** [sisong/HDiffPatch#326]
https://github.com/facebook/zstd/wiki/Zstandard-as-a-patching-engine

**Comment by sisong** [comment]
对比测试中已经添加了`zstd --patch-from`，见[readme](https://github.com/sisong/HDiffPatch/edit/master/README.md)   
本次也更新了程序和源码测试用例，apk测试用例不变；  zstd效果不错，就是内存占用方面有点大。
