### ISSUE TITLE
关于报错

### ISSUE THREAD

**Issue by able1214** [sisong/HDiffPatch#328]
![V6%ZQM2XX3VYWEEM0OKQ20R](https://user-images.githubusercontent.com/32001378/209222570-c1921d76-e402-4c94-b95c-c21b9e3b36ae.png)
请问这个报错应该怎么解决？翻了下其他的issue也没看到相同的问题。
我也尝试用了下-s参数，包括默认的和其他几个推荐的值，结果就是虽然没有最后一行的报错，但也没有成功的信息，而且生成的差分文件都是一模一样的1点几m的文件。

**Comment by sisong** [comment]
调用 malloc 失败， 说明内存不足。      
hdiffz默认-m，当处理的文件特别大(30GB)时需要的内存非常巨大(256GB以上)；  只能使用 -s；    
如果默认的-s-64运行内存还不够(需要约 30GB*16/64)，可以加大参数，比如 -s-1k 试试能否成功；   
然后尝试减小该参数(并推荐添加-c压缩）并来获得更小的补丁。

**Comment by able1214** [comment]
16,32,48,1k,64k,1m都试过都不行。。。我只有16g内存有什么推荐的参数吗？

**Comment by sisong** [comment]
这肯定不是内存不够的原因了。   
你把程序输出信息放出来看看，在哪个步骤出错的

**Comment by able1214** [comment]
![D) X ~FB `3KWW_9 BF`5NE](https://user-images.githubusercontent.com/32001378/209301756-5e1a0fca-afe3-422f-9346-d0c516115852.png)
这是用1k的结果，啥报错都没，大概过了几十秒就没了，输出的文件只有1.39m
![B~DWOCKDGBE76KR CIWKEVU](https://user-images.githubusercontent.com/32001378/209301917-58e005a6-6380-4b36-a29d-6f653940305d.png)

**Comment by sisong** [comment]
没有正常结束。   看起来是出了异常，程序直接退出了

**Comment by able1214** [comment]
[旧文件](https://fitgirl-repacks.site/monochrome-mobius-rights-and-wrongs/) 安装时选繁体中文，安装完后不包括Redist文件夹和unins000.dat、unins000.exe 2个文件
![M_GVEAOXL3@GFDR$}I2~GHA](https://user-images.githubusercontent.com/32001378/209416152-1c1b92fb-2821-468a-9327-5768220a86df.png)

[新文件](https://collections.lilithraws.org/posts/%E9%BB%91%E7%99%BD%E8%8E%AB%E6%AF%94%E7%83%8F%E6%96%AF-%E6%AD%B2%E6%9C%88%E7%9A%84%E4%BB%A3%E5%83%B9/) 里面带base的和cht的压缩文件，下载完整合在一起
![0~SX7`21`~TV~OBOCLY$EQY](https://user-images.githubusercontent.com/32001378/209416161-f6ac87be-3fc6-4f66-8ff7-ea3de1da6084.png)

**Comment by sisong** [comment]
好的 Thanks   
下载中

**Comment by sisong** [comment]
复现了该问题，猜测**diff -s**时存在一个**多线程**bug   
关闭多线程后，diff执行正常：
```
$ hdiffpatch_v4.5.1_bin\windows64\hdiffz.exe old new h.pat -s-64 -f -p-1
oldDir : "old\"
newDir : "new\"
outDiff: "h.pat"
hdiffz run dir diff with compress plugin: ""
hdiffz run dir diff with checksum plugin: "fadler64"


DirDiff old path count: 6460
        new path count: 6484 (fileCount:5993)
       same file count: 27 (dataSize: 16853868)
    ref old file count: 5942
   diff new file count: 5966

run hdiffz:
  oldRefSize  : 29304350486
  newRefSize  : 29966454901 (all newSize: 29983308769)
  diffDataSize: 4443688811
  diff    time: 710.116 s

diffDataSize  : 4445154104
dir  diff time: 775.737 s
  out dirDiffFile ok!

load dirDiffFile for test by patch check:
diffDataSize  : 4445154104
dir patch time: 198.141 s
  patch check diff data ok!

all   time: 973.964 s
```

**Comment by able1214** [comment]
成功了，谢谢！
这个bug修复以后，是不是就不用-p参数了？

**Comment by sisong** [comment]
"这个bug修复以后，是不是就不用-p参数了？" 是的    
 问题已经找到，并随后会发布新版本       
    
另外，你也可以添加**-c**参数来输出压缩的补丁，推荐 `-c-zstd`

**Comment by sisong** [comment]
@able1214  我注意到一个问题，我们两个人得到的文件数目对不上，这是一个严重的问题: 如果不能保证一样，应用补丁的时候会错误。
