### ISSUE TITLE
7-zip压缩后的文件再diff效果很差，想请教一下原因以及优化思路，多谢

### ISSUE THREAD

**Issue by weijuncheng-150622** [sisong/HDiffPatch#330]

**Comment by sisong** [comment]
大多数压缩算法压缩后的数据一般来说对于diff算法都不友好，建议为对解压缩后的数据执行diff。     
比如现在的apkdiffpatch和sfpatcher库，都是针对压缩的zip文件格式专门进行的优化：就是diff前先解压缩old和new数据，patch时重新还原压缩得到new。

**Comment by weijuncheng-150622** [comment]
> 大多数压缩算法压缩后的数据一般来说对于diff算法都不友好，建议为对解压缩后的数据执行diff。 比如现在的apkdiffpatch和sfpatcher库，都是针对压缩的zip文件格式专门进行的优化：就是diff前先解压缩old和new数据，patch时重新还原压缩得到new。

就是担心在手机移动端做重新压缩工作的内存和耗时成本会不会难以接受，特别是针对7zip这种相对比较极致的压缩算法而言，可能需要测一下，非常感谢

**Comment by sisong** [comment]
. 如果为了还原压缩的速度，可以考虑：增大补丁包大小来换取压缩还原速度的优化策略。      
. 对于lzma格式，猜测也许并行压缩得到的数据更有利于diff一些？

**Comment by weijuncheng-150622** [comment]
> 

嗯嗯，第一点我们正在考虑；关于第二点，并行压缩指的是什么呢，有没有什么可以参考的资料呢？ 7zip似乎不提供并行压缩的能力，是否有推荐的并行压缩方案，其压缩效果是否和7zip差距不大呢？

**Comment by sisong** [comment]
“增大补丁包大小来换取压缩还原速度”  这只是一个优化思路，具体如何操作需要具体问题具体分析； 比如压缩速度很慢，可能绝大部分时间在搜寻最佳匹配位置，那我是否可以用一个更快的搜索算法(比如zstd)替代（2个算法得到的位置不同时，需要添加额外信息）。   
“ 7zip似乎不提供并行压缩的能力”  7zip是支持并行压缩的（和选择的压缩算法有关）

**Comment by weijuncheng-150622** [comment]
> “增大补丁包大小来换取压缩还原速度” 这只是一个优化思路，具体如何操作需要具体问题具体分析； 比如压缩速度很慢，可能绝大部分时间在搜寻最佳匹配位置，那我是否可以用一个更快的搜索算法(比如zstd)替代（2个算法得到的位置不同时，需要添加额外信息）。 “ 7zip似乎不提供并行压缩的能力” 7zip是支持并行压缩的（和选择的压缩算法有关）

非常感谢，经过这几天的调研，可能优先选择压缩速度更快的压缩算法，通过牺牲一部分原包压缩效果来进行处理，如果不可行的话，再尝试你这边的第一个思路
