### ISSUE TITLE
Multi threading doesn't seem to work?

### ISSUE THREAD

**Issue by DarkShadow44** [sisong/HDiffPatch#331]
I'm trying to use `create_single_compressed_diff` to create a diff. But even if I increase `threadNum`, it doesn't seem to use more than one CPU core.

Is there a way to increase the speed by running it in parallel?

```
#include "libHDiffPatch/HDiff/diff.h"
#include <fstream>
#include <iterator>

int main()
{
    std::ifstream file_in1("in1.zip", std::ios::binary);
    std::ifstream file_in2("in2.zip", std::ios::binary);
    std::vector<unsigned char> contents_in1((std::istreambuf_iterator<char>(file_in1)), std::istreambuf_iterator<char>());
    std::vector<unsigned char> contents_in2((std::istreambuf_iterator<char>(file_in2)), std::istreambuf_iterator<char>());
    std::vector<unsigned char> out;
    create_single_compressed_diff(
        &contents_in2[0], &contents_in2[0] + contents_in2.size(),
        &contents_in1[0], &contents_in1[0] + contents_in1.size(),
        out,
        0, kMinSingleMatchScore_default, kDefaultPatchStepMemSize, false, 0, 8);
    
    std::ofstream output_file("out.diff");
    std::ostream_iterator<unsigned char> output_iterator(output_file);
    std::copy(out.begin(), out.end(), output_iterator);
    return 0; 
}
```

**Comment by sisong** [comment]
It is possible that the data is too small，The startup conditions for using parallelism were not met.      
if need to up speed，you  can try func `create_single_compressed_diff_block()` .

**Comment by DarkShadow44** [comment]
Thanks for the reply, that does make it much faster (2x). The data I'm using is 686MB and 689MB, the time is 24s. It seems to do a little multi-threading, but not much. It's still mostly using one CPU, even if I say 8 threads. Is that intentional?

**Comment by sisong** [comment]
`a little multi-threading, but not much`   Parallelism is related to the characteristics of the input data.

**Comment by DarkShadow44** [comment]
It's about 23s. Slightly slower than `hdiffz  {old} {new} {pat}  -f` (20s).

**Comment by sisong** [comment]
The difference run time may be due to the parameter` isUseBigCacheMatch`  (cmdline set `-cache`)
