### ISSUE TITLE
在编译 iphoneos 平台时，出现报错，要怎么解决呢？

### ISSUE THREAD

**Issue by ilinchunjie** [sisong/HDiffPatch#333]
编译工具：xmake
编译配置：
target("hpatch")
    set_kind("static")
    add_files("src/**.c")
    set_languages("c99", "c++11")

error: fatal error: error in backend: Cannot select: intrinsic %llvm.aarch64.crc32w
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: 
********************
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/nr/g3nm2bzd66v5btm6h5_kp_7h0000gn/T/7zCrc-06d366.c
clang: note: diagnostic msg: /var/folders/nr/g3nm2bzd66v5btm6h5_kp_7h0000gn/T/7zCrc-06d366.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/linchunjie/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg:

**Comment by sisong** [comment]
`add_files("src/**.c")`   不太好，会添加不必要的文件； 你借鉴一下 `https://github.com/sisong/HDiffPatch/blob/master/builds/android_ndk_jni_mk/Android.mk` 和 `https://github.com/sisong/HDiffPatch/blob/master/Makefile`

**Comment by ilinchunjie** [comment]
我这边的 xmake 工程已经去除了大部分没必要的脚本，仅保留 patch 的相关源码和 lzma 库，如果我不引入 lzma 库，能正常编译和使用；如果引入 lzma 库（以源码的形式），使用 set_toolchains("clang") 也能正常编译，但是导入 xcode 工程打包时，会出现 Undefined symbols for architecture arm64：_hpatchz

**Comment by ilinchunjie** [comment]
在其他库里，我有看到一样的报错，不知道是否有帮助
https://github.com/android/ndk/issues/1568

**Comment by sisong** [comment]
mac下我一般用 make和xcode编译，没有用过xmake   
用搜索引擎搜索`Undefined symbols for architecture arm64`试试
