### ISSUE TITLE
关于 compress_plugin_demo.h 文件的疑惑

### ISSUE THREAD

**Issue by StephQAZ** [sisong/HDiffPatch#334]
作者您好，我在尝试阅读HDiffPatch源码时存在困惑。在compress_plugin_demo.h文件中，存在_zlib_compress()函数，按照我的理解，该函数是作为使用zlib库压缩差分包的plugin。在_zlib_compress()中，存在着_zlib_compress_part()函数，请问这函数的具体含义是什么，为什么它需要将数据部分压缩呢？

如果您能回复，不甚感激。

**Comment by sisong** [comment]
你应该搜索一下`_zlib_compress_part`的使用情况，会发现被`_zlib_compress`在一个循环中所调用。
