### ISSUE TITLE
支持原地更新吗

### ISSUE THREAD

**Issue by gneworld** [sisong/HDiffPatch#335]
大佬您好，请问现在支持原地更新了吗，支持的话对应哪几个接口调用呢，谢谢

**Comment by sisong** [comment]
没有支持

**Comment by wangchz13** [comment]
@gneworld 原地更新我已经实现了，并且移植到嵌入式设备了，见我主页

**Comment by sisong** [comment]
刚给 单片机项目 [HPatchLite](https://github.com/sisong/HPatchLite) 添加了2种最简单的原地更新方案 ；
