### ISSUE TITLE
Using hdiff as a library with compression

### ISSUE THREAD

**Issue by q-bertsuit** [sisong/HDiffPatch#336]
Hi,

I'm trying to use hdiff patch in a C++ project, but I'm having trouble replicating what I am able to do with the command line tool.

This is what I am trying to replicate:

.\hdiffz.exe -m-6 -SD -d -f -p-1 -c-lzma2-9-16m .\old.txt .\new.txt patch.tar

I was able to use the library like this:

```
    std::ifstream newFile("new.txt", std::ios::binary);
    std::ifstream oldFile("old.txt", std::ios::binary);

    // read the data from the files into vectors
    std::vector<unsigned char> newVector((std::istreambuf_iterator<char>(newFile)),
        std::istreambuf_iterator<char>());
    std::vector<unsigned char> oldVector((std::istreambuf_iterator<char>(oldFile)),
        std::istreambuf_iterator<char>());

    std::vector<unsigned char> out_diff;

    // create a patch from oldData to newData
    create_diff(&newVector[0], &newVector[0] + newVector.size(),
        &oldVector[0], &oldVector[0] + oldVector.size(),
        out_diff, kMinSingleMatchScore_default, false, 1);

    // apply the patch to oldData to get newData
    std::vector<unsigned char> newData_patched(newVector.size());
    unsigned char* newData_patched_end = newData_patched.data() + newData_patched.size();
    patch(newData_patched.data(), newData_patched_end,
        &oldVector[0], &oldVector[0] + oldVector.size(),
        out_diff.data(), out_diff.data() + out_diff.size());
```

but no luck with the create_single_compressed_diff_block since it needs a compression plugin etc. Any tips for a complete noob on how to proceed?

Thanks!

**Comment by sisong** [comment]
you can used `lzma2CompressPlugin` in `HDiffPatch\compress_plugin_demo.h`

**Comment by q-bertsuit** [comment]
Thanks! Will the patch size be just as small if I create an uncompressed patch using the patch() function, then manually compress it, compared to using create_single_compressed_diff_block?

**Comment by sisong** [comment]
"patch size be just as small"   yes， same size，you can do it.

**Comment by q-bertsuit** [comment]
Thanks again, really appreciate it! Sorry, one last question. If I want to use the create_diff() and patch() functions in my own C++ project, I need to include a lot of files, not only diff.h/cpp and patch.h/cpp? Im struggeling with a lot of compile errors and trying to include many different files

**Comment by sisong** [comment]
Add  lib source code directory

**Comment by q-bertsuit** [comment]
Sorry for being such a noob.. I cant figure this out... So if I create a new C++ console app in VS, do I then have to go to Properties -> C/C++ -> General -> Additional Include Directories and add the path to libHDiffPatch?

**Comment by sisong** [comment]
for patch, only need `HDiffPatch\libHDiffPatch\HPatch\patch.c`;      
for diff, need all C\CPP files in 'HDiffPatch\libHDiffPatch\';   
you can open `HDiffPatch\builds\vc2019\HDiffPatch.sln` by VC++, as an example of reference;
