### ISSUE TITLE
hpatch: open oldFile for read ERROR!

### ISSUE THREAD

**Issue by sitJac** [sisong/HDiffPatch#337]
When calling the hpatch interface, an error is reported saying "open oldFile for read ERROR!" The file permissions are sufficient. Is there any restriction on the type of file, and does it support reading block device files?
```bash
brw-rw----   1 root      root         1,  45 Jan 01  1970 uda0.8E2F94FF-389A-4B97-A0D3-A13B5CEC7C36.35
```
![image](https://user-images.githubusercontent.com/46061424/230531904-9a3a1671-b0d3-4db9-8d8b-d570465b488b.png)

![image](https://user-images.githubusercontent.com/46061424/230605668-1802a151-9a45-4c21-b5a9-338bc114f70e.png)

**Comment by sisong** [comment]
What is the hpatch version?    The new hpatchz cmdline will report why an error occurred when calling the file API failed.      
hpatch default used fopen()\fread to access oldFile, you can used other file API do this.

**Comment by sitJac** [comment]
> 

 I will try again with the latest version of hpatch code and provide more information later, thx.

**Comment by sitJac** [comment]
I'm trying to chang 'fopen' to 'open' in the function '_import_fileOpenByMode' to read this type of file:
```C
#define __S_IFBLK   0060000 /* Block device.  */

hpatch_FileHandle _import_fileOpenByMode(const char* fileName_utf8,const char* mode){
    printf("fileName_utf8:%s\n", fileName_utf8);
    int fd = open(fileName_utf8, O_RDWR | O_CREAT, 0666);
    printf("fd is %d\n", fd);
    if (fd < 0) {
        perror("open");
        return NULL; // or other error handling
    }
    FILE* fp = fdopen(fd, "r+");
    if (!fp) {
        printf("fdopen\n");
        close(fd);
        return NULL; // or other error handling
    }
    printf("fdopen success\n");
    return fp;
    // return fopen(fileName_utf8,mode); 
}
```
But when I run hpatchz for this type of file, I get the error message 'patch run ERROR!', and the patch_result is 11 (HPATCH_HPATCH_ERROR), so does hpatchz support the file API 'open', or is my file type too special to support hpatchz 😢

**Comment by sitJac** [comment]
> What is the hpatch version? The new hpatchz cmdline will report why an error occurred when calling the file API failed. hpatch default used fopen()\fread to access oldFile, you can used other file API do this.

I'm trying to chang 'fopen' to 'open' in the function '_import_fileOpenByMode' to read this type of file:
```C
#define __S_IFBLK   0060000 /* Block device.  */
```
```C
hpatch_FileHandle _import_fileOpenByMode(const char* fileName_utf8,const char* mode){
    printf("fileName_utf8:%s\n", fileName_utf8);
    int fd = open(fileName_utf8, O_RDWR | O_CREAT, 0666);
    printf("fd is %d\n", fd);
    if (fd < 0) {
        perror("open");
        return NULL; // or other error handling
    }
    FILE* fp = fdopen(fd, "r+");
    if (!fp) {
        printf("fdopen\n");
        close(fd);
        return NULL; // or other error handling
    }
    printf("fdopen success\n");
    return fp;
    // return fopen(fileName_utf8,mode); 
}
```
But when I run hpatchz for this type of file, I get the error message 'patch run ERROR!', and the patch_result is 11 (HPATCH_HPATCH_ERROR), so does hpatchz support the file API 'open', or is my file type too special to support hpatchz? 😢

**Comment by sisong** [comment]
> file type too special to support hpatchz     

The API has nothing to do with the file type and may not even be a file. All that is required is that the old data can be accessed randomly.      
You can set the value of hpatch_TStreamInput yourself and call the patch API directly.

**Comment by sitJac** [comment]
Ok, here is the solution: The stat(path_utf8, &s) method cannot get the size of block files. I set the size of this type of file's out_fileSize to a default value(0x100000000) and turned off check_on_error(HPATCH_FILEDATA_ERROR), and then hpatchz work correctly!!!"
```C
   if ((s.st_mode&S_IFMT)==S_IFBLK){
        *out_type=kPathType_blk;
        printf("s.st_size = %llu\n", *s.st_size);
        if (out_fileSize) *out_fileSize=0x100000000;
        if (out_st_mode) *out_st_mode=s.st_mode;
        return hpatch_TRUE;
    }
```
```C
    if (poldData->streamSize!=diffInfo.oldDataSize){
        printf("oldFile dataSize %" PRIu64 " != diffFile saved oldDataSize %" PRIu64 " ERROR!\n",
                poldData->streamSize,diffInfo.oldDataSize);
	 poldData->streamSize = diffInfo.oldDataSize;
        //check_on_error(HPATCH_FILEDATA_ERROR);
    }
```
```bash
New patch file exist and deleted.
old : "/dev/disk/uda0.8E2F94FF-389A-4B97-A0D3-A13B5CEC7C36.35"
diff: "la_boot_diff"
out : "la_boot_patch2"
oldDataSize : 67108864
diffDataSize: 8244903
newDataSize : 67108864
  patch ok!

hpatchz time: 0.485 s
```
