### ISSUE TITLE
Use error codes instead of _hpatch_FALSE

### ISSUE THREAD

**Issue by Kromster80** [sisong/HDiffPatch#338]
It would help a lot to debug issues if return values were more meaningfull than just 0 and 1.

**Comment by sisong** [comment]
patch result hpatch_FALSE： usually it's  files access error (which you can catch), or the diffFile's data error.       
If you want to debug code, you can try the change the code  `__hpatch_debug_check_false_x` , which redefined _hpatch_FALSE (that's how I debug code).

**Comment by Kromster80** [comment]
I have changed the code in my mini-fork to `return hpatch_FALSE + 101`,  `return hpatch_FALSE + 102`,  `return hpatch_FALSE + 103` ... it is quite handy (cos I use the lib as DLL) and gives me exact error location.

**Comment by sisong** [comment]
you can define  0 is name ok, all other error code define a name, all result code is a enum type.

**Comment by sisong** [comment]
I don't think it's needed (result type changed to int), so I won't recode it.    
> **patch result hpatch_FALSE： usually it's files access error (which you can catch), or the diffFile's data error.**
