### ISSUE TITLE
option to use hard links with hpatch

### ISSUE THREAD

**Issue by Ost3rbaer** [sisong/HDiffPatch#339]
It would be nice if we can avoid to copy same files upon creation of a patched output directory on the same file system as the source, i.e. use the functions link(2) on POSIX platforms (Linux/Android/OSX) and  the CreateHardLinkA function (https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createhardlinka) on Windows platforms.

This has the potential of drastically reduce patch time and disk space requirements when only a subset of files in a larger project changes.

**Comment by sisong** [comment]
yes, you can do that.      
dir patch  setp 1: patch new files & changed old files to dst dir.  step 2: copy same old files to dst dir.      
note func: `_copySameFile()` read old file's data copy to new file,   `_tempDir_copySameFile()` only readed old file's data (for cheecksum)    
  
other： linked file is safe?   edit old file, will the new file be changed or copied?

**Comment by sisong** [comment]
"This library does not deal with file metadata"   
I don't want to support link files, you can extend this library youself if needed.

**Comment by sisong** [comment]
"This library does not deal with file metadata"
I don't want to support link files, you can extend this library youself if needed.
