### ISSUE TITLE
hdiffz newDataSize is zero but the actual size is 193KB

### ISSUE THREAD

**Issue by swcumt** [sisong/HDiffPatch#340]
run the hdiffz in program concurrency,  with several hdiffz process, the command is 
`hdiffz -c-zstd /data/tmp/statusoutpackage_assets_all_1.bundle /data/tmp/statusoutpackage_assets_all_2.bundle /data/tmp/patch/test.patch`
with the log below:
`old : "/data/tmp/statusoutpackage_assets_all_1.bundle"
new : "/data/tmp/statusoutpackage_assets_all_2.bundle"
out : "/data/tmp/patch/test.patch"
hdiffz run with compress plugin: "zstd"
oldDataSize : 128417
newDataSize : 0
diffDataSize: 26
diff    time: 0.038 s
  out diff file ok!

load diffFile for test by patch:
diffDataSize: 26
patch   time: 0.000 s
  patch check diff data ok!

all   time: 0.038 s`
generate wrong patch

**Comment by swcumt** [comment]
HDiffPatch::hdiffz v4.4.2

**Comment by sisong** [comment]
> oldDataSize : 128417
newDataSize : 0

I don't know why hdiffz couldn't get the size of the newfile, but the size of the oldfile is correct； them are same func.      
You can try to  update hdiffz to v4.5.2, test this case:  https://github.com/sisong/HDiffPatch/releases

**Comment by swcumt** [comment]
I run several hdiffz processes at the same time, does this matter?

**Comment by swcumt** [comment]
upgrade to v4.5.2 has the same info

**Comment by sisong** [comment]
test：$hdiffz new old pat   
test:  $copy new to new2     $hdiffz old  new2 pat

**Comment by swcumt** [comment]
it solved by change the generated patch path to dir which named by the filename. Like the example, change the patch to **/data/tmp/patch/statusoutpackage_assets_all/1_2.patch**, the problem disappeared.
The problem appear when lots of patch at the same dir

**Comment by sisong** [comment]
It is correct to output different patch filenames when parallel diffs.
