### ISSUE TITLE
Android ndk build error

### ISSUE THREAD

**Issue by wangshaolei** [sisong/HDiffPatch#350]
Hi，
    ./build_libs.sh
[armeabi-v7a] Compile thumb  : hpatchz <= hpatch.c
In file included from ././hpatch.c:13:
In file included from ./../../hpatchz.c:98:
./../../decompress_plugin_demo.h:406:13: fatal error: 'LzmaDec.h' file not found
#   include "LzmaDec.h" // "lzma/C/LzmaDec.h" https://github.com/sisong/lzma
            ^~~~~~~~~~~
1 error generated.
make: *** [/Users/lei/Library/Android/sdk/ndk/25.2.9519653/build/core/build-binary.mk:422: obj/local/armeabi-v7a/objs/hpatchz/./hpatch.o] Error 1

i need help, thanks

**Comment by sisong** [comment]
try
```
cd <path>/HDiffPatch          
git clone --depth=1 https://github.com/sisong/lzma.git ../lzma
git clone --depth=1 https://github.com/sisong/zstd.git ../zstd
cd HDiffPatch\builds\android_ndk_jni_mk
./build_libs.sh
```

**Comment by wangshaolei** [comment]
> try
> 
> ```
> cd <path>/HDiffPatch          
> git clone --depth=1 https://github.com/sisong/lzma.git ../lzma
> git clone --depth=1 https://github.com/sisong/zstd.git ../zstd
> cd builds/android_ndk_jni_mk
> ./build_libs.sh
> ```

thanks, i'll try it

**Comment by wangshaolei** [comment]
> HDiffPatch

thanks,
[arm64-v8a] SharedLibrary  : libhpatchz.so
[arm64-v8a] Install        : libhpatchz.so => libs/arm64-v8a/libhpatchz.so
it solved.
