### ISSUE TITLE
Make it possible to compile the library without using C++ exceptions

### ISSUE THREAD

**Issue by JohnAlcatraz** [sisong/HDiffPatch#354]
I would like to use this library in a project that is compiled with `-fno-exceptions`. Unfortunately this library cannot be compiled in such a project at the moment, since this library uses try/catch/throw and there does not appear to be any #define to disable the exceptions globally for this library.

**Comment by sisong** [comment]
all patch code only used C, but diff code used C++ & used exceptions

**Comment by JohnAlcatraz** [comment]
Could you add a `#define NO_EXCEPTIONS` that disables the exceptions in the diff code, so that it can be compiled successfully with `-fno-exceptions`?

**Comment by sisong** [comment]
That require too many code changes
