### ISSUE TITLE
iOS项目使用的产物

### ISSUE THREAD

**Issue by Tommywangh** [sisong/HDiffPatch#355]
有iOS项目使用的产物，用macos的报错

**Comment by sisong** [comment]
有什么错误可以发上来？   
使用场景是如何的？ （比如是否需要diff？是否需要压缩？单文件？）   
iOS上建议直接将需要的C\C++源代码文件添加到项目中使用。   
可以借鉴： `HDiffPatch\builds\xcode\HDiffPatch.xcworkspace`

**Comment by Tommywangh** [comment]
1.HDiffPatch\builds\xcode\HDiffPatch.xcworkspace这个我编译mac os没问题，切换成iOS报错，
<img width="396" alt="image" src="https://github.com/sisong/HDiffPatch/assets/24494975/1ce5f68e-5794-4d57-b441-a62a671776b8">
2、使用场景就是用来合并zip包，用patch能力。

**Comment by sisong** [comment]
这两天我会尝试更新一个版本，发布iOS的静态库

**Comment by Tommywangh** [comment]
太棒了，期待，Android这边已经用so试过了，zip的合并速度和patch大小确实比BsDiff有优势

**Comment by sisong** [comment]
@Tommywangh 
 我上传了iOS的测试SDK，你可以试试看： 
https://github.com/sisong/HDiffPatch/releases/tag/v4.6.6-test-iOS-static-lib

**Comment by Tommywangh** [comment]
好的，收到~

**Comment by Tommywangh** [comment]
> 

<img width="498" alt="image" src="https://github.com/sisong/HDiffPatch/assets/24494975/2db76bbf-37b6-4851-99ff-01b1eb48d844">
这个.a不包含libmd5、lzma、zstd这些嘛，.a引入工程会报错

**Comment by Tommywangh** [comment]
是在build里打出来的产物，只把.a和两个.h拖入，会报符号表的错误

**Comment by sisong** [comment]
libbz2 库需要自己添加到项目中。 lzma那个缺失是个问题

**Comment by Tommywangh** [comment]
是用的最新的 我再试一下 用的真机版本

**Comment by Tommywangh** [comment]
<img width="276" alt="image" src="https://github.com/sisong/HDiffPatch/assets/24494975/772b794f-5036-4944-be72-ed3a59a456fe">
这是拖入项目的SDK，还是报错：hpatchz/libbz2.a(blocksort.o), building for iOS, but linking in object file built for macOS, file 'hpatchz/libbz2.a' for architecture arm64

**Comment by sisong** [comment]
libbz2 库需要自己添加到项目中。 lzma那个缺失是个问题

**Comment by sisong** [comment]
关于libbz2库    
你试试从项目 TARGETS 的 Build Phases  -> Linked Framework and Libraries 中用 + 添加名称 libbz2.tbd

**Comment by Tommywangh** [comment]
libbz2.tbd这个我拉libbz2没看到有这个，可以出一个空工程的接入嘛iOS这块，方面加个wx或者群嘛我跟您请教下

**Comment by sisong** [comment]
我发布了新版本  https://github.com/sisong/HDiffPatch/releases/download/v4.6.7/hdiffpatch_v4.6.7_bin_iOS_SDK_hpatchz.zip

可以给我发邮件，地址见readme中的最后留的联系人地址
