### ISSUE TITLE
Is there a way to patch old directory without making new temporary one.

### ISSUE THREAD

**Issue by beastburst** [sisong/HDiffPatch#356]
I have a very big old dir that I have created patch file for it.
However all the time when patching it creates new tmp dir than it removes the old and renames the new tmp dir to match the name of the old dir.

Is there a way to patch directly the old dir without creating new tmp directory and the follow up procedures of deletion and renaming ?

**Comment by sisong** [comment]
patch to same dir, have 2 step (see `tempDirPatchListener`):
1. step: patch all modified & added files to tmp dir; (slow & revocable&safe process)
1. step: merge tmp dir to old dir; (fast & irrevocable process)

If you don't want a tmp dir for save disk space, you can creating multiple diffFiles and customizing the patch process by yourself.

**Comment by beastburst** [comment]
What does that mean "If you don't want a tmp dir for save disk space, you can creating multiple diffFiles and customizing the patch process by yourself." ?

I have to create a patchfile for every file that was changed in the dir ?

If so I have a question. Does patching a file create new tmp file or it directly patches the old file ?
