### ISSUE TITLE
Question on applying a patch onto the same partition

### ISSUE THREAD

**Issue by Kevin-gluck** [sisong/HDiffPatch#361]
Hi, 

I'm trying to use this library to patch one of my embedded device's file which is usually bigger than 1GB with small memory(RAM) footprint, eg ~1GB.
I'd like to know if following is possible;
1. make patch file delta.hdiff for src.img -> target.img on the host machine
2. download delta.hdiff to embedded device
3. apply patch delta.hdiff to src.img directly (meaning, I cannot make new target.img in the device because of storage limitation)

Also, I'd like to know how much RAM are required during patching.
To be more specific, what is the value of "decompress buffer size"

Thanks in advance.

**Comment by sisong** [comment]
> I cannot make new target.img in the device because of storage limitation   
   
now, hdiffpatch not support inplace-patch.

**Comment by Kevin-gluck** [comment]
Thanks for update.
One more question, can I know if this library is being used on any well known product or device, eg AOSP ?

**Comment by sisong** [comment]
hdiffpatch is heavily used: at least than 10 apps with more than 100 million users, used hdiffpatch.

**Comment by Kevin-gluck** [comment]
Thanks for comments.

**Comment by sisong** [comment]
I just added two simplest inplace-patch solutions to the  [HPatchLite](https://github.com/sisong/HPatchLite) project. You can check whether they meet your needs.   
There is an actual MCU project developed with it, and the effect is pretty good.
