### ISSUE TITLE
hdiffz fail with long path file

### ISSUE THREAD

**Issue by florian-gandon** [sisong/HDiffPatch#363]
Hello !

I've the following error when generating a patch file.

> call import system api error! errno: 2, errmsg: No such file or directory.
> dir diff run an error: open file "c:\#################################################################################################################################################################################################################################################################" error! ERROR!

(I've replaced the path for privacy reason.)
The path is 261 characters long for one of the file in the folder. It is working when it is shorter. I think less or equal to 256.

Is it a know issue ? Is there a way to avoid such except reducing the path ?

**Comment by sisong** [comment]
What OS are you running on?
   
now, the maximum length of file path supported by hpatchz is 2KB.

**Comment by florian-gandon** [comment]
Hi !

I forgot to mention. It is Windows 10. I'm using the windows64 version.
I guess this is the well known Windows issue when length is more than 260 characters.
I thought it was supposed to be fixed in newer versions especially the 64bits one. I've checked the Windows Registry. It is supposed to be activated.
Also, I tried with relative path but I've the same issue.

I'm not actually sure we can fix it in Hdiff.

Regards,
Florian

**Comment by florian-gandon** [comment]
I'm not that of an expert in C or C++ but it seems there are solutions like the one described [there](https://stackoverflow.com/a/6831683).
Not sure how easy it is to implement for Hdiff.

**Comment by sisong** [comment]
Thank you for your new info, I've fixed this issue, and a new version will be released soon.

**Comment by florian-gandon** [comment]
Thank you !
I see only the version upgrade linked to this issue. I would be interested to know how it was fixed.

**Comment by sisong** [comment]
need re download cmdline from https://github.com/sisong/HDiffPatch/releases   
fix by add a manifest file to exe vc-project, see: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

**Comment by florian-gandon** [comment]
Thank you for the quick fix !
It is working perfectly.
