### ISSUE TITLE
文件夹合并一直报110或111错误

### ISSUE THREAD

**Issue by CFPanda** [sisong/HDiffPatch#366]
你好，我在使用这个库去做patch包的合并的时候发现，文件级别的合并是成功的，但是文件夹合并失败返回110或111。这个大概是什么原因呢？

**Comment by sisong** [comment]
文件打开失败。
你可以自己查看 错误码表： THPatchResult 
 你看一下错误输出，应该有更详细的原因

**Comment by CFPanda** [comment]
是的，我对照错误码看到了，提示文件打开失败，但是这个文件应该是没问题的。因为这个库我们在安卓和iOS上使用都是正常的，现在是在往鸿蒙上做移植，发现鸿蒙上只能做文件合并，无法做文件夹合并，是不是这个库在鸿蒙上不支持啊，内部是否可能有不兼容的逻辑。

**Comment by sisong** [comment]
怀疑是文件访问权限问题； 或者是某个 C api 不兼容，比如 stat() 或 文件夹 操作函数之类的函数。

建议测试： 单文件之间diff，但diff时添加 -D 参数来创建补丁，如果也能正确合并，那猜测就是目录操作有问题。

另外：失败返回110或111； 是同一个测试吗？还是不同的测试用例？ 按理说，相同的测试应该返回固定的错误码。

**Comment by CFPanda** [comment]
1、我跟着到具体错误码返回的位置的确是stat() 这个方法返回的有问题，返回了-1。
<img width="1110" alt="截屏2023-11-28 14 50 27" src="https://github.com/sisong/HDiffPatch/assets/17490441/cee7929a-f55e-4f23-87be-2dab1cb679b3">
2、失败返回110或111，都是执行的文件夹合并，只是文件夹不一样。

**Comment by CFPanda** [comment]
**建议测试： 单文件之间diff，但diff时添加 -D 参数来创建补丁。**
这个我试了，加上-D参数后，文件也合并失败了，返回错误码9。

**Comment by sisong** [comment]
那就是stat函数不兼容了。  可以看看这时errno的值，就知道原因了

**Comment by sisong** [comment]
”返回错误码9“   单文件合并时，因为添加了-D，所以需要用目录间的补丁合并方式(比如hpatch_dir)

**Comment by CFPanda** [comment]
errno=13，这个可以修改吗？

**Comment by sisong** [comment]
网上搜索 errno 13， 得到 Permission denied 
即 访问权限问题，被操作系统拒绝访问了。

**Comment by CFPanda** [comment]
好的，感谢解答～
