### ISSUE TITLE
"get oldPath type ERROR!" on Windows XP

### ISSUE THREAD

**Issue by pkr-sadx** [sisong/HDiffPatch#368]
Hello, thank you for making this extremely useful tool.

I've been trying to compile a Windows XP compatible version of hpatchz.exe for a retro project I'm working on. It compiles successfully in VS2022 after changing platform toolset to v141_xp for all projects and setting subsystem to CONSOLE. The program itself runs on Windows XP, however it fails to apply the patch with `get oldPath type ERROR!`. The same executable with the same command line arguments applies the patch successfully on Windows 7 or later. Do you know what causes this difference and what changes to the code are required to get XP compatibility?

I realize this is a pretty uncommon issue, so I am not requesting any support for XP, but if there's a way to get it working on XP I'd appreciate it if you could let me know. Thanks!

EDIT: Forgot to say, the patch I'm trying to apply is a folder patch. Individual file patches appear to be working fine.

**Comment by mgrinzPlayer** [comment]
Which source? tag/v4.6.7 v4.6.8 or latest tag/v4.6.9

**Comment by pkr-sadx** [comment]
Hi, thank you for the response. I tried v4.6.7 and the latest commit, both with the same result. I'll be happy to test on a Windows XP VM and on real hardware.

**Comment by mgrinzPlayer** [comment]
@pkr-sadx I compiled it with MSYS2 + mingw-w64 + patched HDiffPatch makefile and patched zstd threading.c/threading.h
It successfully patched folder on my WinXPSP3. Note: it was source v.4.6.3 and packages from that time.
I will try with latest commits (and latest packages).

**Comment by sisong** [comment]
@mgrinzPlayer 
The cmdline you compile on mingw，it call stat() default, which should does not support file larger than 4GB.

@pkr-sadx
recode _hpatch_getPathStat_noEndDirSeparator() to:  
```
    struct stat  s;
    int          rt;
    assert(out_type!=0);
    memset(&s,0,sizeof(s));
    rt = stat(path_utf8,&s); //only for test,not support file larger than 4GB
    ... <following the original code> ...
```

**Comment by pkr-sadx** [comment]
@sisong I changed `file_for_patch.c` (latest commit) like this and recompiled.
![image](https://github.com/sisong/HDiffPatch/assets/147223739/2cbb70be-96e3-47dd-a69a-9a8c43fb985e)


Unfortunately I'm still getting the same error on XP. I've also tried changing `_IS_USED_WIN32_UTF8_WAPI` in `file_for_patch.h` to 0 both with and without the above change, no luck.

@mgrinzPlayer I've been trying with VS2022 until now, will try with your setup, thanks.

**Comment by mgrinzPlayer** [comment]
I made some patches to the makefile, so it is using stat64. Let me remove my other custom patches and post the needed patche here.

**Comment by mgrinzPlayer** [comment]
Good. I'm glad it worked for you.

There's one tiny problem, currently, 32bit hdiffz (original release from git and my msys2-mingw-w64 build) can not allocate more than 2GB. I ensured that LAW (large address aware) is set on both EXE files.

If I'm not wrong, if you process 5GB old and 5GB new file and `-p-1 -s-32`, it should take about (5368709120*16/32) bytes of memory. Which is about 2.5GB.  Formula is O(oldFileSize*16/matchBlockSize + ...)

For me, 32bit hdiffz didn't allocate more than 2GB. Under WinXP32bit, with /3GB switch, memory limit is 3GB. Under newer Win64bit, memory limit is 4GB - [info link](https://learn.microsoft.com/pl-pl/windows/win32/memory/memory-limits-for-windows-releases?redirectedfrom=MSDN)

**Comment by sisong** [comment]
@pkr-sadx 
I update some test code for WinXP, swap stat() to GetFileAttributesEx():      
https://github.com/sisong/HDiffPatch/tree/dev-forWinXP
