### ISSUE TITLE
get older file ERROR 

### ISSUE THREAD

**Issue by pquy37** [sisong/HDiffPatch#373]
"input oldFile oldDataSize 3398147240 != diffFile saved oldDataSize 3436290185 ERROR!"
then it became " THIS APP CANT RUN ON PC "

**Comment by sisong** [comment]
I tried cmline under windows\linux\macos OS, but I didn't recurrence the similar problem.    
What are your test OS? Did you compile it by yourself? and What are your parameters when run hdiffz?

**Comment by pquy37** [comment]
i've added ""-info diffFile" before the line code so it became " Cant run on Pc"
and i just wanna update patch of game xD

**Comment by pquy37** [comment]
D\> WHERE hpatchez.exe is   "D:\ WHERE path need update" "D:\WHERE the update file ( diff )" "D:\WHERE i wanna put my new file "

**Comment by sisong** [comment]
"-info diffFile" added from v4.6.9，you can see version by run $hpatchz -v

**Comment by pquy37** [comment]
how can i fix that XD?

**Comment by pquy37** [comment]
like i wanna update my file and Error 
so how can i fix that and update my file xD,pls ( im noob :v )

**Comment by sisong** [comment]
you can  download   https://github.com/sisong/HDiffPatch/releases/download/v4.6.9/hdiffpatch_v4.6.9_bin_windows64.zip for update hpatchz.   
but can't fixed this problem, because your owner oldFile not the oldFile when diff; so the patchFile can't update your oldFile.

**Comment by pquy37** [comment]
"your owner oldFile not the oldFile when diff" 
This means that the file is only updated by the developer ? or I did it some wrong way.I did see how to do it and follow it but it didn't work very well

**Comment by pquy37** [comment]
can you suggest me xd ?

**Comment by pquy37** [comment]
i got it
hahahaha 
tks you 
i try so hard
