### ISSUE TITLE
能否让编译更简单？

### ISSUE THREAD

**Issue by acgnfun** [sisong/HDiffPatch#374]
在编译前还需要下载第三方库的操作比较复杂，另外还会使目录结构变得更复杂。

如果我决定删除一些不在使用的本地存储库，我就要仔细区分究竟哪些属于该存储库，哪些不属于，这十分糟糕。

能否将这些第三方库放入源码目录，使其可随源码下载，如果认为这会占用存储库大小，则可以通过添加子模块的方式，将这些第三方库作为子模块，这可以避免占用存储库空间

**Comment by sisong** [comment]
你可以试试
https://github.com/sisong/HDiffPatch/releases/download/v4.6.9/hdiffpatch_v4.6.9_sources.zip

**Comment by sisong** [comment]
建立了一个项目 https://github.com/sisong/HDiffPatch5 来管理依赖仓库，以避免代码版本不匹配等问题。
