### ISSUE TITLE
[Request] View list of files in diff file

### ISSUE THREAD

**Issue by antrv** [sisong/HDiffPatch#376]
Hi. Is it possible to view the list of files in diff file that are different in old and new folder?
If not, please add command line switch like '-info' or additionally to '-info'
Thanks

**Comment by sisong** [comment]
There are no development plans right now: because I haven't figured out how to display these file names and what exactly the feature is for;  the number of files can be very large.     
It's also uncertain if this will be possible, the infos in diffFile may not be enough to implement it.

**Comment by knowhatamine** [comment]
Even when I specify the same directory as in and out, I always get 24 differences. Would really like to know which files these are.

When not ignoring any files it is a lot more (hundreds).


Running command hdiffz -block-0 -m-6 -SD -d -f -p-8 -c-lzma2-9-16m -g#ignorePath#.git*#node_modules*#.vscode* /home/fab/buman/home--fab/dom2 /home/fab/buman/home--fab/dom1 /home/fab/buman/home--fab/dom.patches/1710403364407 ...
Output: oldDir : "/home/fab/buman/home--fab/dom2/"
newDir : "/home/fab/buman/home--fab/dom1/"
outDiff: "/home/fab/buman/home--fab/dom.patches/1710403364407"
hdiffz run dir diff with compress plugin: "lzma2"
hdiffz run dir diff with checksum plugin: "fadler64"

  ignore file : "/home/fab/buman/home--fab/dom2/node_modules/"
  ignore file : "/home/fab/buman/home--fab/dom2/.gitignore"
  ignore file : "/home/fab/buman/home--fab/dom2/.git/"
  ignore file : "/home/fab/buman/home--fab/dom2/.vscode/"
  ignore file : "/home/fab/buman/home--fab/dom1/node_modules/"
  ignore file : "/home/fab/buman/home--fab/dom1/.gitignore"
  ignore file : "/home/fab/buman/home--fab/dom1/.git/"
  ignore file : "/home/fab/buman/home--fab/dom1/.vscode/"
      old path count: 41096
      new path count: 41096 (fileCount:41072)
     same file count: 41072 (dataSize: 97197397)
  ref old file count: 0
 diff new file count: 0

run hdiffz:
  oldRefSize  : 0
  newRefSize  : 0 (all newSize: 97197397)
  (used one lzma2 dictSize: 4524486  (input data: 4524486))
  (used one lzma2 dictSize: 4096  (input data: 6))
  diffDataSize: 28
  diff    time: 0.000 s

diffDataSize  : 76460
dir  diff time: 1.063 s
  out dirDiffFile ok!

all   time: 1.116 s

**Comment by sisong** [comment]
'diffDataSize : 76460'     
diffdata only 28 bytes, but diffFile saved all new flies's names, so 76k
