### ISSUE TITLE
A "CreateSignature" for diff tool would be nice

### ISSUE THREAD

**Issue by WindowsNT** [sisong/HDiffPatch#378]
I am considering using this for live updates of my apps. Currently I use Microsoft's RDC implementation.

It would be nice if there was a signature tool so the signatures are kept offline.
For example:

Old folder = in web
New folder = in my PC.

I could generate a signature for the old folder for the diff tool to use it instead of having to download again the old folder from my site in order to compare it with the newer folder in my PC.Therefore, a diff can be created without the original source to be present, only it's signature.

MSRDC supports that but of course, only Windows.

Best.

**Comment by sisong** [comment]
> a diff can be created without the original source to be present, only it's signature.    

hdiffpatch lib have a demo [hsynz](https://github.com/sisong/hsynz), only used new data's hash data, to create any old datas's diff file.    

 Is it possible to meet your needs?

**Comment by WindowsNT** [comment]
Basically, the idea is this:

1. I have a folder in my local system which is duplicated in a remote system. All the file "signatures" are precalculated.
2. When I want to push an update, I update my local folder.
3. At this point I want to generate a diff file for the remote system without the need to compare the new local updated folder with the old folder (which resides in the remote system), but instead do that based on the precalculated signatures which are smaller and can be downloaded from the remote system.

So it would be the same as hdiffz/hpatchz but hdiffz would only create the diff from the precalculated signature file, not from the entire remote directory (which is very large).


So I will take a look to hsynz and see if it works, thanks a lot for your support.
