### ISSUE TITLE
请问能放入aosp中编译吗

### ISSUE THREAD

**Issue by randytian** [sisong/HDiffPatch#385]
我是在安卓环境使用，想把这个工程放入AOSP编译，需要参照哪个方法呢

**Comment by sisong** [comment]
我没有接触过AOSP编译，所以无法提供准确的信息。   
如果使用的make编译系统，那可以借鉴readme的"自己编译"中关于如何在linux上使用make编译的说明。 如果要将项目源代码文件加入已有的某个Makefile中，可以参考本项目根目录下的Makefile文件。   
如果只是想在某个apk中使用patch功能，可以参考"libhpatchz.so for Android"的说明，编译出.so库。

**Comment by randytian** [comment]
感谢作者，AOSP也是利用的Android.mk，我直接放到里面mm编译，报了这个问题，是不是ndk环境是必须的
CFG_TEE_PLUGIN_LOAD_PATH = /vendor/lib64/tee-supplicant/plugins/
FAILED: ninja: 'external/hdiff/HDiffPatch/builds/android_ndk_jni_mk/external/hdiff/HDiffPatch/builds/android_ndk_jni_mk/hpatch_jni.c', needed by 'out/target/product/se1000/obj/SHARED_LIBRARIES/hpatchz_intermediates/external/hdiff/HDiffPatch/builds/android_ndk_jni_mk/hpatch_jni.o', missing and no known rule to make it
10:58:30 ninja failed with: exit status 1

#### failed to build some targets (51 seconds) ####

**Comment by leleliu008** [comment]
@sisong 你如果嫌用Android NDK编译麻烦的话，可以直接使用我写的一个编译工具，他能直接利用GitHub Actions ，不需要你安装在自己的电脑上，非常方便 ， 这是我刚刚编译好的 https://github.com/leleliu008/ndk-pkg-package-manually-build/actions/runs/14719403177
