### ISSUE TITLE
文件路径过长导致合并失败

### ISSUE THREAD

**Issue by wang931150** [sisong/HDiffPatch#386]
在ios手机端实测时，如果传入文件路径过长，会出现 HPATCH_OPENREAD_ERROR
同样，生成文件路径过长，会出现 HPATCH_OPENWRITE_ERROR
是否路径长度受到 127字符长度限制？

**Comment by sisong** [comment]
不知道你如何测试的，按理说 hdiffpatch设计的文件名支持长度为4k，实际上按mac和ios操作系统说明应该可以到2k。

**Comment by wang931150** [comment]
> 不知道你如何测试的，按理说 hdiffpatch设计的文件名支持长度为4k，实际上按mac和ios操作系统说明应该可以到2k。

同样的文件，只进行了重命名，当文件名长一点时，就会返回 2，必须将总长度控制到一定长度之下，才可以正常生成，安卓下没有这个问题。

**Comment by sisong** [comment]
我查询资料，发现MaxOS的限制是文件和目录名称最大长度255，路径总和最长支持1k；   
而我在Mac电脑上测试了hdiffz&hpatchz命令行，都能正确处理长路径:  实际测试的文件名长度超过200字节，文件路径+文件名长度约900字节(3个文件参数总和长度超2k)，并且含中文字符。      
而iOS长度上限制应该是一样的(没有真机测试)，而且库也并没有特别处理和限制。
