### ISSUE TITLE
Command `selfExtractArchive` show help menu instead of self extracting

### ISSUE THREAD

**Issue by Mesteery** [sisong/HDiffPatch#387]
Platform: windows 11
When I run `[selfExtractArchive]` without argument in the directory that I want to patch, it show the help menu instead of self extracting (according to doc: **extract SFX: selfExtractArchive (same as: selfExtractArchive -f "" -X "./")**)

Code to reproduce
```
hpatchz diffFile -X#updater.exe
./updater.exe # show help menu instead of self extracting in current directory
```

By the way `selfExtractArchive -f "" -X "./"` show error: `options -X input count ERROR!`.
Only `selfExtractArchive -f "./" -X "./"` works as intented.

**Comment by sisong** [comment]
The command line argument "" is different from "./", where "" means there is no oldPath, and "./" means that the current directory is oldPath.   
Your diffFile is created with an oldPath, so hpatchz thinks that the params count is no enough when run with default parameter "".   
If you want to change this default parameter of hpatchz, you can edit the C source code: change `oldPath     =kSFX_emptyPath;` to `oldPath     =kSFX_curDefaultPath;`

**Comment by Mesteery** [comment]
Thanks you for your fast response.
Indeed your are right I created my diff file with oldPath.
But the main issue, is when I run directly selfExtractArchive without arguments by double clicking it (or via terminal), it show help menu instead of self extracting.

**Comment by sisong** [comment]
Thank you for your feedback；  
I maybe modify that default logic in the next version.

**Comment by Mesteery** [comment]
Thanks you, it works perfectly now!
