### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by 1029543947** [sisong/HDiffPatch#390]
能否生成兼容bsdiff4.3并且压缩方式是lzma

**Comment by sisong** [comment]
这个就不叫兼容了吧，因为bsdiff4不支持lzma解码。     
如果只是人让hdiffz支持，理论上当然可以（我本地改了一下，都OK）。这需要一些小的修改：   
1. 删除阻止bz2外其他压缩器和解压缩器的代码    
2. 需要修改解压缩器的代码才能兼容（否则就需要保存数据压缩前的大小），参考 _bz2DecompressPlugin_unsz 对 bz2DecompressPlugin的修改。

**Comment by 1029543947** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 1029543947** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
