### ISSUE TITLE
请问有支持鸿蒙的版本吗

### ISSUE THREAD

**Issue by yangyujiang** [sisong/HDiffPatch#392]
如题

**Comment by sisong** [comment]
可以看看分支  https://github.com/sisong/HDiffPatch/tree/dev-forHarmonyOS
只是一个尝试demo，没有真机运行过

**Comment by yangyujiang** [comment]
这个看了，正在研究如何生成一个so库。有具体的编译的操作步骤指引吗

**Comment by sisong** [comment]
我不熟悉开发环境，也没有注册。  印象中是打开项目文件，就能编译出.so

**Comment by resonlei** [comment]
直接把c文件复制到鸿蒙工程构建就行了，调整下jni文件成鸿蒙格式的就行
