### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Hellboy00000** [sisong/HDiffPatch#395]
-s-64 -SD -d -f -p-1 -c-lzma2-9-16m
I understand the 9 is the compression but what the 16m do?

-c-zstd-21-24
This mean the compression is between 21 and 24, right?

Thanks

**Comment by sisong** [comment]
You can read the command line argument description （in readme or  run $hdiffz -h）.     
The '9' or '21' here does refer to the compression level;   
The '16m' here refers to the decompressor dictionary memory size  is '16MB';   
The '24' here means the decompressor dictionary bits is 24 (memory size is '1<<24').

**Comment by Hellboy00000** [comment]
Thanks.
