### ISSUE TITLE
Progress bar for making a diff or applying one? Or at least eta?

### ISSUE THREAD

**Issue by qtqgyt** [sisong/HDiffPatch#396]
Hi, I was wondering if hdiffz will ever add a progress bar. I personally think it would be useful for large files, or just in general. If this has already been proposed, although I couldn't find it upon a quick search, please point it out and I would be happy to close this issue. Thank you in advance.

**Comment by sisong** [comment]
HDIFFZ does not support the display of a progress bar, and there are no plans to add this feature.    
If you want to add it yourself, it should be noted that the time consumption of the various parts of the hdiffz is not evenly proportional.

**Comment by qtqgyt** [comment]
I figured that you cant exactly know the final size, but I thought that even a estimated percentage would be nice. Thanks tho!
