### ISSUE TITLE
关于android中集成HDiffPatch疑问

### ISSUE THREAD

**Issue by lvjiancong** [sisong/HDiffPatch#397]
您好，是否有关于在android中集成HDiffPatch的相关文档。我从编译好的android-diffpatch-master.zip中只看到有patch的方法，如果需要diff的方法，该编译好的so文件是否有包含diff的功能，如果有包含diff的功能，我应该怎么调用？

**Comment by sisong** [comment]
当前的安卓so库只包含patch，不包含diff。    
需要的话需要自己动手修改。
