### ISSUE TITLE
Proposal:SplitDiffData

### ISSUE THREAD

**Issue by SysVR** [sisong/HDiffPatch#398]
Proposal:
Splitting at the specified size during patch generation: A separate plain text index file will be generated. “File name and extension are free to choose.” The mechanism allows for patching the split data by reading the index file during patch application. Additionally, if the size exceeds 4GB during SFX, it will be possible to automatically split into two parts.
The index file used for patching will include:

File name, Checksum data, File size
The file name part can specify the hierarchy from relative paths or absolute paths.

Example:

patch.diff,E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855,1234567890
core\patch.diff,E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855,1234567890
D:\update\core\patch.diff,E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855,1234567890
\update\core\patch.diff,E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855,1234567890
\\localhost\D$\update\core\patch.diff,E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855,1234567890

**Comment by sisong** [comment]
In what scenarios would you use this feature?   
I probably wouldn't have included it in the development plan.     
   
If you need this feature, consider doing it yourself: the patch function supports diffFile as an input stream, and you can abstract multiple files into an input stream by yourself.

**Comment by SysVR** [comment]
thank you reply.

>In what scenarios would you use this feature?
>I probably wouldn't have included it in the development plan.

Storage media such as CDs and DVDs with limited maximum capacity.
Homepage/blog hosting services with limited maximum capacity.
Currently, after generating an SFX, I split it into specified sizes using uncompressed RAR.
I think it would be convenient if HDiffPatch itself had a splitting and merging function, so I am proposal (not requesting) this feature.
