### ISSUE TITLE
请问这个HDiffPatch的补丁相对于原文件能缩小多少？

### ISSUE THREAD

**Issue by wkkkk1** [sisong/HDiffPatch#400]
你好。我下载使用了你的hdiffz和hpatchz工具进行使用，在自己的ota包进行验证，包原来文件大概有250M，生成的补丁文件大概有140M。这种情况合理不，一般补丁的大小会多大呢？

**Comment by sisong** [comment]
创建补丁时加了-c压缩参数了没有？    
ota包数据本身有压缩吗？   
补丁包大小和数据修改量有关。

**Comment by wkkkk1** [comment]
谢谢回复。hdiffz -s

**Comment by wkkkk1** [comment]
谢谢回复，我的命令行验证如下：hdiffz  -c-zstd-21-24 -s   oldPath  newPath     out。     加 -c-zstd-21-24 -s的变化不明显。   ota包本身是四个.tar.gz的压缩包。

**Comment by sisong** [comment]
hdiffpatch对压缩状态的数据不友好，数据修改量应该没有这么大。   不建议对压缩状态的数据直接进行diff。

**Comment by wkkkk1** [comment]
嗯嗯，感谢～
