### ISSUE TITLE
make 编译不过

### ISSUE THREAD

**Issue by BH1SCW** [sisong/HDiffPatch#55]
编译出错， 环境：ubuntu LTS 16.04

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

g++ -O3 -lbz2 -lz   -c -o libHDiffPatch/HDiff/diff.o libHDiffPatch/HDiff/diff.cpp
In file included from libHDiffPatch/HDiff/diff.cpp:29:0:
libHDiffPatch/HDiff/diff.h:63:18: error: expected identifier before ‘*’ token
         size_t  (*maxCompressedSize)(const hdiff_TCompress* compressPlugin,size_t dataSize);
                  ^
libHDiffPatch/HDiff/diff.h:63:76: error: ‘size_t’ has not been declared
         size_t  (*maxCompressedSize)(const hdiff_TCompress* compressPlugin,size_t dataSize);
                                                                            ^
libHDiffPatch/HDiff/diff.h:63:91: error: ISO C++ forbids declaration of ‘size_t’ with no type [-fpermissive]
         size_t  (*maxCompressedSize)(const hdiff_TCompress* compressPlugin,size_t dataSize);
                                                                                           ^
libHDiffPatch/HDiff/diff.h:63:91: error: ‘size_t’ declared as function returning a function
libHDiffPatch/HDiff/diff.h:65:27: error: expected identifier before ‘*’ token
         size_t           (*compress)(const hdiff_TCompress* compressPlugin,
                           ^
libHDiffPatch/HDiff/diff.h:67:93: error: ISO C++ forbids declaration of ‘size_t’ with no type [-fpermissive]
                                      const unsigned char* data,const unsigned char* data_end);
                                                                                             ^
libHDiffPatch/HDiff/diff.h:67:93: error: ‘size_t’ declared as function returning a function
libHDiffPatch/HDiff/diff.h:132:36: error: ‘size_t’ has not been declared
                                    size_t kMatchBlockSize=kMatchBlockSize_default);
                                    ^
libHDiffPatch/HDiff/diff.cpp: In function ‘void {anonymous}::do_compress(std::vector<unsigned char>&, const std::vector<unsigned char>&, const hdiff_TCompress*)’:
libHDiffPatch/HDiff/diff.cpp:423:44: error: ‘const hdiff_TCompress {aka const struct hdiff_TCompress}’ has no member named ‘maxCompressedSize’
         size_t maxCodeSize=compressPlugin->maxCompressedSize(compressPlugin,data.size());
                                            ^
libHDiffPatch/HDiff/diff.cpp:428:41: error: ‘const hdiff_TCompress {aka const struct hdiff_TCompress}’ has no member named ‘compress’
         size_t codeSize=compressPlugin->compress(compressPlugin,
                                         ^
<builtin>: recipe for target 'libHDiffPatch/HDiff/diff.o' failed
make: *** [libHDiffPatch/HDiff/diff.o] Error 1

**Comment by sisong** [comment]
看起来是找不到“ size_t”的定义
