### ISSUE TITLE
 undefined reference to `BZ2_bzCompressInit'

### ISSUE THREAD

**Issue by BH1SCW** [sisong/HDiffPatch#57]
hello， 还是有一些问题， Ubuntu16.04下
g++ -O3 -lbz2 -lz    hdiffz.cpp libhdiffpatch.a   -o hdiffz
/tmp/cc07aHEx.o: In function `_bz2_compress_stream(hdiff_TStreamCompress const*, hpatch_TStreamOutput const*, hpatch_TStreamInput const*)':
hdiffz.cpp:(.text+0x8c): undefined reference to `BZ2_bzCompressInit'
hdiffz.cpp:(.text+0xaf): undefined reference to `BZ2_bzCompressEnd'
hdiffz.cpp:(.text+0x218): undefined reference to `BZ2_bzCompress'
hdiffz.cpp:(.text+0x29b): undefined reference to `BZ2_bzCompress'
hdiffz.cpp:(.text+0x2cb): undefined reference to `BZ2_bzCompressEnd'
hdiffz.cpp:(.text+0x2fe): undefined reference to `BZ2_bzCompressEnd'
/tmp/cc07aHEx.o: In function `_bz2_decompress_part(hpatch_TDecompress const*, void*, unsigned char*, unsigned char*)':
hdiffz.cpp:(.text+0x456): undefined reference to `BZ2_bzDecompress'
/tmp/cc07aHEx.o: In function `_bz2_open(hpatch_TDecompress*, unsigned long, hpatch_TStreamInput const*, unsigned long, unsigned long)':
hdiffz.cpp:(.text+0x516): undefined reference to `BZ2_bzDecompressInit'
/tmp/cc07aHEx.o: In function `_bz2_close(hpatch_TDecompress*, void*)':
hdiffz.cpp:(.text+0x58e): undefined reference to `BZ2_bzDecompressEnd'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'hdiffz' failed
make: *** [hdiffz] Error 1
改成这样可以通过， maintainer改一下makefile吧
 g++ -O3  hdiffz.cpp libhdiffpatch.a  -lbz2 -lz  -o hdiffz

**Comment by sisong** [comment]
你也可以自己提一个mr的
