### ISSUE TITLE
hdiffz使用-zlib选项被系统kill

### ISSUE THREAD

**Issue by yesboyhongtai** [sisong/HDiffPatch#70]
楼主对于sqllite或其他类型的db文件diff有没有建议选项？
目前我使用hdiffz -m -c-zlib 选项运行两个db文件会被系统kill掉，每次都是在运行到占用9648640Kb内存时，Log如下：

hdiffz run with compress plugin: "zlib"
oldDataSize : 394596352
newDataSize : 393560064
Command terminated by signal 11
real_time:      248.52(s)
max_rss:        9648640(Kb)
avg_rss:        0(Kb)
avg_mem:        0(Kb)

**Comment by yesboyhongtai** [comment]
是在服务器上运行被Kill掉的，机器内存大概还有80多个G

**Comment by sisong** [comment]
应该是zlib使用中某个内存错误造成的； 在macos下没有问题，在linux下确实可以复现这个bug；   而换成 -c-bzip2 就没有问题；  会跟进修复这个bug

**Comment by sisong** [comment]
已经修复zlib压缩插件的bug

**Comment by larack8** [comment]
> 已经修复zlib压缩插件的bug

这个是什么样的BUG呢？什么时候提交的呀？
