### ISSUE TITLE
lzma解压过程中多次申请 state_size 和 dictionnary buffer

### ISSUE THREAD

**Issue by Wvirgil123** [sisong/HDiffPatch#75]
https://github.com/sisong/HDiffPatch/blob/acec588163538f957883be5f22bac5f2dd138ff7/libHDiffPatch/HPatch/patch.c#L1118

在使用lzma解压时，会调用两个getStreamClip 函数，该函数里会调用decompressPlugin->open 函数进行申请 state_size buffer 和 dictionnary buffer， 导致重复申请内存

**Comment by sisong** [comment]
应该没有问题，这里只是需要多个压缩流；所以会“重复”申请内存

**Comment by sisong** [comment]
patch时需要多个解压流（最大4个），所以需要多次调用；     
如果还有异议，请重新打开该issue

**Comment by sisong** [comment]
#75你删除了？
应该没有问题，这里只是需要多个压缩流


Wvirgil123 <notifications@github.com> 于2018年10月22日周一 上午10:57写道：
