### ISSUE TITLE
移动平台上以多大文件区分使用patch()/patch_stream()比较好?

### ISSUE THREAD

**Issue by RPG3D** [sisong/HDiffPatch#76]

**Comment by RPG3D** [comment]
此外,hpatch_kStreamCacheSize 默认为1024, 这个调大会有其他影响吗?

**Comment by sisong** [comment]
patch函数执行时都不会额外申请内存； 不提供额外内存给patch函数时，将使用栈空间作为临时内存，这个大小乘以7就是函数最大可能使用的栈空间，这个栈空间越大一般情况下执行速度可能会略快；这个栈空间的上限受线程函数调用栈空间影响，比如一般的体系默认可以使用到1MB等大小；   你可以调大它测试出该极限（栈溢出崩溃），但不建议以太大值作为发布值；

**Comment by sisong** [comment]
patch()/patch_stream() 主要考虑的是内存占用问题，每个函数都会说明；   不是用来区分pc或移动，那哪个更好和应用场景有关
